#!/bin/sh
PPP_IPPARAM="$6"

. /lib/netifd/netifd-proto.sh
proto_init_update "$IFNAME" 0
proto_send_update "$PPP_IPPARAM"

[ -d /etc/ppp/ip-down.d ] && {
	for SCRIPT in /etc/ppp/ip-down.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}

local ppp_demand="`ps aux | grep [p]ppd | grep demand 2>/dev/null`"
[ -n "$ppp_demand" ] && [ "`uci get network.$PPP_IPPARAM.defaultroute`" = "1" ] && route add -net 0.0.0.0/0 $IFNAME
