
#ifndef __AUDIO_COMMON_H__
#define __AUDIO_COMMON_H__


#define FAKE_FOCUS_ID (-2)

#define AUDIO_PP_MAX_INPIN_NUM (4)

#define AUDIO_PP_OUTPIN_ID (AUDIO_PP_MAX_INPIN_NUM+1)  // can't less than AUDIO_PP_MAX_INPIN_NUM
#define AUDIO_PP_DAP_INPIN_ID (AUDIO_PP_MAX_INPIN_NUM+2)
#define AUDIO_PP_DAP_OUTPIN_ID (AUDIO_PP_MAX_INPIN_NUM)


#define AUDIO_RING_LIST_MAX (16)

#endif
