LOCAL_DIR := $(GET_LOCAL_DIR)

MODULE := $(LOCAL_DIR)

WITH_SMP ?= 1

LK_HEAP_IMPLEMENTATION ?= dlmalloc

MODULE_SRCS += \
	$(LOCAL_DIR)/debug.c \
	$(LOCAL_DIR)/platform.c \
	$(LOCAL_DIR)/secondary_boot.S \
	$(LOCAL_DIR)/uart.c \
	$(LOCAL_DIR)/mmu.c \
	$(LOCAL_DIR)/ops.S \
	$(LOCAL_DIR)/cpu.c \
	$(LOCAL_DIR)/rtkemmc.c \
	$(LOCAL_DIR)/rtkspi.c \
	$(LOCAL_DIR)/rtknand.c \
	$(LOCAL_DIR)/ddr.c \
	$(LOCAL_DIR)/bdinfo.c \
	$(LOCAL_DIR)/gpio.c \
	$(LOCAL_DIR)/hdmitx/logo_disp_read_edid.c \
	$(LOCAL_DIR)/dptx/logo_disp_dptx.c \
	$(LOCAL_DIR)/rpmb.c \
	$(LOCAL_DIR)/pwm.c \
	$(LOCAL_DIR)/boot_partition.c \
	$(LOCAL_DIR)/rtkirda.c \
	$(LOCAL_DIR)/rtkusb.c \
	$(LOCAL_DIR)/rtkusb-phy.c

MODULE_EXTRA_OBJS += \
          $(LOCAL_DIR)/libefuse.a
	
MEMBASE := 0x00000000
MEMSIZE ?= 0x40000000   # 1GB
KERNEL_LOAD_OFFSET := 0x20000 # 128k

MODULE_DEPS += \
	lib/cbuf \
	lib/fdt \
	dev/interrupt/arm_gic \
	dev/timer/arm_generic \
	dev/md \
	dev/net/rtl8168 \
	platform/rtd1295/acpu_image \
	external/lib/factory

GLOBAL_DEFINES += \
	MEMBASE=$(MEMBASE) \
	MEMSIZE=$(MEMSIZE) \
	HEAP_START=$(HEAP_START) \
	HEAP_SIZE=$(HEAP_SIZE) \
	HAVE_MREMAP=0 \
	PLATFORM_SUPPORTS_PANIC_SHELL=1 \
	FLASH_TYPE=$(FLASH_TYPE) \
	LK_OFFSET=$(KERNEL_LOAD_OFFSET)

# GLOBAL_DEFINES += MMU_WITH_TRAMPOLINE=1 \

LINKER_SCRIPT += \
	$(BUILDDIR)/system-onesegment.ld

#PWM defines
GLOBAL_DEFINES += \
	PWM_0_PIN_0=$(PWM_0_PIN_0) \
	PWM_0_PIN_1=$(PWM_0_PIN_1) \
	PWM_1_PIN_0=$(PWM_1_PIN_0) \
	PWM_1_PIN_1=$(PWM_1_PIN_1) \
	PWM_2_PIN_0=$(PWM_2_PIN_0) \
	PWM_2_PIN_1=$(PWM_2_PIN_1) \
	PWM_3_PIN_0=$(PWM_3_PIN_0) \
	PWM_3_PIN_1=$(PWM_3_PIN_1)

#IRDA defines
GLOBAL_DEFINES += \
	IR_PROTOCOL=$(IR_PROTOCOL) \
	IR_SCANCODE_MASK=$(IR_SCANCODE_MASK) \
	IR_WAKEUP_SCANCODE=$(IR_WAKEUP_SCANCODE) \
	IR_CUS_MASK=$(IR_CUS_MASK) \
	IR_CUS_CODE=$(IR_CUS_CODE)

# CRYPTO configuration
ifeq ($(HW_MCP),1)
MODULE_DEPS += dev/mcp
GLOBAL_DEFINES += HW_MCP=1
endif #HW_MCP

ifeq ($(LK_WAS_LOADED_FROM_SPI),1)
GLOBAL_DEFINES += LK_WAS_LOADED_FROM_SPI
endif #LK_WAS_LOADED_FROM_SPI

ifeq ($(VMX),1)
GLOBAL_DEFINES += VMX
endif #VMX

ifeq ($(VMX_3RD_PARTY),1)
GLOBAL_DEFINES += VMX_3RD_PARTY
endif #VMX

ifeq ($(VMX_BL),1)
GLOBAL_DEFINES += VMX_BL
endif #VMX

ifeq ($(USB_GPIO_SETTING),1)
#1295/1296 USB GPIO setting
GLOBAL_DEFINES += \
	USB_PORT0_GPIO_TYPE=\"$(USB_PORT0_GPIO_TYPE)\" \
	USB_PORT0_GPIO_NUM=$(USB_PORT0_GPIO_NUM) \
	USB_PORT0_TYPE_C_RD_GPIO_TYPE=\"$(USB_PORT0_TYPE_C_RD_GPIO_TYPE)\" \
	USB_PORT0_TYPE_C_RD_GPIO_NUM=$(USB_PORT0_TYPE_C_RD_GPIO_NUM) \
	USB_PORT1_GPIO_TYPE=\"$(USB_PORT1_GPIO_TYPE)\" \
	USB_PORT1_GPIO_NUM=$(USB_PORT1_GPIO_NUM) \
	USB_PORT2_GPIO_TYPE=\"$(USB_PORT2_GPIO_TYPE)\" \
	USB_PORT2_GPIO_NUM=$(USB_PORT2_GPIO_NUM) \
	USB_PORT3_GPIO_TYPE=\"$(USB_PORT3_GPIO_TYPE)\" \
	USB_PORT3_GPIO_NUM=$(USB_PORT3_GPIO_NUM) \
	RTD1296_USB_PORT0_GPIO_TYPE=\"$(RTD1296_USB_PORT0_GPIO_TYPE)\" \
	RTD1296_USB_PORT0_GPIO_NUM=$(RTD1296_USB_PORT0_GPIO_NUM) \
	RTD1296_USB_PORT0_TYPE_C_RD_GPIO_TYPE=\"$(RTD1296_USB_PORT0_TYPE_C_RD_GPIO_TYPE)\" \
	RTD1296_USB_PORT0_TYPE_C_RD_GPIO_NUM=$(RTD1296_USB_PORT0_TYPE_C_RD_GPIO_NUM) \
	RTD1296_USB_PORT1_GPIO_TYPE=\"$(RTD1296_USB_PORT1_GPIO_TYPE)\" \
	RTD1296_USB_PORT1_GPIO_NUM=$(RTD1296_USB_PORT1_GPIO_NUM) \
	RTD1296_USB_PORT2_GPIO_TYPE=\"$(RTD1296_USB_PORT2_GPIO_TYPE)\" \
	RTD1296_USB_PORT2_GPIO_NUM=$(RTD1296_USB_PORT2_GPIO_NUM) \
	RTD1296_USB_PORT3_GPIO_TYPE=\"$(RTD1296_USB_PORT3_GPIO_TYPE)\" \
	RTD1296_USB_PORT3_GPIO_NUM=$(RTD1296_USB_PORT3_GPIO_NUM)
endif

include make/module.mk
