/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REMOTE_MALLOC_DATA_H_RPCGEN
#define _REMOTE_MALLOC_DATA_H_RPCGEN

#include <RPCstruct.h>

#endif /* !_REMOTE_MALLOC_DATA_H_RPCGEN */
