/**@@@+++@@@@******************************************************************
**
** Microsoft (r) PlayReady (r)
** Copyright (c) Microsoft Corporation. All rights reserved.
**
***@@@---@@@@******************************************************************
*/

/*
 * pfddrmmtpextensions.h
 *
 * #defines used by the MTP extensions for PFD
 *
 */

#ifndef _PFDDRMMTPEXTENSIONS_H_
#define _PFDDRMMTPEXTENSIONS_H_

ENTER_PK_NAMESPACE;

/*
 * MTP operations for Advanced A/V Transfer (AAVT) extensions
 */
#define MTP_OPCODE_AAVT_OPENMEDIASESSION       0X9170
#define MTP_OPCODE_AAVT_CLOSEMEDIASESSION      0X9171
#define MTP_OPCODE_AAVT_GETNEXTDATABLOCK       0X9172
#define MTP_OPCODE_AAVT_SETCURRENTTIMEPOSITION 0X9173

/*
 * MTP response codes for Microsoft Advanced A/V Transfer (AAVT) extensions
 */
#define MTP_RESPONSECODE_AAVT_INVALID_MEDIA_SESSION_ID    0XA170
#define MTP_RESPONSECODE_AAVT_MEDIA_SESSION_LIMIT_REACHED 0XA171
#define MTP_RESPONSECODE_AAVT_NO_MORE_DATA                0XA172


/*
 * MTP operations for WMDRMND extensions
 */
#define MTP_OPCODE_WMDRMND_SENDREGISTRATIONREQUEST      0X9180
#define MTP_OPCODE_WMDRMND_GETREGISTRATIONRESPONSE      0X9181
#define MTP_OPCODE_WMDRMND_GETPROXIMITYCHALLENGE        0X9182
#define MTP_OPCODE_WMDRMND_SENDPROXIMITYRESPONSE        0X9183
#define MTP_OPCODE_WMDRMND_SENDWMDRMNDLICENSEREQUEST    0X9184
#define MTP_OPCODE_WMDRMND_GETWMDRMNDLICENSERESPONSE    0X9185

/*
 * MTP response codes for WMDRMND extensions
 */
#define MTP_RESPONSECODE_WMDRMND_INVALID_CERTIFICATE                 0xA180
#define MTP_RESPONSECODE_WMDRMND_CERTIFICATE_REVOKED                 0xA181
#define MTP_RESPONSECODE_WMDRMND_MUST_APPROVE                        0xA182
#define MTP_RESPONSECODE_WMDRMND_LICENSE_UNAVAILABLE                 0xA183
#define MTP_RESPONSECODE_WMDRMND_TRANSMITTER_FAILURE                 0xA184
#define MTP_RESPONSECODE_WMDRMND_DEVICE_LIMIT_REACHED                0xA185
#define MTP_RESPONSECODE_WMDRMND_UNABLE_TO_VERIFY_PROXIMITY          0xA186
#define MTP_RESPONSECODE_WMDRMND_MUST_REGISTER                       0xA187
#define MTP_RESPONSECODE_WMDRMND_MUST_REVALIDATE                     0xA188
#define MTP_RESPONSECODE_WMDRMND_INVALID_PROXIMITY_RESPONSE          0xA189
#define MTP_RESPONSECODE_WMDRMND_INVALID_SESSION                     0xA18A
#define MTP_RESPONSECODE_WMDRMND_UNABLE_TO_OPEN_FILE                 0xA18B
#define MTP_RESPONSECODE_WMDRMND_UNSUPPORTED_PROTOCOL_VERSION        0xA18C
#define MTP_RESPONSECODE_WMDRMND_BAD_REQUEST                         0xA18D
#define MTP_RESPONSECODE_WMDRMND_INVALID_TRANSACTION_REGISTRATION_ID 0xA18E

/*
 * Mappings of PTP and MTP object formats
 */
#define  WMDRMND_FORMATCODE_UNDEFINED      0x3000
#define  WMDRMND_FORMATCODE_ASSOCIATION    0x3001
#define  WMDRMND_FORMATCODE_SCRIPT         0x3002
#define  WMDRMND_FORMATCODE_EXECUTABLE     0x3003
#define  WMDRMND_FORMATCODE_TEXT           0x3004
#define  WMDRMND_FORMATCODE_HTML           0x3005
#define  WMDRMND_FORMATCODE_DPOF           0x3006
#define  WMDRMND_FORMATCODE_AIFF           0x3007
#define  WMDRMND_FORMATCODE_WAVE           0x3008
#define  WMDRMND_FORMATCODE_MP3            0x3009
#define  WMDRMND_FORMATCODE_AVI            0x300A
#define  WMDRMND_FORMATCODE_MPEG           0x300B
#define  WMDRMND_FORMATCODE_ASF            0x300C

#define  WMDRMND_FORMATCODE_UNDEFINED_FIRMWARE              0xB802
#define  WMDRMND_FORMATCODE_WINDOWS_IMAGE_FORMAT            0xB881
#define  WMDRMND_FORMATCODE_UNDEFINED_AUDIO                 0xB900
#define  WMDRMND_FORMATCODE_WMA                             0xB901
#define  WMDRMND_FORMATCODE_UNDEFINED_VIDEO                 0xB980
#define  WMDRMND_FORMATCODE_WMV                             0xB981
#define  WMDRMND_FORMATCODE_UNDEFINED_COLLECTION            0xBA00
#define  WMDRMND_FORMATCODE_ABSTRACT_MULTIMEDIA_ALBUM       0xBA01
#define  WMDRMND_FORMATCODE_ABSTRACT_IMAGE_ALBUM            0xBA02
#define  WMDRMND_FORMATCODE_ABSTRACT_AUDIO_ALBUM            0xBA03
#define  WMDRMND_FORMATCODE_ABSTRACT_VIDEO_ALBUM            0xBA04
#define  WMDRMND_FORMATCODE_ABSTRACT_AV_PLAYLIST            0xBA05
#define  WMDRMND_FORMATCODE_ABSTRACT_CONTACT_GROUP          0xBA06
#define  WMDRMND_FORMATCODE_ABSTRACT_MESSAGE_FOLDER         0xBA07
#define  WMDRMND_FORMATCODE_ABSTRACT_CHAPTERED_PRODUCTION   0xBA08
#define  WMDRMND_FORMATCODE_WPL_PLAYLIST                    0xBA10
#define  WMDRMND_FORMATCODE_M3U_PLAYLIST                    0xBA11
#define  WMDRMND_FORMATCODE_MPL_PLAYLIST                    0xBA12
#define  WMDRMND_FORMATCODE_ASX_PLAYLIST                    0xBA13
#define  WMDRMND_FORMATCODE_PLS_PLAYLIST                    0xBA14
#define  WMDRMND_FORMATCODE_UNDEFINED_DOCUMENT              0xBA80
#define  WMDRMND_FORMATCODE_ABSTRACT_DOCUMENT               0xBA81
#define  WMDRMND_FORMATCODE_UNDEFINED_MESSAGE               0xBB00
#define  WMDRMND_FORMATCODE_ABSTRACT_MESSAGE                0xBB01
#define  WMDRMND_FORMATCODE_UNDEFINED_CONTACT               0xBB80
#define  WMDRMND_FORMATCODE_ABSTRACT_CONTACT                0xBB81
#define  WMDRMND_FORMATCODE_VCARD2                          0xBB82
#define  WMDRMND_FORMATCODE_VCARD3                          0xBB83
#define  WMDRMND_FORMATCODE_UNDEFINED_CALENDAR_ITEM         0xBE00
#define  WMDRMND_FORMATCODE_ABSTRACT_CALENDAR_ITEM          0xBE01
#define  WMDRMND_FORMATCODE_VCALENDAR1                      0xBE02
#define  WMDRMND_FORMATCODE_UNDEFINED_WINDOWS_EXECUTABLE    0xBE80

EXIT_PK_NAMESPACE;    

#endif  /* _PFDDRMMTPEXTENSIONS_H_ */
