/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VIDEORPCBASEDS_H_RPCGEN
#define _VIDEORPCBASEDS_H_RPCGEN

#include <rt/misc/RPCstruct.h>

#include "VideoRPCBaseDS_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#define printf(str)

#include <rpc_common.h>

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_RPC_RINGBUFFER (XDR *, RPC_RINGBUFFER*);
extern  bool_t xdr_VIDEO_VF_TYPE (XDR *, VIDEO_VF_TYPE*);
extern  bool_t xdr_VIDEO_LOW_DELAY (XDR *, VIDEO_LOW_DELAY*);
extern  bool_t xdr_VIDEO_IMG_TYPE (XDR *, VIDEO_IMG_TYPE*);
extern  bool_t xdr_VIDEO_JPEG_ROTATION (XDR *, VIDEO_JPEG_ROTATION*);
extern  bool_t xdr_VIDEO_ASSISTANT_TYPE (XDR *, VIDEO_ASSISTANT_TYPE*);
extern  bool_t xdr_VIDEO_ASSISTANT_ACTION (XDR *, VIDEO_ASSISTANT_ACTION*);
extern  bool_t xdr_VIDEO_JPEG_MIRROR (XDR *, VIDEO_JPEG_MIRROR*);
extern  bool_t xdr_IMG_TARGET_FORMAT (XDR *, IMG_TARGET_FORMAT*);
extern  bool_t xdr_IMG_TARGET_POSITION (XDR *, IMG_TARGET_POSITION*);
extern  bool_t xdr_IMG_SOURCE_PICTURE_SELECT (XDR *, IMG_SOURCE_PICTURE_SELECT*);
extern  bool_t xdr_IMG_STATUS (XDR *, IMG_STATUS*);
extern  bool_t xdr_VIDEO_COLOR_FMT (XDR *, VIDEO_COLOR_FMT*);
extern  bool_t xdr_VIDEO_TRANSITION_TYPE (XDR *, VIDEO_TRANSITION_TYPE*);
extern  bool_t xdr_VIDEO_FORMAT (XDR *, VIDEO_FORMAT*);
extern  bool_t xdr_VIDEO_STREAM_TYPE (XDR *, VIDEO_STREAM_TYPE*);
extern  bool_t xdr_VIDEO_DECODER_CC_BYPASS_MODE (XDR *, VIDEO_DECODER_CC_BYPASS_MODE*);
extern  bool_t xdr_VO_STANDARD (XDR *, VO_STANDARD*);
extern  bool_t xdr_VO_PEDESTAL_TYPE (XDR *, VO_PEDESTAL_TYPE*);
extern  bool_t xdr_VO_TV_TYPE (XDR *, VO_TV_TYPE*);
extern  bool_t xdr_VO_HDMI_MODE (XDR *, VO_HDMI_MODE*);
extern  bool_t xdr_VO_HDMI_AUDIO_SAMPLE_FREQ (XDR *, VO_HDMI_AUDIO_SAMPLE_FREQ*);
extern  bool_t xdr_VO_HDMI_COLOR_FMT (XDR *, VO_HDMI_COLOR_FMT*);
extern  bool_t xdr_VO_INTERFACE_TYPE (XDR *, VO_INTERFACE_TYPE*);
extern  bool_t xdr_VO_3D_SOURCE_FORMAT (XDR *, VO_3D_SOURCE_FORMAT*);
extern  bool_t xdr_VO_VBI_ASPECT_RATIO (XDR *, VO_VBI_ASPECT_RATIO*);
extern  bool_t xdr_VO_VBI_COPY_MODE (XDR *, VO_VBI_COPY_MODE*);
extern  bool_t xdr_VO_VBI_APS (XDR *, VO_VBI_APS*);
extern  bool_t xdr_VO_VBI_SUBTITLE_MODE (XDR *, VO_VBI_SUBTITLE_MODE*);
extern  bool_t xdr_VO_VIDEO_PLANE (XDR *, VO_VIDEO_PLANE*);
extern  bool_t xdr_VO_RESCALE_MODE (XDR *, VO_RESCALE_MODE*);
extern  bool_t xdr_VO_DEINT_MODE (XDR *, VO_DEINT_MODE*);
extern  bool_t xdr_VO_OSD_LPF_TYPE (XDR *, VO_OSD_LPF_TYPE*);
extern  bool_t xdr_VO_OSD_COLOR_FORMAT (XDR *, VO_OSD_COLOR_FORMAT*);
extern  bool_t xdr_VO_OSD_RGB_ORDER (XDR *, VO_OSD_RGB_ORDER*);
extern  bool_t xdr_VO_GRAPHIC_PLANE (XDR *, VO_GRAPHIC_PLANE*);
extern  bool_t xdr_VO_GRAPHIC_STORAGE_MODE (XDR *, VO_GRAPHIC_STORAGE_MODE*);
extern  bool_t xdr_VO_COLOR (XDR *, VO_COLOR*);
extern  bool_t xdr_VO_RECTANGLE (XDR *, VO_RECTANGLE*);
extern  bool_t xdr_VO_SUBPIC_COLORMAP (XDR *, VO_SUBPIC_COLORMAP*);
extern  bool_t xdr_VO_ZOOM_TYPE (XDR *, VO_ZOOM_TYPE*);
extern  bool_t xdr_SP_STREAM_TYPE (XDR *, SP_STREAM_TYPE*);
extern  bool_t xdr_TVE_BOARD_TYPE (XDR *, TVE_BOARD_TYPE*);
extern  bool_t xdr_VIDEO_BUFFER_TYPE (XDR *, VIDEO_BUFFER_TYPE*);
extern  bool_t xdr_VIDEO_DNR_MODE (XDR *, VIDEO_DNR_MODE*);
extern  bool_t xdr_VIDEO_CODEC_CONTROL_BIT (XDR *, VIDEO_CODEC_CONTROL_BIT*);
extern  bool_t xdr_VIDEO_PHOTO_DEC_JPEG_CTRL (XDR *, VIDEO_PHOTO_DEC_JPEG_CTRL*);
extern  bool_t xdr_VIDEO_PHOTO_DEC_BITMAP_CTRL (XDR *, VIDEO_PHOTO_DEC_BITMAP_CTRL*);
extern  bool_t xdr_VIDEO_PHOTO_DEC_TIFF_CTRL (XDR *, VIDEO_PHOTO_DEC_TIFF_CTRL*);
extern  bool_t xdr_VIDEO_PHOTO_DEC_GIF_CTRL (XDR *, VIDEO_PHOTO_DEC_GIF_CTRL*);
extern  bool_t xdr_VIDEO_PHOTO_DEC_PNG_CTRL (XDR *, VIDEO_PHOTO_DEC_PNG_CTRL*);
extern  bool_t xdr_MIXER_WIN (XDR *, MIXER_WIN*);
extern  bool_t xdr_YUV_FMT (XDR *, YUV_FMT*);
extern  bool_t xdr_PLANE_MIXER_WIN (XDR *, PLANE_MIXER_WIN*);
extern  bool_t xdr_ENUM_SEI_3D_TYPE (XDR *, ENUM_SEI_3D_TYPE*);
extern  bool_t xdr_ENUM_VIDEO_DEC_PRIVATEINFO (XDR *, ENUM_VIDEO_DEC_PRIVATEINFO*);
extern  bool_t xdr_ENUM_VIDEO_VO_PRIVATEINFO (XDR *, ENUM_VIDEO_VO_PRIVATEINFO*);
extern  bool_t xdr_VIDEO_RPC_DEC_PRIVATEINFO_INPUT_PARAMETERS (XDR *, VIDEO_RPC_DEC_PRIVATEINFO_INPUT_PARAMETERS*);
extern  bool_t xdr_VIDEO_RPC_DEC_PRIVATEINFO_OUTPUT_PARAMETERS (XDR *, VIDEO_RPC_DEC_PRIVATEINFO_OUTPUT_PARAMETERS*);
extern  bool_t xdr_VIDEO_RPC_DEC_PRIVATEINFO_SEI_INFO (XDR *, VIDEO_RPC_DEC_PRIVATEINFO_SEI_INFO*);
extern  bool_t xdr_VIDEO_RPC_VO_PRIVATEINFO_INPUT_PARAMETERS (XDR *, VIDEO_RPC_VO_PRIVATEINFO_INPUT_PARAMETERS*);
extern  bool_t xdr_VIDEO_RPC_VO_PRIVATEINFO_OUTPUT_PARAMETERS (XDR *, VIDEO_RPC_VO_PRIVATEINFO_OUTPUT_PARAMETERS*);
extern  bool_t xdr_VIDEO_ENUM_PRIVATEINFO (XDR *, VIDEO_ENUM_PRIVATEINFO*);
extern  bool_t xdr_VIDEO_RPC_PRIVATEINFO_PARAMETERS (XDR *, VIDEO_RPC_PRIVATEINFO_PARAMETERS*);
extern  bool_t xdr_VIDEO_RPC_PRIVATEINFO_RETURNVAL (XDR *, VIDEO_RPC_PRIVATEINFO_RETURNVAL*);

#else /* K&R C */
extern bool_t xdr_RPC_RINGBUFFER ();
extern bool_t xdr_VIDEO_VF_TYPE ();
extern bool_t xdr_VIDEO_LOW_DELAY ();
extern bool_t xdr_VIDEO_IMG_TYPE ();
extern bool_t xdr_VIDEO_JPEG_ROTATION ();
extern bool_t xdr_VIDEO_ASSISTANT_TYPE ();
extern bool_t xdr_VIDEO_ASSISTANT_ACTION ();
extern bool_t xdr_VIDEO_JPEG_MIRROR ();
extern bool_t xdr_IMG_TARGET_FORMAT ();
extern bool_t xdr_IMG_TARGET_POSITION ();
extern bool_t xdr_IMG_SOURCE_PICTURE_SELECT ();
extern bool_t xdr_IMG_STATUS ();
extern bool_t xdr_VIDEO_COLOR_FMT ();
extern bool_t xdr_VIDEO_TRANSITION_TYPE ();
extern bool_t xdr_VIDEO_FORMAT ();
extern bool_t xdr_VIDEO_STREAM_TYPE ();
extern bool_t xdr_VIDEO_DECODER_CC_BYPASS_MODE ();
extern bool_t xdr_VO_STANDARD ();
extern bool_t xdr_VO_PEDESTAL_TYPE ();
extern bool_t xdr_VO_TV_TYPE ();
extern bool_t xdr_VO_HDMI_MODE ();
extern bool_t xdr_VO_HDMI_AUDIO_SAMPLE_FREQ ();
extern bool_t xdr_VO_HDMI_COLOR_FMT ();
extern bool_t xdr_VO_INTERFACE_TYPE ();
extern bool_t xdr_VO_3D_SOURCE_FORMAT ();
extern bool_t xdr_VO_VBI_ASPECT_RATIO ();
extern bool_t xdr_VO_VBI_COPY_MODE ();
extern bool_t xdr_VO_VBI_APS ();
extern bool_t xdr_VO_VBI_SUBTITLE_MODE ();
extern bool_t xdr_VO_VIDEO_PLANE ();
extern bool_t xdr_VO_RESCALE_MODE ();
extern bool_t xdr_VO_DEINT_MODE ();
extern bool_t xdr_VO_OSD_LPF_TYPE ();
extern bool_t xdr_VO_OSD_COLOR_FORMAT ();
extern bool_t xdr_VO_OSD_RGB_ORDER ();
extern bool_t xdr_VO_GRAPHIC_PLANE ();
extern bool_t xdr_VO_GRAPHIC_STORAGE_MODE ();
extern bool_t xdr_VO_COLOR ();
extern bool_t xdr_VO_RECTANGLE ();
extern bool_t xdr_VO_SUBPIC_COLORMAP ();
extern bool_t xdr_VO_ZOOM_TYPE ();
extern bool_t xdr_SP_STREAM_TYPE ();
extern bool_t xdr_TVE_BOARD_TYPE ();
extern bool_t xdr_VIDEO_BUFFER_TYPE ();
extern bool_t xdr_VIDEO_DNR_MODE ();
extern bool_t xdr_VIDEO_CODEC_CONTROL_BIT ();
extern bool_t xdr_VIDEO_PHOTO_DEC_JPEG_CTRL ();
extern bool_t xdr_VIDEO_PHOTO_DEC_BITMAP_CTRL ();
extern bool_t xdr_VIDEO_PHOTO_DEC_TIFF_CTRL ();
extern bool_t xdr_VIDEO_PHOTO_DEC_GIF_CTRL ();
extern bool_t xdr_VIDEO_PHOTO_DEC_PNG_CTRL ();
extern bool_t xdr_MIXER_WIN ();
extern bool_t xdr_YUV_FMT ();
extern bool_t xdr_PLANE_MIXER_WIN ();
extern bool_t xdr_ENUM_SEI_3D_TYPE ();
extern bool_t xdr_ENUM_VIDEO_DEC_PRIVATEINFO ();
extern bool_t xdr_ENUM_VIDEO_VO_PRIVATEINFO ();
extern bool_t xdr_VIDEO_RPC_DEC_PRIVATEINFO_INPUT_PARAMETERS ();
extern bool_t xdr_VIDEO_RPC_DEC_PRIVATEINFO_OUTPUT_PARAMETERS ();
extern bool_t xdr_VIDEO_RPC_DEC_PRIVATEINFO_SEI_INFO ();
extern bool_t xdr_VIDEO_RPC_VO_PRIVATEINFO_INPUT_PARAMETERS ();
extern bool_t xdr_VIDEO_RPC_VO_PRIVATEINFO_OUTPUT_PARAMETERS ();
extern bool_t xdr_VIDEO_ENUM_PRIVATEINFO ();
extern bool_t xdr_VIDEO_RPC_PRIVATEINFO_PARAMETERS ();
extern bool_t xdr_VIDEO_RPC_PRIVATEINFO_RETURNVAL ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VIDEORPCBASEDS_H_RPCGEN */
