/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VIDEORPC_AGENT_H_RPCGEN
#define _VIDEORPC_AGENT_H_RPCGEN

#include <rt/misc/RPCstruct.h>

#include "VideoRPC_Agent_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#define printf(str)

#include <RPCBaseDS.h>
#include <VideoRPCBaseDS.h>

#define VIDEO_AGENT 300
#define VERSION 0

struct REG_STRUCT * VIDEO_AGENT_0_register(struct REG_STRUCT *rnode);

#if defined(__STDC__) || defined(__cplusplus)
#define VIDEO_RPC_ToSystem_EndOfStream 2
extern  HRESULT * VIDEO_RPC_ToSystem_EndOfStream_0(VIDEO_RPC_ENDOFSTREAM *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToSystem_EndOfStream_0_svc(VIDEO_RPC_ENDOFSTREAM *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg 5
extern  HRESULT * VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0(VIDEO_RPC_DEC_JPEG_INFO *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0_svc(VIDEO_RPC_DEC_JPEG_INFO *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_DEC_ToSystem_FatalError 8
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_FatalError_0(VIDEO_RPC_DEC_ERROR_INFO *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_FatalError_0_svc(VIDEO_RPC_DEC_ERROR_INFO *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToSystem_ScaleModeSCART 9
extern  HRESULT * VIDEO_RPC_ToSystem_ScaleModeSCART_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToSystem_ScaleModeSCART_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToSystem_VideoHaltDone 11
extern  HRESULT * VIDEO_RPC_ToSystem_VideoHaltDone_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToSystem_VideoHaltDone_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToSystem_VideoAssistant 13
extern  RPCRES_LONG * VIDEO_RPC_ToSystem_VideoAssistant_0(VIDEO_RPC_VideoAssistant *, CLNT_STRUCT *);
extern  RPCRES_LONG * VIDEO_RPC_ToSystem_VideoAssistant_0_svc(VIDEO_RPC_VideoAssistant *, RPC_STRUCT *, RPCRES_LONG *);
#define VIDEO_RPC_ToSystem_DecoderMessage 15
extern  HRESULT * VIDEO_RPC_ToSystem_DecoderMessage_0(VIDEO_RPC_DEC_MESSAGE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToSystem_DecoderMessage_0_svc(VIDEO_RPC_DEC_MESSAGE *, RPC_STRUCT *, HRESULT *);

#else /* K&R C */
#define VIDEO_RPC_ToSystem_EndOfStream 2
extern  HRESULT * VIDEO_RPC_ToSystem_EndOfStream_0();
extern  HRESULT * VIDEO_RPC_ToSystem_EndOfStream_0_svc();
#define VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg 5
extern  HRESULT * VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0();
extern  HRESULT * VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0_svc();
#define VIDEO_RPC_DEC_ToSystem_FatalError 8
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_FatalError_0();
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_FatalError_0_svc();
#define VIDEO_RPC_ToSystem_ScaleModeSCART 9
extern  HRESULT * VIDEO_RPC_ToSystem_ScaleModeSCART_0();
extern  HRESULT * VIDEO_RPC_ToSystem_ScaleModeSCART_0_svc();
#define VIDEO_RPC_ToSystem_VideoHaltDone 11
extern  HRESULT * VIDEO_RPC_ToSystem_VideoHaltDone_0();
extern  HRESULT * VIDEO_RPC_ToSystem_VideoHaltDone_0_svc();
#define VIDEO_RPC_ToSystem_VideoAssistant 13
extern  RPCRES_LONG * VIDEO_RPC_ToSystem_VideoAssistant_0();
extern  RPCRES_LONG * VIDEO_RPC_ToSystem_VideoAssistant_0_svc();
#define VIDEO_RPC_ToSystem_DecoderMessage 15
extern  HRESULT * VIDEO_RPC_ToSystem_DecoderMessage_0();
extern  HRESULT * VIDEO_RPC_ToSystem_DecoderMessage_0_svc();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_VIDEO_RPC_ENDOFSTREAM (XDR *, VIDEO_RPC_ENDOFSTREAM*);
extern  bool_t xdr_VIDEO_RPC_DEC_JPEG_INFO (XDR *, VIDEO_RPC_DEC_JPEG_INFO*);
extern  bool_t xdr_VIDEO_RPC_VideoAssistant (XDR *, VIDEO_RPC_VideoAssistant*);
extern  bool_t xdr_VIDEO_RPC_DEC_JPEG_CTRL (XDR *, VIDEO_RPC_DEC_JPEG_CTRL*);
extern  bool_t xdr_VIDEO_RPC_DEC_ERROR_INFO (XDR *, VIDEO_RPC_DEC_ERROR_INFO*);
extern  bool_t xdr_VIDEO_RPC_ENC_AUTOPAUSE (XDR *, VIDEO_RPC_ENC_AUTOPAUSE*);
extern  bool_t xdr_VIDEO_RPC_FLASH_FRAME_INFO (XDR *, VIDEO_RPC_FLASH_FRAME_INFO*);
extern  bool_t xdr_VIDEO_RPC_DEC_MESSAGE (XDR *, VIDEO_RPC_DEC_MESSAGE*);
extern  bool_t xdr_VIDEO_RPC_TRANSITION_EFFECT_CTRL (XDR *, VIDEO_RPC_TRANSITION_EFFECT_CTRL*);

#else /* K&R C */
extern bool_t xdr_VIDEO_RPC_ENDOFSTREAM ();
extern bool_t xdr_VIDEO_RPC_DEC_JPEG_INFO ();
extern bool_t xdr_VIDEO_RPC_VideoAssistant ();
extern bool_t xdr_VIDEO_RPC_DEC_JPEG_CTRL ();
extern bool_t xdr_VIDEO_RPC_DEC_ERROR_INFO ();
extern bool_t xdr_VIDEO_RPC_ENC_AUTOPAUSE ();
extern bool_t xdr_VIDEO_RPC_FLASH_FRAME_INFO ();
extern bool_t xdr_VIDEO_RPC_DEC_MESSAGE ();
extern bool_t xdr_VIDEO_RPC_TRANSITION_EFFECT_CTRL ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VIDEORPC_AGENT_H_RPCGEN */
