/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VIDEORPC_AGENT_DATA_H_RPCGEN
#define _VIDEORPC_AGENT_DATA_H_RPCGEN

#include <RPCBaseDS.h>
#include <VideoRPCBaseDS.h>

struct VIDEO_RPC_ENDOFSTREAM {
	long SP_instanceID;
};
typedef struct VIDEO_RPC_ENDOFSTREAM VIDEO_RPC_ENDOFSTREAM;

struct VIDEO_RPC_DEC_JPEG_INFO {
	long instanceID;
	long destWidth;
	long destHeight;
	long eventID;
	long reserved2;
	long reserved3;
};
typedef struct VIDEO_RPC_DEC_JPEG_INFO VIDEO_RPC_DEC_JPEG_INFO;

struct VIDEO_RPC_VideoAssistant {
	long instanceID;
	VIDEO_ASSISTANT_ACTION action;
	VIDEO_ASSISTANT_TYPE assistantType;
	long reserved;
};
typedef struct VIDEO_RPC_VideoAssistant VIDEO_RPC_VideoAssistant;

struct VIDEO_RPC_DEC_JPEG_CTRL {
	long decodedWidth;
	long decodedHeight;
	long bitstreamEnd;
	long cancel;
	long status;
	long orgJpegWidth;
	long orgJpegHeight;
	long croppedJpegX;
	long croppedJpegY;
	long croppedJpegWidth;
	long croppedJpegHeight;
	enum VIDEO_JPEG_ROTATION orientation;
	long percentage;
	long reserved3;
	long JPEG_CTRL;
	long BITMAP_CTRL;
	long TIFF_CTRL;
	long GIF_CTRL;
	long PNG_CTRL;
	long Format1_CTRL;
	long Format2_CTRL;
	long Format3_CTRL;
	long bitstreamStart;
	long outInstanceID;
	enum VIDEO_IMG_TYPE imgType;
	long pScratchBase;
	long scratchSize;
};
typedef struct VIDEO_RPC_DEC_JPEG_CTRL VIDEO_RPC_DEC_JPEG_CTRL;

struct VIDEO_RPC_DEC_ERROR_INFO {
	long instanceID;
	long errCode;
};
typedef struct VIDEO_RPC_DEC_ERROR_INFO VIDEO_RPC_DEC_ERROR_INFO;

struct VIDEO_RPC_ENC_AUTOPAUSE {
	long instanceID;
	u_char isFinish;
};
typedef struct VIDEO_RPC_ENC_AUTOPAUSE VIDEO_RPC_ENC_AUTOPAUSE;

struct VIDEO_RPC_FLASH_FRAME_INFO {
	short LuBufID;
	short ChBufID;
	u_int pic_width;
	u_int pic_height;
	int Lu_width_scale;
	int Lu_init_page;
	int Lu_x_offset;
	int Lu_y_offset;
	int Ch_width_scale;
	int Ch_init_page;
	int Ch_x_offset;
	int Ch_y_offset;
	u_int context;
	u_int PTShigh;
	u_int PTSlow;
	u_int reserved0;
	u_int reserved1;
};
typedef struct VIDEO_RPC_FLASH_FRAME_INFO VIDEO_RPC_FLASH_FRAME_INFO;

struct VIDEO_RPC_DEC_MESSAGE {
	long instanceID;
	long message;
};
typedef struct VIDEO_RPC_DEC_MESSAGE VIDEO_RPC_DEC_MESSAGE;

struct VIDEO_RPC_TRANSITION_EFFECT_CTRL {
	long cancel;
	long percentage;
	VO_RECTANGLE winStart_A;
	VO_RECTANGLE winEnd_A;
	VO_RECTANGLE winStart_B;
	VO_RECTANGLE winEnd_B;
	long timeForKenBurns;
};
typedef struct VIDEO_RPC_TRANSITION_EFFECT_CTRL VIDEO_RPC_TRANSITION_EFFECT_CTRL;

#endif /* !_VIDEORPC_AGENT_DATA_H_RPCGEN */
