#ifndef ASF_DRM_TYPE_H
#define ASF_DRM_TYPE_H

#ifdef SUPPORT_WMDRM_PD 

	typedef DRM_MANAGER_CONTEXT			ASF_DRM_MANAGER_T;
	typedef DRM_MANAGER_DECRYPT_CONTEXT	ASF_DRM_DECRYPT_CONTEXT_T;
#else
	typedef DRM_APP_CONTEXT				ASF_DRM_MANAGER_T;
	typedef DRM_DECRYPT_CONTEXT			ASF_DRM_DECRYPT_CONTEXT_T;
#endif

#endif	 //ASF_DRM_TYPE_H