#!/bin/sh

/etc/init.d/netatalk enabled && {
	/etc/init.d/netatalk stop
	/etc/init.d/netatalk disable
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.netatalk
	set ucitrack.netatalk=netatalk
	set ucitrack.netatalk.init=netatalk
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
