LOCAL_PATH := $(my-dir)
##############################
include $(CLEAR_VARS)

LOCAL_MODULE := SampleTvInput
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_CERTIFICATE := platform

#LOCAL_MODULE_TARGET_ARCH := arm
#LOCAL_BUILT_MODULE_STEM := package.apk
#LOCAL_PRIVILEGED_MODULE := true

include $(BUILD_PREBUILT)
