#ifndef __FILTERS_CONFIG_H__
#define __FILTERS_CONFIG_H__

/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */


/* enable warnings about being development release */
#define _DEVELOPMENT_ 

/* enable GNU libc extension */
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif


/* Define as `__inline' if that's what the C compiler calls it, or to nothing
   if it is not supported. */
#define inline __inline


#endif // __FILTERS_CONFIG_H__
