#ifndef VIDEO_MIXER_WINDOW_ID_DEFINE_H
#define VIDEO_MIXER_WINDOW_ID_DEFINE_H

#define VIDEO_MIXER_WINDOW_ID_OF_CAMERA_IN 	0
#define VIDEO_MIXER_WINDOW_ID_OF_REMOTE_1 	1
#define VIDEO_MIXER_WINDOW_ID_OF_REMOTE_2 	2
#define VIDEO_MIXER_WINDOW_ID_OF_REMOTE_3 	3
#define VIDEO_MIXER_WINDOW_ID_OF_REMOTE_4 	4
#define VIDEO_MIXER_WINDOW_ID_OF_REMOTE_5 	5
#define VIDEO_MIXER_WINDOW_ID_OF_REMOTE_6 	6
#define VIDEO_MIXER_WINDOW_ID_OF_REMOTE_7 	7

#endif
