/*
 * Copyright (C) 2017 Realtek Semiconductor Corporation.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

	.file	1 "filter_v2.c"
	.section .mdebug.abi32
	.previous
	.gnu_attribute 4, 3
	.ident	"GCC: (Realtek MSDK-4.4.7 Build 2001) 4.4.7"
