LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

CAL_SRC_FILES := power.kylin.so
LOCAL_MODULE_TAGS:= optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/hw
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE := power

include $(BUILD_PREBUILT)


