#ifndef __VIDEORPC_MAKEUP_H__
#define __VIDEORPC_MAKEUP_H__

#include "video_filter_pin_def.h"
// copy from Mars::VideoRPCBaseDS_data.h
enum ENUM_TVD_INPUT_FORMAT {
	TVD_INFMT_CVBS0_TUNER = 0,
	TVD_INFMT_CVBS1 = 0 + 1,
	TVD_INFMT_CVBS2 = 0 + 2,
	TVD_INFMT_SVIDEO0 = 0 + 3,
	TVD_INFMT_SVIDEO1 = 0 + 4,
	TVD_INFMT_YPbPr0 = 0 + 5,
	TVD_INFMT_YPbPr1 = 0 + 6,
	TVD_INFMT_SCART = 0 + 7,
	TVD_INFMT_YPbPrM = 0 + 8,
	TVD_INFMT_SCART_CVBS = 0 + 9,
	TVD_INFMT_SCART_RGB = 0 + 10,
};
typedef enum ENUM_TVD_INPUT_FORMAT ENUM_TVD_INPUT_FORMAT;

// copy from Mars::VideoRPCBaseDS_data.h
enum ENUM_TVD_VIDEO_FORMAT {
	TVD_VIDEO_AUTO_DETECT = 0x00,
	TVD_VIDEO_ZNTSC = 0x01,
	TVD_VIDEO_ZNTSC_443 = 0x02,
	TVD_VIDEO_ZPAL_I = 0x03,
	TVD_VIDEO_ZPAL_M = 0x04,
	TVD_VIDEO_ZPAL_CN = 0x05,
	TVD_VIDEO_ZSECAM = 0x06,
	TVD_VIDEO_480P = 0x06 + 1,
	TVD_VIDEO_576P = 0x06 + 2,
	TVD_VIDEO_720P50 = 0x06 + 3,
	TVD_VIDEO_720P60 = 0x06 + 4,
	TVD_VIDEO_1080I50 = 0x06 + 5,
	TVD_VIDEO_1080I60 = 0x06 + 6,
	TVD_VIDEO_1080P50 = 0x06 + 7,
	TVD_VIDEO_1080P60 = 0x06 + 8,
};
typedef enum ENUM_TVD_VIDEO_FORMAT ENUM_TVD_VIDEO_FORMAT;

// copy from Mars::VideoRPCBaseDS_data.h
//enum VIDEO_RATE_CONTROL_MODE {
//	VIDEO_RATE_CBR = 0,
//	VIDEO_RATE_CBG = 1,
//	VIDEO_RATE_VBR = 2,
//	VIDEO_RATE_CVBR = 3,
//	VIDEO_RATE_NVBR = 4,
//};
//typedef enum VIDEO_RATE_CONTROL_MODE VIDEO_RATE_CONTROL_MODE;

// copy from Mars::VideoRPCBaseDS_data.h
enum ENUM_VIDEO_ENCODER_RC_MODE {
	VIDEOENCODER_CBR = 0,
	VIDEOENCODER_VBR = 1,
	VIDEOENCODER_CVBR = 2,
	VIDEOENCODER_TotalRCMode = 3,
};
typedef enum ENUM_VIDEO_ENCODER_RC_MODE ENUM_VIDEO_ENCODER_RC_MODE;

#endif /*__VIDEORPC_MAKEUP_H__*/
