#ifndef SETTING_H
#define SETTING_H

#include "libcgi.h"
#include "Application/AppClass/setupdef.h"

enum {
	SETTING_OSD_LANGUAGE,
	SETTING_UNKNOWN,
};

// Language Code Table
static const PARAMETER_TABLE ISO_639_language_3bytes_code_table[] = 
{
	INSERT_PARAM("en", OSD_LANG_ENGLISH),
	INSERT_PARAM("zh", OSD_LANG_CHINESE), 
	INSERT_PARAM("ja", OSD_LANG_JAPANESE),
	INSERT_PARAM("es", OSD_LANG_SPANISH),
	INSERT_PARAM("fr", OSD_LANG_FRENCH),  
	INSERT_PARAM("de", OSD_LANG_GERMAN),  
	INSERT_PARAM("it", OSD_LANG_ITALIAN), 
	INSERT_PARAM("ko", OSD_LANG_KOREAN), 
	INSERT_PARAM("nl", OSD_LANG_DUTCH),
	INSERT_PARAM("ru", OSD_LANG_RUSSIAN),
	INSERT_PARAM("ch", OSD_LANG_SCHINESE),			
	INSERT_PARAM("th", OSD_LANG_THAI),	  
	INSERT_PARAM("iw", OSD_LANG_HEBREW), 
	INSERT_PARAM("he", OSD_LANG_HEBREW), 
	INSERT_PARAM("ar", OSD_LANG_ARABIC),	
	INSERT_PARAM("pt", OSD_LANG_PORTUGUESE), 
	INSERT_PARAM("su", OSD_LANG_SUDANESE),
	INSERT_PARAM("sv", OSD_LANG_SWEDISH),
	INSERT_PARAM("fi", OSD_LANG_FINNISH),
	INSERT_PARAM("pl", OSD_LANG_POLISH),
	INSERT_PARAM("tr", OSD_LANG_TURKMEN),
	INSERT_PARAM("da", OSD_LANG_DANISH),
	INSERT_PARAM("el", OSD_LANG_GRECCE),
	INSERT_PARAM("cs", OSD_LANG_CZECH),
	INSERT_PARAM("sl", OSD_LANG_SLOVAK), 
	INSERT_PARAM("hu", OSD_LANG_HUNGARIAN),  	
	INSERT_PARAM("ro", OSD_LANG_ROMANIA),
	INSERT_PARAM("uk", OSD_LANG_UKRAINE),
	INSERT_PARAM("no", OSD_LANG_NORWEGIAN),
	INSERT_PARAM("hi", OSD_LANG_HINDI),
};

static const PARAMETER_TABLE tbl_SettingSet[] = {
	INSERT_PARAM("osd_language", SETTING_OSD_LANGUAGE),

};


int handleGetSetSettingItem(void);

#endif // SETTING_H
