#ifndef WIFI_H
#define WIFI_H

#include "libcgi.h"

#define WIFI_CHECK_SETUP_NECESSARY_CMD_STR  "wifi_connect_needed"
#define WIFI_QUERY_STATUS_CMD_STR			"query_status"
#define WIFI_ENABLE_CMD_STR					"enable"
#define WIFI_DISABLE_CMD_STR				"disable"
#define WIFI_SEARCH_AP_LIST_CMD_STR			"search_ap_list"
#define WIFI_CONNECT_CMD_STR				"connect"
#define WIFI_DISCONNECT_CMD_STR				"disconnect"
#define WIFI_REMOVE_CMD_STR					"remove"
#define WIFI_QUERY_CONNECT_INFO_CMD_STR		"query_connect_info"

#define WIFI_CGI_SSID_TAG					"ssid"
#define WIFI_CGI_PASSWD_TAG					"passwd"
#define WIFI_CGI_SECURITY_TAG               "security"
#define WIFI_CGI_NETID_TAG					"netid"

enum 
{
    WIFI_CHECK_SETUP_NECESSARY, // wifi setup is needed or not: true / false
	WIFI_QUERY_STATUS,	// device status : true / false
	WIFI_ENABLE,
	WIFI_DISABLE,
	WIFI_SEARCH_AP_LIST,
	WIFI_CONNECT,
	WIFI_DISCONNECT,
	WIFI_REMOVE,
	WIFI_QUERY_CONNECT_INFO,
	WIFI_CMD_NUM
};

static const PARAMETER_TABLE tbl_WifiCommandSet[] = {
    INSERT_PARAM(WIFI_CHECK_SETUP_NECESSARY_CMD_STR, WIFI_CHECK_SETUP_NECESSARY),
	INSERT_PARAM(WIFI_QUERY_STATUS_CMD_STR, 	WIFI_QUERY_STATUS),
	INSERT_PARAM(WIFI_ENABLE_CMD_STR, 			WIFI_ENABLE),
	INSERT_PARAM(WIFI_DISABLE_CMD_STR,			WIFI_DISABLE),
	INSERT_PARAM(WIFI_SEARCH_AP_LIST_CMD_STR, 	WIFI_SEARCH_AP_LIST),
	INSERT_PARAM(WIFI_CONNECT_CMD_STR, 			WIFI_CONNECT),
	INSERT_PARAM(WIFI_DISCONNECT_CMD_STR, 		WIFI_DISCONNECT),
	INSERT_PARAM(WIFI_REMOVE_CMD_STR, 			WIFI_REMOVE),
	INSERT_PARAM(WIFI_QUERY_CONNECT_INFO_CMD_STR, WIFI_QUERY_CONNECT_INFO),
};

int handleWifi(void);

#endif
