obj-$(CONFIG_POWER_CONTROL)         += power_control_core.o  
obj-$(CONFIG_POWER_CONTROL_DEBUGFS) += power_control_debugfs.o
obj-$(CONFIG_POWER_CONTROL_RTD129x) += pwrctrl-rtk-drv.o pwrctrl-rtk.o pwrctrl-rtk-timer.o

