/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DEBUG_LEVEL_DATA_H_RPCGEN
#define _DEBUG_LEVEL_DATA_H_RPCGEN

#include <RPCstruct.h>

#endif /* !_DEBUG_LEVEL_DATA_H_RPCGEN */
