/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DEBUG_LEVEL_H_RPCGEN
#define _DEBUG_LEVEL_H_RPCGEN

#include <RPCstruct.h>

#include "debug_level_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCstruct.h>

#define D_PROGRAM 97
#define D_VERSION 0

struct REG_STRUCT * D_PROGRAM_0_register(struct REG_STRUCT *rnode);

#if defined(__STDC__) || defined(__cplusplus)
#define set_debug_flag 1
extern  int * set_debug_flag_0(int *, CLNT_STRUCT *);
extern  int * set_debug_flag_0_svc(int *, RPC_STRUCT *, int *);

#else /* K&R C */
#define set_debug_flag 1
extern  int * set_debug_flag_0();
extern  int * set_debug_flag_0_svc();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DEBUG_LEVEL_H_RPCGEN */
