ifeq ($(USE_RTK_HDMI_CONTROL), YES)

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

ifeq ($(USE_RTK_HDCP1x_CONTROL), YES)
LOCAL_SRC_FILES := libRTKHDMIControl.so_HDCP 
else
LOCAL_SRC_FILES := libRTKHDMIControl.so
endif

LOCAL_MODULE_TAGS:= optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE := libRTKHDMIControl

include $(BUILD_PREBUILT)

endif # USE_RTK_HDMI_CONTROL
