LOCAL_DIR := $(GET_LOCAL_DIR)

MODULE := $(LOCAL_DIR)

MODULE_DEPS += \
	lib/sysparam \
	external/lib/factory \
	external/lib/gpt

MODULE_SRCS += \
	$(LOCAL_DIR)/rtkboot.c \
	$(LOCAL_DIR)/boot_kernel.c \
	$(LOCAL_DIR)/acpu.c \
	$(LOCAL_DIR)/firmware.c \
	$(LOCAL_DIR)/parse_h.c \
	$(LOCAL_DIR)/power.c

GLOBAL_DEFINES += \
	KERNEL_LOADADDR=$(KERNEL_LOADADDR) \
	FDT_LOADADDR=$(FDT_LOADADDR) \
	ROOTFS_LOADADDR=$(ROOTFS_LOADADDR) \
	AUDIO_LOADADDR=$(AUDIO_LOADADDR)

ifeq ($(ANDROID_REBOOT_CMD),1)
GLOBAL_DEFINES += ANDROID_REBOOT_CMD
endif #ANDROID_REBOOT_CMD

ifeq ($(FORCE_BOOT_FROM_USB),1)
GLOBAL_DEFINES += FORCE_BOOT_FROM_USB
endif #FORCE_BOOT_FROM_USB

ifeq ($(SUPPORT_BOOT_RU_CMD),1)
GLOBAL_DEFINES += SUPPORT_BOOT_RU_CMD
endif #SUPPORT_BOOT_RU_CMD

ifeq ($(NAS_ENABLE),1)
GLOBAL_DEFINES += NAS_ENABLE
endif #NAS_ENABLE

ifeq ($(NAS_DUAL),1)
GLOBAL_DEFINES += NAS_DUAL
endif #NAS_DUAL

ifeq ($(LK_FW_LOAD),1)
GLOBAL_DEFINES += LK_FW_LOAD=1
else
GLOBAL_DEFINES += LK_FW_LOAD=0
endif #LK_FW_LOAD

ifeq ($(FW_TABLE_SIGN),1)
GLOBAL_DEFINES += FW_TABLE_SIGN
endif #FW_TABLE_SIGN
include make/module.mk
