#!/bin/sh

/etc/init.d/forked-daapd enabled && {
	/etc/init.d/forked-daapd stop
	/etc/init.d/forked-daapd disable
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.forked-daapd
	set ucitrack.forked-daapd=forked-daapd
	set ucitrack.forked-daapd.init=forked-daapd
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
