/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VIDEORPC_AGENT_H_RPCGEN
#define _VIDEORPC_AGENT_H_RPCGEN

#include <../../../include/RPCstruct.h>

#include "VideoRPC_Agent_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCBaseDS.h>
#include <VideoRPCBaseDS.h>
#include <AudioRPCBaseDS.h>
#include <AudioRPC_Agent.h>

#define VIDEO_AGENT 300
#define VERSION 0

struct REG_STRUCT * VIDEO_AGENT_0_register(struct REG_STRUCT *rnode);

#if defined(__STDC__) || defined(__cplusplus)
#define VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg 5
extern  HRESULT * VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0(VIDEO_RPC_DEC_JPEG_INFO *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0_svc(VIDEO_RPC_DEC_JPEG_INFO *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_DEC_ToSystem_FatalError 63
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_FatalError_0(VIDEO_RPC_DEC_ERROR_INFO *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_FatalError_0_svc(VIDEO_RPC_DEC_ERROR_INFO *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToSystem_VideoHaltDone 65
extern  HRESULT * VIDEO_RPC_ToSystem_VideoHaltDone_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToSystem_VideoHaltDone_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToSystem_DecoderMessage 67
extern  HRESULT * VIDEO_RPC_ToSystem_DecoderMessage_0(VIDEO_RPC_DEC_MESSAGE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToSystem_DecoderMessage_0_svc(VIDEO_RPC_DEC_MESSAGE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_DEC_ToSystem_Deliver_FrameInfo 1018
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_Deliver_FrameInfo_0(VIDEO_RPC_DEC_FRAME_INFO *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_Deliver_FrameInfo_0_svc(VIDEO_RPC_DEC_FRAME_INFO *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_DEC_ToSystem_Deliver_PicInfo 1019
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_Deliver_PicInfo_0(VIDEO_RPC_DEC_PIC_INFO *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_Deliver_PicInfo_0_svc(VIDEO_RPC_DEC_PIC_INFO *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_DEC_ToSystem_Deliver_MediaInfo 1020
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_Deliver_MediaInfo_0(VIDEO_RPC_DEC_MEDIA_INFO *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_Deliver_MediaInfo_0_svc(VIDEO_RPC_DEC_MEDIA_INFO *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToSystem_VoutMessage 1021
extern  HRESULT * VIDEO_RPC_ToSystem_VoutMessage_0(VIDEO_RPC_VOUT_MESSAGE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToSystem_VoutMessage_0_svc(VIDEO_RPC_VOUT_MESSAGE *, RPC_STRUCT *, HRESULT *);

#else /* K&R C */
#define VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg 5
extern  HRESULT * VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0();
extern  HRESULT * VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0_svc();
#define VIDEO_RPC_DEC_ToSystem_FatalError 63
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_FatalError_0();
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_FatalError_0_svc();
#define VIDEO_RPC_ToSystem_VideoHaltDone 65
extern  HRESULT * VIDEO_RPC_ToSystem_VideoHaltDone_0();
extern  HRESULT * VIDEO_RPC_ToSystem_VideoHaltDone_0_svc();
#define VIDEO_RPC_ToSystem_DecoderMessage 67
extern  HRESULT * VIDEO_RPC_ToSystem_DecoderMessage_0();
extern  HRESULT * VIDEO_RPC_ToSystem_DecoderMessage_0_svc();
#define VIDEO_RPC_DEC_ToSystem_Deliver_FrameInfo 1018
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_Deliver_FrameInfo_0();
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_Deliver_FrameInfo_0_svc();
#define VIDEO_RPC_DEC_ToSystem_Deliver_PicInfo 1019
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_Deliver_PicInfo_0();
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_Deliver_PicInfo_0_svc();
#define VIDEO_RPC_DEC_ToSystem_Deliver_MediaInfo 1020
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_Deliver_MediaInfo_0();
extern  HRESULT * VIDEO_RPC_DEC_ToSystem_Deliver_MediaInfo_0_svc();
#define VIDEO_RPC_ToSystem_VoutMessage 1021
extern  HRESULT * VIDEO_RPC_ToSystem_VoutMessage_0();
extern  HRESULT * VIDEO_RPC_ToSystem_VoutMessage_0_svc();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_VIDEO_DEC_FRM_MSG (XDR *, VIDEO_DEC_FRM_MSG*);
extern  bool_t xdr_VIDEO_DEC_PIC_MSG (XDR *, VIDEO_DEC_PIC_MSG*);
extern  bool_t xdr_VIDEO_RPC_VOUT_MESSAGE (XDR *, VIDEO_RPC_VOUT_MESSAGE*);
extern  bool_t xdr_VIDEO_RPC_DEC_FRAME_INFO (XDR *, VIDEO_RPC_DEC_FRAME_INFO*);
extern  bool_t xdr_VIDEO_RPC_DEC_PIC_INFO (XDR *, VIDEO_RPC_DEC_PIC_INFO*);
extern  bool_t xdr_VIDEO_RPC_DEC_MEDIA_INFO (XDR *, VIDEO_RPC_DEC_MEDIA_INFO*);
extern  bool_t xdr_VIDEO_RPC_TO_KERNEL_PARAMETER (XDR *, VIDEO_RPC_TO_KERNEL_PARAMETER*);
extern  bool_t xdr_VIDEO_RPC_TRANSITION_EFFECT_CTRL (XDR *, VIDEO_RPC_TRANSITION_EFFECT_CTRL*);

#else /* K&R C */
extern bool_t xdr_VIDEO_DEC_FRM_MSG ();
extern bool_t xdr_VIDEO_DEC_PIC_MSG ();
extern bool_t xdr_VIDEO_RPC_VOUT_MESSAGE ();
extern bool_t xdr_VIDEO_RPC_DEC_FRAME_INFO ();
extern bool_t xdr_VIDEO_RPC_DEC_PIC_INFO ();
extern bool_t xdr_VIDEO_RPC_DEC_MEDIA_INFO ();
extern bool_t xdr_VIDEO_RPC_TO_KERNEL_PARAMETER ();
extern bool_t xdr_VIDEO_RPC_TRANSITION_EFFECT_CTRL ();

#endif /* K&R C */


////////////////  CallBack
//extern HRESULT* (*g_VIDEO_RPC_ENC_ToSystem_EndOfStream_0_svc)(long *instanceID, RPC_STRUCT *rpc, HRESULT *retval);
extern HRESULT* (*g_VIDEO_RPC_ToSystem_EndOfStream_0_svc)(VIDEO_RPC_ENDOFSTREAM* pInfo, RPC_STRUCT *rpc, HRESULT *retval);
//extern HRESULT* (*g_VIDEO_RPC_ToSystem_Deliver_GenInfo_0_svc)(long *instanceID, RPC_STRUCT *rpc, HRESULT *retval);
extern HRESULT* (*g_VIDEO_RPC_ToSystem_Deliver_FrameInfo_0_svc)(long *instanceID, RPC_STRUCT *rpc, HRESULT *retval);
//extern HRESULT* (*g_VIDEO_RPC_ToSystem_Deliver_PauseInfo_0_svc)(long *instanceID, RPC_STRUCT *rpc, HRESULT *retval);
//extern HRESULT* (*g_VIDEO_RPC_ToSystem_Deliver_WSSInfo_0_svc)(long *instanceID, RPC_STRUCT *rpc, HRESULT *retval);
//extern HRESULT* (*g_VIDEO_RPC_ToSystem_Deliver_AutoPauseInfo_0_svc)(VIDEO_RPC_ENC_AUTOPAUSE *info, RPC_STRUCT *rpc, HRESULT *retval);
extern HRESULT* (*g_VIDEO_RPC_ToSystem_DecoderMessage_0_svc)(VIDEO_RPC_DEC_MESSAGE *pInfo, RPC_STRUCT *rpc, HRESULT *retval);
extern HRESULT* (*g_VIDEO_RPC_JPEG_ToSystem_EndOfDecSeg_0_svc)(VIDEO_RPC_DEC_JPEG_INFO* pInfo, RPC_STRUCT *rpc, HRESULT *retval);
extern HRESULT* (*g_VIDEO_RPC_ToSystem_VoutMessage_0_svc)(VIDEO_RPC_VOUT_MESSAGE* pInfo, RPC_STRUCT *rpc, HRESULT *retval);
extern HRESULT* (*g_VIDEO_RPC_DEC_ToSystem_FatalError_0_svc)(VIDEO_RPC_DEC_ERROR_INFO *pInfo, RPC_STRUCT *rpc, HRESULT *retval);
extern HRESULT* (*g_VIDEO_RPC_ToSystem_ScaleModeSCART_0_svc)(long *WideScreen, RPC_STRUCT *rpc, HRESULT *retval);
extern HRESULT* (*g_VIDEO_RPC_ToSystem_VideoHaltDone_0_svc)(long *reserved, RPC_STRUCT *rpc, HRESULT *retval);
//extern HRESULT* (*g_VIDEO_RPC_ToSystem_SendScalerMsg_0_svc)(VIDEO_RPC_SCALER_MESSAGE *a_ptScalerMsg, RPC_STRUCT *rpc, HRESULT *result);
//extern HRESULT* (*g_VIDEO_RPC_ToSystem_KernelRPC_0_svc)(VIDEO_RPC_TO_KERNEL_PARAMETER *pInfo, RPC_STRUCT *rpc, HRESULT *result);
extern HRESULT* (*g_VIDEO_RPC_DEC_ToSystem_Deliver_FrameInfo_0_svc)(VIDEO_RPC_DEC_FRAME_INFO *pInfo, RPC_STRUCT *rpc, HRESULT *result);
extern HRESULT* (*g_VIDEO_RPC_DEC_ToSystem_Deliver_PicInfo_0_svc)(VIDEO_RPC_DEC_PIC_INFO *pInfo, RPC_STRUCT *rpc, HRESULT *result);
extern HRESULT* (*g_VIDEO_RPC_DEC_ToSystem_Deliver_MediaInfo_0_svc)(VIDEO_RPC_DEC_MEDIA_INFO *pInfo, RPC_STRUCT *rpc, HRESULT *result);


////////////////  CallBack
typedef HRESULT* (*PFN_VIDEO_RPC_ToSystem_VoutMessage_0_svc) (VIDEO_RPC_VOUT_MESSAGE* pInfo, RPC_STRUCT *rpc, HRESULT *retval);
typedef HRESULT* (*PFN_VIDEO_RPC_DEC_ToSystem_Deliver_FrameInfo_0_svc) (VIDEO_RPC_DEC_FRAME_INFO *pInfo, RPC_STRUCT *rpc, HRESULT *result);
typedef HRESULT* (*PFN_VIDEO_RPC_DEC_ToSystem_Deliver_PicInfo_0_svc) (VIDEO_RPC_DEC_PIC_INFO *pInfo, RPC_STRUCT *rpc, HRESULT *result);
typedef HRESULT* (*PFN_VIDEO_RPC_DEC_ToSystem_Deliver_MediaInfo_0_svc) (VIDEO_RPC_DEC_MEDIA_INFO *pInfo, RPC_STRUCT *rpc, HRESULT *result);
typedef HRESULT* (*PFN_VIDEO_RPC_DEC_ToSystem_DecoderMessage_0_svc) (VIDEO_RPC_DEC_MESSAGE *pInfo, RPC_STRUCT *rpc, HRESULT *result);
typedef HRESULT* (*PFN_VIDEO_RPC_DEC_ToSystem_FatalError_0_svc) (VIDEO_RPC_DEC_ERROR_INFO *pInfo, RPC_STRUCT *rpc, HRESULT *result);

void rhal_RegisterVoutMessageCallback(PFN_VIDEO_RPC_ToSystem_VoutMessage_0_svc pfnVoutMessageCallback);
void rhal_RegisterDecFrameInfoCallback(PFN_VIDEO_RPC_DEC_ToSystem_Deliver_FrameInfo_0_svc pfnDecFrameInfoCallback);
void rhal_RegisterDecPicInfoCallback(PFN_VIDEO_RPC_DEC_ToSystem_Deliver_PicInfo_0_svc pfnDecPicInfoCallback);
void rhal_RegisterDecMediaInfoCallback(PFN_VIDEO_RPC_DEC_ToSystem_Deliver_MediaInfo_0_svc pfnDecMediaInfoCallback);
void rhal_RegisterDecoderMessageCallback(PFN_VIDEO_RPC_DEC_ToSystem_DecoderMessage_0_svc pfnDecoderMessageCallback);
void rhal_RegisterDecFatalErrorCallback(PFN_VIDEO_RPC_DEC_ToSystem_FatalError_0_svc pfnDecoderFatalErrorCallback);
void rhal_UnRegisterVoutMessageCallback();
void rhal_UnRegisterDecFrameInfoCallback();
void rhal_UnRegisterDecPicInfoCallback();
void rhal_UnRegisterDecMediaInfoCallback();
void rhal_UnRegisterDecoderMessageCallback();
void rhal_UnRegisterDecFatalErrorCallback();


#ifdef __cplusplus
}
#endif

#endif /* !_VIDEORPC_AGENT_H_RPCGEN */
