/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VIDEORPCBASEDS_H_RPCGEN
#define _VIDEORPCBASEDS_H_RPCGEN

#include <../../../include/RPCstruct.h>

#include "VideoRPCBaseDS_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <rpc_common.h>
#include <AudioRPCBaseDS.h>
#include <AudioRPC_Agent.h>
#include <AudioRPC_System.h>

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_VIDEO_RESOURCE_CORE_TYPE (XDR *, VIDEO_RESOURCE_CORE_TYPE*);
extern  bool_t xdr_VIDEO_RESOURCE_CTRL_TYPE (XDR *, VIDEO_RESOURCE_CTRL_TYPE*);
extern  bool_t xdr_CMPRS_RATIO (XDR *, CMPRS_RATIO*);
extern  bool_t xdr_HDR_TYPE (XDR *, HDR_TYPE*);
extern  bool_t xdr_ENUM_VIDEO_MSG_INFO_TYPE (XDR *, ENUM_VIDEO_MSG_INFO_TYPE*);

#else /* K&R C */
extern bool_t xdr_VIDEO_RESOURCE_CORE_TYPE ();
extern bool_t xdr_VIDEO_RESOURCE_CTRL_TYPE ();
extern bool_t xdr_CMPRS_RATIO ();
extern bool_t xdr_HDR_TYPE ();
extern bool_t xdr_ENUM_VIDEO_MSG_INFO_TYPE ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VIDEORPCBASEDS_H_RPCGEN */
