/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VIDEORPC_SYSTEM_DATA_H_RPCGEN
#define _VIDEORPC_SYSTEM_DATA_H_RPCGEN

#include <RPCBaseDS.h>
#include <VideoRPCBaseDS.h>
#include <AudioRPCBaseDS.h>
#include <AudioRPC_System.h>

struct VIDEO_RPC_DEC_SET_SPEED {
	u_int instanceID;
	u_int displaySpeed;
	u_int decodeSkip;
};
typedef struct VIDEO_RPC_DEC_SET_SPEED VIDEO_RPC_DEC_SET_SPEED;

struct VIDEO_RPC_DEC_SET_ERR_CONCEALMENT_LEVEL {
	u_int instanceID;
	u_int errConcealmentLevel;
	u_int errNotificationLevel;
	u_int continuousFrmCntForNotification;
	u_int bIsVideoSlowForErrBlk;
};
typedef struct VIDEO_RPC_DEC_SET_ERR_CONCEALMENT_LEVEL VIDEO_RPC_DEC_SET_ERR_CONCEALMENT_LEVEL;

struct VIDEO_RPC_DEC_INIT {
	u_int instanceID;
	VIDEO_STREAM_TYPE type;
	struct VIDEO_RPC_DEC_SET_SPEED set_speed;
};
typedef struct VIDEO_RPC_DEC_INIT VIDEO_RPC_DEC_INIT;

struct VIDEO_RPC_DEC_SET_DEBLOCK {
	u_int instanceID;
	u_char enable;
};
typedef struct VIDEO_RPC_DEC_SET_DEBLOCK VIDEO_RPC_DEC_SET_DEBLOCK;

struct VIDEO_RPC_DEC_BITSTREAM_BUFFER {
	u_int bsBase;
	u_int bsSize;
	enum VIDEO_VF_TYPE type;
};
typedef struct VIDEO_RPC_DEC_BITSTREAM_BUFFER VIDEO_RPC_DEC_BITSTREAM_BUFFER;

struct VIDEO_RPC_DEC_BV_RESULT {
	u_int bitRate;
	u_int type;
};
typedef struct VIDEO_RPC_DEC_BV_RESULT VIDEO_RPC_DEC_BV_RESULT;
struct VIDEO_RPC_DEC_PV_RESULT {
	u_int width;
	u_int height;
};
typedef struct VIDEO_RPC_DEC_PV_RESULT VIDEO_RPC_DEC_PV_RESULT;

struct VIDEO_RPC_DEC_SEQ_INFO {
	u_int hor_size;
	u_int ver_size;
	u_int aspect_ratio;
	u_int frame_rate;
	u_int bit_rate;
	u_int vbv_buf_size;
	u_int profile_level;
	u_int chroma_format;
	u_int video_format;
	u_int disp_hor_size;
	u_int disp_ver_size;
	u_int isProg;
	u_int isMVC;
	u_int isHDR;
	u_int isCompressBufferMode;
	u_int offsetTable_ysize;
	u_int offsetTable_csize;
};
typedef struct VIDEO_RPC_DEC_SEQ_INFO VIDEO_RPC_DEC_SEQ_INFO;

struct VIDEO_RPC_DEC_SEQ_INFO_NEW {
	u_int hor_size;
	u_int ver_size;
	u_int aspect_ratio;
	u_int frame_rate;
	u_int bit_rate;
	u_int vbv_buf_size;
	u_int profile_level;
	u_int chroma_format;
	u_int video_format;
	u_int disp_hor_size;
	u_int disp_ver_size;
	u_int isProg;
	u_int isMVC;
	u_int isHDR;
	u_int isCompressBufferMode;
	u_int offsetTable_ysize;
	u_int offsetTable_csize;
	u_int is4k2k_MVC;
	u_int isREALD;
	u_int prog_sequence;
	u_int pic_type;
	u_int temp_ref;
	u_int pic_struct;
	u_int top_ff;
	u_int rept_ff;
	u_char video_full_range_flag;
	u_char transfer_characteristics;
	u_char matrix_coefficiets;
	u_char colour_primaries;
	u_short display_primaries_x[3];
	u_short display_primaries_y[3];
	u_short white_point_x;
	u_short white_point_y;
	u_int min_display_mastering_luminance;
	u_int max_display_mastering_luminance;
	u_int MaxSpeed;
	u_char hdr_type;
};
typedef struct VIDEO_RPC_DEC_SEQ_INFO_NEW VIDEO_RPC_DEC_SEQ_INFO_NEW;
struct VIDEO_RPC_DEC_MPEG_SEQ_HDR {
	u_int instanceID;
	u_int C_prog_seq;
	u_int C_aspect_ratio;
	u_int C_intra_QM;
	u_int C_non_intra_QM;
	u_int H_hor_size;
	u_int H_ver_size;
	u_int H_disp_hor_size;
	u_int H_disp_ver_size;
	u_int H_frame_rate;
	u_int L_frame_PTSinc;
	u_int L_bit_rate;
	u_int C_Mpeg1;
	u_int active_format;
	u_int L_Num_Pics;
	u_short H_vop_time_increment_resolution;
	u_short H_size_vop_time_increment;
	u_char C_complexity_estimation_disable;
	u_char C_resync_marker_disable;
	u_char C_quant_type;
	u_char C_quarter_sample;
	char C_intra_QM_MPEG4;
	char C_non_intra_QM_MPEG4;
	u_int L_define_vop_comp_est_hdr;
	u_int saveBuf;
	u_char Seq_Intra_QM[64];
	u_char Seq_Non_Intra_QM[64];
};
typedef struct VIDEO_RPC_DEC_MPEG_SEQ_HDR VIDEO_RPC_DEC_MPEG_SEQ_HDR;
struct VIDEO_RPC_DEC_CC_BYPASS_MODE {
	u_int instanceID;
	enum VIDEO_DECODER_CC_BYPASS_MODE cc_mode;
};
typedef struct VIDEO_RPC_DEC_CC_BYPASS_MODE VIDEO_RPC_DEC_CC_BYPASS_MODE;

struct VIDEO_RPC_DEC_SET_DNR {
	u_int instanceID;
	enum VIDEO_DNR_MODE dnr_mode;
};
typedef struct VIDEO_RPC_DEC_SET_DNR VIDEO_RPC_DEC_SET_DNR;

struct VIDEO_RPC_DEC_SET_REF_SYNC_LIMIT {
	u_int instanceID;
	u_int refSyncLimit;
};
typedef struct VIDEO_RPC_DEC_SET_REF_SYNC_LIMIT VIDEO_RPC_DEC_SET_REF_SYNC_LIMIT;

struct VIDEO_RPC_DEC_CAPABILITY {
	u_int HighWord;
	u_int LowWord;
};
typedef struct VIDEO_RPC_DEC_CAPABILITY VIDEO_RPC_DEC_CAPABILITY;
struct VIDEO_RPC_DEC_CMPRS_CTRL {
	u_int instanceID;
	u_char mode;
	enum CMPRS_RATIO ratio;
	u_char enable;
};
typedef struct VIDEO_RPC_DEC_CMPRS_CTRL VIDEO_RPC_DEC_CMPRS_CTRL;

struct VIDEO_RPC_THUMBNAIL_SET_VSCALER_OUTFORMAT {
	u_int instanceID;
	u_int ThumbAckAddr;
	VIDEO_COLOR_FMT colorFormat;
	u_int pTargetLuma;
	u_int pTargetChroma;
	u_int pitch;
	u_int targetRectX;
	u_int targetRectY;
	u_int targetRectWidth;
	u_int targetRectHeight;
	u_int alpha;
	u_int fillColor;
};
typedef struct VIDEO_RPC_THUMBNAIL_SET_VSCALER_OUTFORMAT VIDEO_RPC_THUMBNAIL_SET_VSCALER_OUTFORMAT;

struct VIDEO_RPC_THUMBNAIL_SET_THRESHOLD {
	u_int instanceID;
	u_int threshold;
};
typedef struct VIDEO_RPC_THUMBNAIL_SET_THRESHOLD VIDEO_RPC_THUMBNAIL_SET_THRESHOLD;

struct VIDEO_RPC_FLASH_SET_OUTPUT {
	u_int instanceID;
	u_int address;
};
typedef struct VIDEO_RPC_FLASH_SET_OUTPUT VIDEO_RPC_FLASH_SET_OUTPUT;

struct VIDEO_RPC_THUMBNAIL_SET_STARTPIC {
	u_int instanceID;
	u_int startPicNum;
	u_int endPicNum;
};
typedef struct VIDEO_RPC_THUMBNAIL_SET_STARTPIC VIDEO_RPC_THUMBNAIL_SET_STARTPIC;

struct VIDEO_RPC_SUBPIC_DEC_CONFIGURE {
	u_int instanceID;
	u_short fullWidth;
	u_short fullHeight;
	enum SP_STREAM_TYPE streamType;
};
typedef struct VIDEO_RPC_SUBPIC_DEC_CONFIGURE VIDEO_RPC_SUBPIC_DEC_CONFIGURE;

struct VIDEO_RPC_SUBPIC_DEC_PAGE {
	u_int instanceID;
	u_short page_id_composition;
	u_short page_id_ancillary;
};
typedef struct VIDEO_RPC_SUBPIC_DEC_PAGE VIDEO_RPC_SUBPIC_DEC_PAGE;

struct VIDEO_RPC_JPEG_DEC_BATCH {
	u_int number;
	u_int structure_addr;
};
typedef struct VIDEO_RPC_JPEG_DEC_BATCH VIDEO_RPC_JPEG_DEC_BATCH;

struct VIDEO_RPC_TRANSITION_EFFECT {
	u_int instantID;
	u_int YBufID_A;
	u_int YBufID_B;
	u_int CBufID_A;
	u_int CBufID_B;
	u_int width;
	u_int height;
	u_int type;
	u_int frame_num;
	u_int PTS_inc;
	u_int start_x;
	u_int start_y;
	u_int start_width;
	u_int start_height;
	u_int end_x;
	u_int end_y;
	u_int end_width;
	u_int end_height;
	u_int pSharedTransEffCtrl;
	u_int YBufID_A_right;
	u_int YBufID_B_right;
	u_int CBufID_A_right;
	u_int CBufID_B_right;
};
typedef struct VIDEO_RPC_TRANSITION_EFFECT VIDEO_RPC_TRANSITION_EFFECT;

struct VIDEO_RPC_MIXER_FILTER_CONFIGURE {
	u_int instanceID;
	u_short width;
	u_short height;
	u_char EnablebgPicture;
	struct VO_COLOR bgColor;
	enum VO_OSD_COLOR_FORMAT colorFmt;
	enum VO_GRAPHIC_STORAGE_MODE storageMode;
	struct VO_RECTANGLE SrcWin;
	struct VO_RECTANGLE dispWin;
	u_short startX[2];
	u_short startY[2];
	u_short imgPitch[2];
	u_int pImage[2];
};
typedef struct VIDEO_RPC_MIXER_FILTER_CONFIGURE VIDEO_RPC_MIXER_FILTER_CONFIGURE;

struct VIDEO_RPC_MIXER_FILTER_CONFIGURE_WIN {
	u_int instanceID;
	u_int count;
	struct MIXER_WIN win[8];
};
typedef struct VIDEO_RPC_MIXER_FILTER_CONFIGURE_WIN VIDEO_RPC_MIXER_FILTER_CONFIGURE_WIN;

struct VIDEO_RPC_MIXER_FILTER_SET_MASTER_WIN {
	u_int instanceID;
	u_char winID;
};
typedef struct VIDEO_RPC_MIXER_FILTER_SET_MASTER_WIN VIDEO_RPC_MIXER_FILTER_SET_MASTER_WIN;

struct VIDEO_RPC_MIXER_PLAY_ONE_MOTION_JPEG_FRAME {
	u_char mixerWinID;
	enum VIDEO_STREAM_TYPE stream_type;
	enum YUV_FMT yuv_fmt;
	u_int base;
	u_int size;
	u_int width;
	u_int height;
};
typedef struct VIDEO_RPC_MIXER_PLAY_ONE_MOTION_JPEG_FRAME VIDEO_RPC_MIXER_PLAY_ONE_MOTION_JPEG_FRAME;

struct VIDEO_RPC_RESOURCE_INFO {
	enum VIDEO_RESOURCE_CTRL_TYPE ctrl_type;
	enum VIDEO_RESOURCE_CORE_TYPE core_type;
	int32_t video_port;
	int32_t max_width;
	int32_t max_height;
	u_int instanceID;
	int32_t width;
	int32_t height;
	int32_t framerate;
};
typedef struct VIDEO_RPC_RESOURCE_INFO VIDEO_RPC_RESOURCE_INFO;
#endif /* !_VIDEORPC_SYSTEM_DATA_H_RPCGEN */
