/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VIDEORPC_AGENT_DATA_H_RPCGEN
#define _VIDEORPC_AGENT_DATA_H_RPCGEN

#include <RPCBaseDS.h>
#include <VideoRPCBaseDS.h>
#include <AudioRPCBaseDS.h>
#include <AudioRPC_Agent.h>

struct VIDEO_DEC_FRM_MSG {
	ENUM_VIDEO_MSG_INFO_TYPE msgType;
	u_int frame_type;
	u_int PTSL;
	u_int PTSH;
	u_int reserved1;
	u_int reserved2;
	u_int reserved3;
	u_int reserved4;
	u_int reserved5;
	u_int reserved6;
	u_int reserved7;
	u_int reserved8;
	u_int reserved9;
	u_int reserved10;
	u_int reserved11;
	u_int reserved12;
	u_int reserved13;
	u_int reserved14;
	u_int reserved15;
	u_int reserved16;
	u_int reserved17;
	u_int reserved18;
	u_int reserved19;
};
typedef struct VIDEO_DEC_FRM_MSG VIDEO_DEC_FRM_MSG;

struct VIDEO_DEC_PIC_MSG {
	ENUM_VIDEO_MSG_INFO_TYPE msgType;
	u_int frame_rate;
	u_int bit_rate;
	u_int resol;
	u_int disp_resol;
	u_int actXY;
	u_int actWH;
	u_int sarWH;
	u_int prog_info;
	u_int ratio_info;
	u_int afd_3d;
	u_int PTSL;
	u_int PTSH;
	u_int color_transf;
	u_int coeffs_overscan;
	u_int dispXY0;
	u_int dispXY1;
	u_int dispXY2;
	u_int whitePointXY;
	u_int maxL;
	u_int minL;
	u_int videoFullRangeFlag;
	u_int reserved1;
};
typedef struct VIDEO_DEC_PIC_MSG VIDEO_DEC_PIC_MSG;

struct VIDEO_RPC_VOUT_MESSAGE {
	u_int instanceID;
	u_int message;
	u_int PTShigh;
	u_int PTSlow;
	u_int reserved1;
	u_int reserved2;
	u_int reserved3;
	u_int reserved4;
};
typedef struct VIDEO_RPC_VOUT_MESSAGE VIDEO_RPC_VOUT_MESSAGE;

struct VIDEO_RPC_DEC_FRAME_INFO {
	u_int instanceID;
	u_int PTSH;
	u_int PTSL;
	u_char frame_type;
};
typedef struct VIDEO_RPC_DEC_FRAME_INFO VIDEO_RPC_DEC_FRAME_INFO;

struct VIDEO_RPC_DEC_PIC_INFO {
	u_int instanceID;
	u_short frame_rate;
	u_short aspect_ratio;
	u_short hor_size;
	u_short ver_size;
	u_int bit_rate;
	u_char afd;
	u_char prog_seq;
	u_char prog_frame;
	u_short activeX;
	u_short activeY;
	u_short activeW;
	u_short activeH;
	u_short disp_hor_size;
	u_short disp_ver_size;
	u_char aspect_ratio_idc;
	u_int sar_width;
	u_int sar_height;
	u_char info_3D;
};
typedef struct VIDEO_RPC_DEC_PIC_INFO VIDEO_RPC_DEC_PIC_INFO;

struct VIDEO_RPC_DEC_MEDIA_INFO {
	u_int instanceID;
	u_int width;
	u_int height;
	u_int frame_rate;
	u_int aspect_ratio_n;
	u_int aspect_ratio_d;
	u_int level;
	u_int profile;
	u_int type_3D;
	u_int par_width;
	u_int par_height;
	u_int type_LR;
	u_int type_Scan;
	u_int afd;
};
typedef struct VIDEO_RPC_DEC_MEDIA_INFO VIDEO_RPC_DEC_MEDIA_INFO;

struct VIDEO_RPC_TO_KERNEL_PARAMETER {
	u_int command;
	u_int param1;
	u_int param2;
};
typedef struct VIDEO_RPC_TO_KERNEL_PARAMETER VIDEO_RPC_TO_KERNEL_PARAMETER;

struct VIDEO_RPC_TRANSITION_EFFECT_CTRL {
	u_int cancel;
	u_int percentage;
	VO_RECTANGLE winStart_A;
	VO_RECTANGLE winEnd_A;
	VO_RECTANGLE winStart_B;
	VO_RECTANGLE winEnd_B;
	u_int timeForKenBurns;
};
typedef struct VIDEO_RPC_TRANSITION_EFFECT_CTRL VIDEO_RPC_TRANSITION_EFFECT_CTRL;

#endif /* !_VIDEORPC_AGENT_DATA_H_RPCGEN */
