/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VIDEORPC_SYSTEM_H_RPCGEN
#define _VIDEORPC_SYSTEM_H_RPCGEN

#include <RPCstruct.h>

#include "VideoRPC_System_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCBaseDS.h>
#include <VideoRPCBaseDS.h>

#define VIDEO_SYSTEM 100
#define VERSION 0

struct REG_STRUCT * VIDEO_SYSTEM_0_register(struct REG_STRUCT *rnode);

#if defined(__STDC__) || defined(__cplusplus)
#define VIDEO_RPC_ToAgent_Create 10
extern  RPCRES_LONG * VIDEO_RPC_ToAgent_Create_0(VIDEO_RPC_INSTANCE *, CLNT_STRUCT *);
extern  RPCRES_LONG * VIDEO_RPC_ToAgent_Create_0_svc(VIDEO_RPC_INSTANCE *, RPC_STRUCT *, RPCRES_LONG *);
#define VIDEO_RPC_ToAgent_Connect 20
extern  HRESULT * VIDEO_RPC_ToAgent_Connect_0(RPC_CONNECTION *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_Connect_0_svc(RPC_CONNECTION *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_InitRingBuffer 30
extern  HRESULT * VIDEO_RPC_ToAgent_InitRingBuffer_0(RPC_RINGBUFFER *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_InitRingBuffer_0_svc(RPC_RINGBUFFER *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_Run 40
extern  HRESULT * VIDEO_RPC_ToAgent_Run_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_Run_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_Pause 50
extern  HRESULT * VIDEO_RPC_ToAgent_Pause_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_Pause_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_Stop 60
extern  HRESULT * VIDEO_RPC_ToAgent_Stop_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_Stop_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_Destroy 70
extern  HRESULT * VIDEO_RPC_ToAgent_Destroy_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_Destroy_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_Flush 80
extern  HRESULT * VIDEO_RPC_ToAgent_Flush_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_Flush_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_SetRefClock 90
extern  HRESULT * VIDEO_RPC_ToAgent_SetRefClock_0(VIDEO_RPC_SET_REFCLOCK *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_SetRefClock_0_svc(VIDEO_RPC_SET_REFCLOCK *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_VideoCreate 100
extern  HRESULT * VIDEO_RPC_ToAgent_VideoCreate_0(VIDEO_INIT_DATA *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_VideoCreate_0_svc(VIDEO_INIT_DATA *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_VideoConfig 105
extern  HRESULT * VIDEO_RPC_ToAgent_VideoConfig_0(VIDEO_CONFIG_DATA *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_VideoConfig_0_svc(VIDEO_CONFIG_DATA *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_VideoMemoryConfig 108
extern  VIDEO_RPC_VIDEO_FREE_MEMORY * VIDEO_RPC_ToAgent_VideoMemoryConfig_0(long *, CLNT_STRUCT *);
extern  VIDEO_RPC_VIDEO_FREE_MEMORY * VIDEO_RPC_ToAgent_VideoMemoryConfig_0_svc(long *, RPC_STRUCT *, VIDEO_RPC_VIDEO_FREE_MEMORY *);
#define VIDEO_RPC_ToAgent_VideoChunkConfig 109
extern  HRESULT * VIDEO_RPC_ToAgent_VideoChunkConfig_0(VIDEO_RPC_CONFIG_CHUNK *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_VideoChunkConfig_0_svc(VIDEO_RPC_CONFIG_CHUNK *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_VideoDestroy 110
extern  HRESULT * VIDEO_RPC_ToAgent_VideoDestroy_0(VIDEO_INIT_DATA *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_VideoDestroy_0_svc(VIDEO_INIT_DATA *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_RequestBuffer 120
extern  RPCRES_LONG * VIDEO_RPC_ToAgent_RequestBuffer_0(VIDEO_RPC_REQUEST_BUFFER *, CLNT_STRUCT *);
extern  RPCRES_LONG * VIDEO_RPC_ToAgent_RequestBuffer_0_svc(VIDEO_RPC_REQUEST_BUFFER *, RPC_STRUCT *, RPCRES_LONG *);
#define VIDEO_RPC_ToAgent_ReleaseBuffer 130
extern  HRESULT * VIDEO_RPC_ToAgent_ReleaseBuffer_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_ReleaseBuffer_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_SetFullHDBuffer 131
extern  HRESULT * VIDEO_RPC_ToAgent_SetFullHDBuffer_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_SetFullHDBuffer_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_FillBuffer 132
extern  HRESULT * VIDEO_RPC_ToAgent_FillBuffer_0(VIDEO_RPC_FILL_BUFFER *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_FillBuffer_0_svc(VIDEO_RPC_FILL_BUFFER *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_ConfigLowDelay 133
extern  HRESULT * VIDEO_RPC_ToAgent_ConfigLowDelay_0(VIDEO_RPC_LOW_DELAY *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_ConfigLowDelay_0_svc(VIDEO_RPC_LOW_DELAY *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_SetDebugMemory 140
extern  HRESULT * VIDEO_RPC_ToAgent_SetDebugMemory_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_SetDebugMemory_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_VideoHalt 150
extern  HRESULT * VIDEO_RPC_ToAgent_VideoHalt_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_VideoHalt_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_YUYV2RGB 160
extern  HRESULT * VIDEO_RPC_ToAgent_YUYV2RGB_0(VIDEO_RPC_YUYV_TO_RGB *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_ToAgent_YUYV2RGB_0_svc(VIDEO_RPC_YUYV_TO_RGB *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_ToAgent_PrivateInfo 165
extern  VIDEO_RPC_PRIVATEINFO_RETURNVAL * VIDEO_RPC_ToAgent_PrivateInfo_0(VIDEO_RPC_PRIVATEINFO_PARAMETERS *, CLNT_STRUCT *);
extern  VIDEO_RPC_PRIVATEINFO_RETURNVAL * VIDEO_RPC_ToAgent_PrivateInfo_0_svc(VIDEO_RPC_PRIVATEINFO_PARAMETERS *, RPC_STRUCT *, VIDEO_RPC_PRIVATEINFO_RETURNVAL *);
#define VIDEO_RPC_DEC_ToAgent_SetSpeed 1010
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetSpeed_0(VIDEO_RPC_DEC_SET_SPEED *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetSpeed_0_svc(VIDEO_RPC_DEC_SET_SPEED *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_DEC_ToAgent_SetErrorConcealmentLevel 1015
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetErrorConcealmentLevel_0(VIDEO_RPC_DEC_SET_ERR_CONCEALMENT_LEVEL *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetErrorConcealmentLevel_0_svc(VIDEO_RPC_DEC_SET_ERR_CONCEALMENT_LEVEL *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_DEC_ToAgent_Init 1020
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_Init_0(VIDEO_RPC_DEC_INIT *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_Init_0_svc(VIDEO_RPC_DEC_INIT *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_DEC_ToAgent_SetDeblock 1030
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetDeblock_0(VIDEO_RPC_DEC_SET_DEBLOCK *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetDeblock_0_svc(VIDEO_RPC_DEC_SET_DEBLOCK *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_DEC_ToAgent_GetVideoSequenceInfo 1035
extern  VIDEO_RPC_DEC_SEQ_INFO * VIDEO_RPC_DEC_ToAgent_GetVideoSequenceInfo_0(long *, CLNT_STRUCT *);
extern  VIDEO_RPC_DEC_SEQ_INFO * VIDEO_RPC_DEC_ToAgent_GetVideoSequenceInfo_0_svc(long *, RPC_STRUCT *, VIDEO_RPC_DEC_SEQ_INFO *);
#define VIDEO_RPC_DEC_ToAgent_BitstreamValidation 1040
extern  VIDEO_RPC_DEC_BV_RESULT * VIDEO_RPC_DEC_ToAgent_BitstreamValidation_0(VIDEO_RPC_DEC_BITSTREAM_BUFFER *, CLNT_STRUCT *);
extern  VIDEO_RPC_DEC_BV_RESULT * VIDEO_RPC_DEC_ToAgent_BitstreamValidation_0_svc(VIDEO_RPC_DEC_BITSTREAM_BUFFER *, RPC_STRUCT *, VIDEO_RPC_DEC_BV_RESULT *);
#define VIDEO_RPC_DEC_ToAgent_Capability 1045
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_Capability_0(VIDEO_RPC_DEC_CAPABILITY *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_Capability_0_svc(VIDEO_RPC_DEC_CAPABILITY *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_DEC_ToAgent_SetDecoderCCBypass 1050
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetDecoderCCBypass_0(VIDEO_RPC_DEC_CC_BYPASS_MODE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetDecoderCCBypass_0_svc(VIDEO_RPC_DEC_CC_BYPASS_MODE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_DEC_ToAgent_SetDNR 1060
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetDNR_0(VIDEO_RPC_DEC_SET_DNR *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetDNR_0_svc(VIDEO_RPC_DEC_SET_DNR *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_DEC_ToAgent_SetRefSyncLimit 1065
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetRefSyncLimit_0(VIDEO_RPC_DEC_SET_REF_SYNC_LIMIT *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetRefSyncLimit_0_svc(VIDEO_RPC_DEC_SET_REF_SYNC_LIMIT *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_THUMBNAIL_ToAgent_SetVscalerOutputFormat 1070
extern  HRESULT * VIDEO_RPC_THUMBNAIL_ToAgent_SetVscalerOutputFormat_0(VIDEO_RPC_THUMBNAIL_SET_VSCALER_OUTFORMAT *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_THUMBNAIL_ToAgent_SetVscalerOutputFormat_0_svc(VIDEO_RPC_THUMBNAIL_SET_VSCALER_OUTFORMAT *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_THUMBNAIL_ToAgent_SetThreshold 1080
extern  HRESULT * VIDEO_RPC_THUMBNAIL_ToAgent_SetThreshold_0(VIDEO_RPC_THUMBNAIL_SET_THRESHOLD *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_THUMBNAIL_ToAgent_SetThreshold_0_svc(VIDEO_RPC_THUMBNAIL_SET_THRESHOLD *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_FLASH_ToAgent_SetOutput 1085
extern  HRESULT * VIDEO_RPC_FLASH_ToAgent_SetOutput_0(VIDEO_RPC_FLASH_SET_OUTPUT *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_FLASH_ToAgent_SetOutput_0_svc(VIDEO_RPC_FLASH_SET_OUTPUT *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_THUMBNAIL_ToAgent_SetStartPictureNumber 1090
extern  HRESULT * VIDEO_RPC_THUMBNAIL_ToAgent_SetStartPictureNumber_0(VIDEO_RPC_THUMBNAIL_SET_STARTPIC *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_THUMBNAIL_ToAgent_SetStartPictureNumber_0_svc(VIDEO_RPC_THUMBNAIL_SET_STARTPIC *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_DEC_ToAgent_PrivateInfo 1095
extern  VIDEO_RPC_DEC_PRIVATEINFO_OUTPUT_PARAMETERS * VIDEO_RPC_DEC_ToAgent_PrivateInfo_0(VIDEO_RPC_DEC_PRIVATEINFO_INPUT_PARAMETERS *, CLNT_STRUCT *);
extern  VIDEO_RPC_DEC_PRIVATEINFO_OUTPUT_PARAMETERS * VIDEO_RPC_DEC_ToAgent_PrivateInfo_0_svc(VIDEO_RPC_DEC_PRIVATEINFO_INPUT_PARAMETERS *, RPC_STRUCT *, VIDEO_RPC_DEC_PRIVATEINFO_OUTPUT_PARAMETERS *);
#define VIDEO_RPC_VOUT_ToAgent_SetVideoStandard 3010
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoStandard_0(VIDEO_RPC_VOUT_SET_VIDEO_STANDARD *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoStandard_0_svc(VIDEO_RPC_VOUT_SET_VIDEO_STANDARD *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetHDMI 3011
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetHDMI_0(VIDEO_RPC_VOUT_SET_HDMI *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetHDMI_0_svc(VIDEO_RPC_VOUT_SET_HDMI *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ConfigHDMI 3012
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigHDMI_0(VIDEO_RPC_VOUT_CONFIG_HDMI *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigHDMI_0_svc(VIDEO_RPC_VOUT_CONFIG_HDMI *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ConfigHdmiInfoFrame 3013
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigHdmiInfoFrame_0(VIDEO_RPC_VOUT_CONFIG_HDMI_INFO_FRAME *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigHdmiInfoFrame_0_svc(VIDEO_RPC_VOUT_CONFIG_HDMI_INFO_FRAME *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ConfigVideoStandard 3014
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigVideoStandard_0(VIDEO_RPC_VOUT_CONFIG_VIDEO_STANDARD *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigVideoStandard_0_svc(VIDEO_RPC_VOUT_CONFIG_VIDEO_STANDARD *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ConfigTVSystem 3015
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigTVSystem_0(VIDEO_RPC_VOUT_CONFIG_TV_SYSTEM *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigTVSystem_0_svc(VIDEO_RPC_VOUT_CONFIG_TV_SYSTEM *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_AnaglyphConversion 3016
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_AnaglyphConversion_0(VIDEO_RPC_VOUT_ANAGLYPH_CONVERSION *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_AnaglyphConversion_0_svc(VIDEO_RPC_VOUT_ANAGLYPH_CONVERSION *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ConfigMacroVision 3340
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigMacroVision_0(VIDEO_RPC_VOUT_CONFIG_MACROVISION *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigMacroVision_0_svc(VIDEO_RPC_VOUT_CONFIG_MACROVISION *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetTVtype 3020
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetTVtype_0(VO_TV_TYPE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetTVtype_0_svc(VO_TV_TYPE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetBackground 3030
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetBackground_0(VIDEO_RPC_VOUT_SET_BKGRND *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetBackground_0_svc(VIDEO_RPC_VOUT_SET_BKGRND *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetMixerOrder 3031
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetMixerOrder_0(VIDEO_RPC_VOUT_SET_MIXER_ORDER *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetMixerOrder_0_svc(VIDEO_RPC_VOUT_SET_MIXER_ORDER *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_GetMixerOrder 3032
extern  VIDEO_RPC_VOUT_SET_MIXER_ORDER * VIDEO_RPC_VOUT_ToAgent_GetMixerOrder_0(void *, CLNT_STRUCT *);
extern  VIDEO_RPC_VOUT_SET_MIXER_ORDER * VIDEO_RPC_VOUT_ToAgent_GetMixerOrder_0_svc(void *, RPC_STRUCT *, VIDEO_RPC_VOUT_SET_MIXER_ORDER *);
#define VIDEO_RPC_VOUT_ToAgent_SetClosedCaption 3040
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetClosedCaption_0(VIDEO_RPC_VOUT_SET_CC *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetClosedCaption_0_svc(VIDEO_RPC_VOUT_SET_CC *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetAPS 3050
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetAPS_0(VIDEO_RPC_VOUT_SET_APS *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetAPS_0_svc(VIDEO_RPC_VOUT_SET_APS *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetCopyMode 3060
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetCopyMode_0(VIDEO_RPC_VOUT_SET_COPY_MODE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetCopyMode_0_svc(VIDEO_RPC_VOUT_SET_COPY_MODE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetAspectRatio 3070
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetAspectRatio_0(VIDEO_RPC_VOUT_SET_AR *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetAspectRatio_0_svc(VIDEO_RPC_VOUT_SET_AR *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ConfigureDisplayWindow 3080
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureDisplayWindow_0(VIDEO_RPC_VOUT_CONFIG_DISP_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureDisplayWindow_0_svc(VIDEO_RPC_VOUT_CONFIG_DISP_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_PMixer_ConfigurePlaneMixer 3085
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_PMixer_ConfigurePlaneMixer_0(VIDEO_RPC_VOUT_CONFIGURE_PLANE_MIXER *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_PMixer_ConfigurePlaneMixer_0_svc(VIDEO_RPC_VOUT_CONFIGURE_PLANE_MIXER *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_3D_ConfigureShiftOffset 3087
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_3D_ConfigureShiftOffset_0(VIDEO_RPC_VOUT_CONFIGURE_3D_OFFSET *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_3D_ConfigureShiftOffset_0_svc(VIDEO_RPC_VOUT_CONFIGURE_3D_OFFSET *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetV2alpha 3090
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetV2alpha_0(u_char *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetV2alpha_0_svc(u_char *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetRescaleMode 3100
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetRescaleMode_0(VIDEO_RPC_VOUT_SET_RESCALE_MODE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetRescaleMode_0_svc(VIDEO_RPC_VOUT_SET_RESCALE_MODE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetDeintMode 3110
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetDeintMode_0(VIDEO_RPC_VOUT_SET_DEINT_MODE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetDeintMode_0_svc(VIDEO_RPC_VOUT_SET_DEINT_MODE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_Zoom 3120
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_Zoom_0(VIDEO_RPC_VOUT_ZOOM *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_Zoom_0_svc(VIDEO_RPC_VOUT_ZOOM *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_Pan_Zoom 3121
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_Pan_Zoom_0(VIDEO_RPC_VOUT_PAN_ZOOM *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_Pan_Zoom_0_svc(VIDEO_RPC_VOUT_PAN_ZOOM *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetTransparency 3122
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetTransparency_0(VIDEO_RPC_VOUT_TRANSPARENCY *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetTransparency_0_svc(VIDEO_RPC_VOUT_TRANSPARENCY *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_Actual_Zoom 3123
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_Actual_Zoom_0(VIDEO_RPC_VOUT_ACTUAL_ZOOM *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_Actual_Zoom_0_svc(VIDEO_RPC_VOUT_ACTUAL_ZOOM *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ConfigureOSD 3130
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureOSD_0(VIDEO_RPC_VOUT_CONFIG_OSD *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureOSD_0_svc(VIDEO_RPC_VOUT_CONFIG_OSD *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ConfigureOSDPalette 3131
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureOSDPalette_0(VIDEO_RPC_VOUT_CONFIG_OSD_PALETTE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureOSDPalette_0_svc(VIDEO_RPC_VOUT_CONFIG_OSD_PALETTE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_CreateOSDwindow 3140
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_CreateOSDwindow_0(VIDEO_RPC_VOUT_CREATE_OSD_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_CreateOSDwindow_0_svc(VIDEO_RPC_VOUT_CREATE_OSD_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetOSDwindowPalette 3141
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetOSDwindowPalette_0(VIDEO_RPC_VOUT_SET_OSD_WIN_PALETTE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetOSDwindowPalette_0_svc(VIDEO_RPC_VOUT_SET_OSD_WIN_PALETTE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindow 3150
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindow_0(VIDEO_RPC_VOUT_MODIFY_OSD_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindow_0_svc(VIDEO_RPC_VOUT_MODIFY_OSD_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindowOnGo 3151
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindowOnGo_0(VIDEO_RPC_VOUT_MODIFY_OSD_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindowOnGo_0_svc(VIDEO_RPC_VOUT_MODIFY_OSD_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindow 3160
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindow_0(u_char *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindow_0_svc(u_char *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindowOnGo 3161
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindowOnGo_0(VIDEO_RPC_VOUT_DELETE_OSD_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindowOnGo_0_svc(VIDEO_RPC_VOUT_DELETE_OSD_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_DrawOSDwindow 3170
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawOSDwindow_0(VIDEO_RPC_VOUT_DRAW_OSD_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawOSDwindow_0_svc(VIDEO_RPC_VOUT_DRAW_OSD_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_DrawOSDwindowOnGo 3171
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawOSDwindowOnGo_0(VIDEO_RPC_VOUT_DRAW_OSD_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawOSDwindowOnGo_0_svc(VIDEO_RPC_VOUT_DRAW_OSD_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_HideOSDwindow 3180
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideOSDwindow_0(u_char *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideOSDwindow_0_svc(u_char *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_HideOSDwindowOnGo 3181
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideOSDwindowOnGo_0(VIDEO_RPC_VOUT_HIDE_OSD_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideOSDwindowOnGo_0_svc(VIDEO_RPC_VOUT_HIDE_OSD_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ConfigOSDCanvas 3182
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigOSDCanvas_0(VIDEO_RPC_VOUT_CONFIG_OSD_CANVAS *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigOSDCanvas_0_svc(VIDEO_RPC_VOUT_CONFIG_OSD_CANVAS *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ConfigureGraphicCanvas 3183
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureGraphicCanvas_0(VIDEO_RPC_VOUT_CONFIG_GRAPHIC_CANVAS *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureGraphicCanvas_0_svc(VIDEO_RPC_VOUT_CONFIG_GRAPHIC_CANVAS *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_CreateGraphicWindow 3184
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_CreateGraphicWindow_0(VIDEO_RPC_VOUT_CREATE_GRAPHIC_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_CreateGraphicWindow_0_svc(VIDEO_RPC_VOUT_CREATE_GRAPHIC_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_HideGraphicWindow 3185
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideGraphicWindow_0(VIDEO_RPC_VOUT_HIDE_GRAPHIC_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideGraphicWindow_0_svc(VIDEO_RPC_VOUT_HIDE_GRAPHIC_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ModifyGraphicWindow 3186
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ModifyGraphicWindow_0(VIDEO_RPC_VOUT_MODIFY_GRAPHIC_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ModifyGraphicWindow_0_svc(VIDEO_RPC_VOUT_MODIFY_GRAPHIC_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_DeleteGraphicWindow 3187
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DeleteGraphicWindow_0(VIDEO_RPC_VOUT_DELETE_GRAPHIC_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DeleteGraphicWindow_0_svc(VIDEO_RPC_VOUT_DELETE_GRAPHIC_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_DrawGraphicWindow 3188
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawGraphicWindow_0(VIDEO_RPC_VOUT_DRAW_GRAPHIC_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawGraphicWindow_0_svc(VIDEO_RPC_VOUT_DRAW_GRAPHIC_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_DisplayGraphic 3189
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DisplayGraphic_0(VIDEO_RPC_VOUT_DISPLAY_GRAPHIC *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DisplayGraphic_0_svc(VIDEO_RPC_VOUT_DISPLAY_GRAPHIC *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ConfigureCursor 3190
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureCursor_0(VIDEO_RPC_VOUT_CONFIG_CURSOR *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureCursor_0_svc(VIDEO_RPC_VOUT_CONFIG_CURSOR *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ConfigureMarsCursor 3192
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureMarsCursor_0(VIDEO_RPC_VOUT_CONFIG_MARS_CURSOR *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureMarsCursor_0_svc(VIDEO_RPC_VOUT_CONFIG_MARS_CURSOR *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_DrawCursor 3200
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawCursor_0(VIDEO_RPC_VOUT_DRAW_CURSOR *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawCursor_0_svc(VIDEO_RPC_VOUT_DRAW_CURSOR *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_HideCursor 3210
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideCursor_0(void *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideCursor_0_svc(void *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetPeakingStrength 3220
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetPeakingStrength_0(u_char *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetPeakingStrength_0_svc(u_char *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetBrightness 3230
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetBrightness_0(u_char *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetBrightness_0_svc(u_char *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetVideoBrightness 3235
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoBrightness_0(u_char *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoBrightness_0_svc(u_char *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetHue 3240
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetHue_0(u_char *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetHue_0_svc(u_char *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetVideoHue 3245
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoHue_0(u_char *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoHue_0_svc(u_char *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetSaturation 3250
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetSaturation_0(u_char *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetSaturation_0_svc(u_char *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetVideoSaturation 3252
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoSaturation_0(u_char *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoSaturation_0_svc(u_char *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetVideoContrast 3254
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoContrast_0(u_char *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoContrast_0_svc(u_char *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetContrast 3255
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetContrast_0(u_char *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetContrast_0_svc(u_char *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_ConfigColorMatrix 3256
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigColorMatrix_0(VIDEO_RPC_VOUT_CONFIG_COLOR_MATRIX *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigColorMatrix_0_svc(VIDEO_RPC_VOUT_CONFIG_COLOR_MATRIX *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_VideoCapture 3257
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_VideoCapture_0(VIDEO_RPC_VOUT_VIDEO_CAPTURE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_VideoCapture_0_svc(VIDEO_RPC_VOUT_VIDEO_CAPTURE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SetSubtitleYoffset 3258
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetSubtitleYoffset_0(short *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetSubtitleYoffset_0_svc(short *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_SwitchSPDomination 3259
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SwitchSPDomination_0(short *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SwitchSPDomination_0_svc(short *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VOUT_ToAgent_DisplayWinAnimation 3350
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DisplayWinAnimation_0(VIDEO_RPC_VOUT_DISP_WIN_ANIMATION *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DisplayWinAnimation_0_svc(VIDEO_RPC_VOUT_DISP_WIN_ANIMATION *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VO_FILTER_ToAgent_Display 3260
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_Display_0(VIDEO_RPC_VO_FILTER_DISPLAY *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_Display_0_svc(VIDEO_RPC_VO_FILTER_DISPLAY *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VO_FILTER_ToAgent_Capture 3270
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_Capture_0(VIDEO_RPC_VO_FILTER_CAPTURE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_Capture_0_svc(VIDEO_RPC_VO_FILTER_CAPTURE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VO_FILTER_ToAgent_SetSpeed 3290
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_SetSpeed_0(VIDEO_RPC_VO_FILTER_SET_SPEED *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_SetSpeed_0_svc(VIDEO_RPC_VO_FILTER_SET_SPEED *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VO_FILTER_ToAgent_Step 3300
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_Step_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_Step_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VO_FILTER_ToAgent_ShowStillPicture 3310
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_ShowStillPicture_0(VIDEO_RPC_VO_FILTER_SHOW_STILL_PIC *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_ShowStillPicture_0_svc(VIDEO_RPC_VO_FILTER_SHOW_STILL_PIC *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VO_FILTER_ToAgent_FillVideoBorder 3320
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_FillVideoBorder_0(VIDEO_RPC_VO_FILTER_FILL_VIDEO_BORDER *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_FillVideoBorder_0_svc(VIDEO_RPC_VO_FILTER_FILL_VIDEO_BORDER *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VO_FILTER_ToAgent_SetFastDisplay 3330
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_SetFastDisplay_0(VIDEO_RPC_VO_FILTER_SET_FAST_DISPLAY *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_SetFastDisplay_0_svc(VIDEO_RPC_VO_FILTER_SET_FAST_DISPLAY *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_VO_FILTER_ToAgent_PrivateInfo 3335
extern  VIDEO_RPC_VO_PRIVATEINFO_OUTPUT_PARAMETERS * VIDEO_RPC_VO_FILTER_ToAgent_PrivateInfo_0(VIDEO_RPC_VO_PRIVATEINFO_INPUT_PARAMETERS *, CLNT_STRUCT *);
extern  VIDEO_RPC_VO_PRIVATEINFO_OUTPUT_PARAMETERS * VIDEO_RPC_VO_FILTER_ToAgent_PrivateInfo_0_svc(VIDEO_RPC_VO_PRIVATEINFO_INPUT_PARAMETERS *, RPC_STRUCT *, VIDEO_RPC_VO_PRIVATEINFO_OUTPUT_PARAMETERS *);
#define VIDEO_RPC_VOUT_ToAgent_VideoRotate 3345
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_VideoRotate_0(VIDEO_RPC_VOUT_VIDEO_ROTATE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_VideoRotate_0_svc(VIDEO_RPC_VOUT_VIDEO_ROTATE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_SUBPIC_DEC_ToAgent_EnableSubPicture 5010
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_EnableSubPicture_0(VIDEO_RPC_SUBPIC_DEC_ENABLE_SUBPIC *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_EnableSubPicture_0_svc(VIDEO_RPC_SUBPIC_DEC_ENABLE_SUBPIC *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_SUBPIC_DEC_ToAgent_ShowSubPicture 5020
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_ShowSubPicture_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_ShowSubPicture_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_SUBPIC_DEC_ToAgent_HideSubPicture 5030
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_HideSubPicture_0(long *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_HideSubPicture_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_SUBPIC_DEC_ToAgent_Configure 5040
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_Configure_0(VIDEO_RPC_SUBPIC_DEC_CONFIGURE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_Configure_0_svc(VIDEO_RPC_SUBPIC_DEC_CONFIGURE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_SUBPIC_DEC_ToAgent_Page 5050
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_Page_0(VIDEO_RPC_SUBPIC_DEC_PAGE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_Page_0_svc(VIDEO_RPC_SUBPIC_DEC_PAGE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_JPEG_ToAgent_DEC 6010
extern  HRESULT * VIDEO_RPC_JPEG_ToAgent_DEC_0(VIDEO_RPC_JPEG_DEC *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_JPEG_ToAgent_DEC_0_svc(VIDEO_RPC_JPEG_DEC *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_JPEG_ToAgent_DEC_BATCH 6011
extern  HRESULT * VIDEO_RPC_JPEG_ToAgent_DEC_BATCH_0(VIDEO_RPC_JPEG_DEC_BATCH *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_JPEG_ToAgent_DEC_BATCH_0_svc(VIDEO_RPC_JPEG_DEC_BATCH *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_TRANSITION_ToAgent_Start 6020
extern  HRESULT * VIDEO_RPC_TRANSITION_ToAgent_Start_0(VIDEO_RPC_TRANSITION_EFFECT *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_TRANSITION_ToAgent_Start_0_svc(VIDEO_RPC_TRANSITION_EFFECT *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_MIXER_FILTER_ToAgent_Configure 8010
extern  HRESULT * VIDEO_RPC_MIXER_FILTER_ToAgent_Configure_0(VIDEO_RPC_MIXER_FILTER_CONFIGURE *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_MIXER_FILTER_ToAgent_Configure_0_svc(VIDEO_RPC_MIXER_FILTER_CONFIGURE *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_MIXER_FILTER_ToAgent_ConfigureWindow 8020
extern  HRESULT * VIDEO_RPC_MIXER_FILTER_ToAgent_ConfigureWindow_0(VIDEO_RPC_MIXER_FILTER_CONFIGURE_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_MIXER_FILTER_ToAgent_ConfigureWindow_0_svc(VIDEO_RPC_MIXER_FILTER_CONFIGURE_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_MIXER_FILTER_ToAgent_SetMasterWindow 8030
extern  HRESULT * VIDEO_RPC_MIXER_FILTER_ToAgent_SetMasterWindow_0(VIDEO_RPC_MIXER_FILTER_SET_MASTER_WIN *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_MIXER_FILTER_ToAgent_SetMasterWindow_0_svc(VIDEO_RPC_MIXER_FILTER_SET_MASTER_WIN *, RPC_STRUCT *, HRESULT *);
#define VIDEO_RPC_MIXER_ToAgent_PlayOneMotionJpegFrame 8040
extern  HRESULT * VIDEO_RPC_MIXER_ToAgent_PlayOneMotionJpegFrame_0(VIDEO_RPC_MIXER_PLAY_ONE_MOTION_JPEG_FRAME *, CLNT_STRUCT *);
extern  HRESULT * VIDEO_RPC_MIXER_ToAgent_PlayOneMotionJpegFrame_0_svc(VIDEO_RPC_MIXER_PLAY_ONE_MOTION_JPEG_FRAME *, RPC_STRUCT *, HRESULT *);

#else /* K&R C */
#define VIDEO_RPC_ToAgent_Create 10
extern  RPCRES_LONG * VIDEO_RPC_ToAgent_Create_0();
extern  RPCRES_LONG * VIDEO_RPC_ToAgent_Create_0_svc();
#define VIDEO_RPC_ToAgent_Connect 20
extern  HRESULT * VIDEO_RPC_ToAgent_Connect_0();
extern  HRESULT * VIDEO_RPC_ToAgent_Connect_0_svc();
#define VIDEO_RPC_ToAgent_InitRingBuffer 30
extern  HRESULT * VIDEO_RPC_ToAgent_InitRingBuffer_0();
extern  HRESULT * VIDEO_RPC_ToAgent_InitRingBuffer_0_svc();
#define VIDEO_RPC_ToAgent_Run 40
extern  HRESULT * VIDEO_RPC_ToAgent_Run_0();
extern  HRESULT * VIDEO_RPC_ToAgent_Run_0_svc();
#define VIDEO_RPC_ToAgent_Pause 50
extern  HRESULT * VIDEO_RPC_ToAgent_Pause_0();
extern  HRESULT * VIDEO_RPC_ToAgent_Pause_0_svc();
#define VIDEO_RPC_ToAgent_Stop 60
extern  HRESULT * VIDEO_RPC_ToAgent_Stop_0();
extern  HRESULT * VIDEO_RPC_ToAgent_Stop_0_svc();
#define VIDEO_RPC_ToAgent_Destroy 70
extern  HRESULT * VIDEO_RPC_ToAgent_Destroy_0();
extern  HRESULT * VIDEO_RPC_ToAgent_Destroy_0_svc();
#define VIDEO_RPC_ToAgent_Flush 80
extern  HRESULT * VIDEO_RPC_ToAgent_Flush_0();
extern  HRESULT * VIDEO_RPC_ToAgent_Flush_0_svc();
#define VIDEO_RPC_ToAgent_SetRefClock 90
extern  HRESULT * VIDEO_RPC_ToAgent_SetRefClock_0();
extern  HRESULT * VIDEO_RPC_ToAgent_SetRefClock_0_svc();
#define VIDEO_RPC_ToAgent_VideoCreate 100
extern  HRESULT * VIDEO_RPC_ToAgent_VideoCreate_0();
extern  HRESULT * VIDEO_RPC_ToAgent_VideoCreate_0_svc();
#define VIDEO_RPC_ToAgent_VideoConfig 105
extern  HRESULT * VIDEO_RPC_ToAgent_VideoConfig_0();
extern  HRESULT * VIDEO_RPC_ToAgent_VideoConfig_0_svc();
#define VIDEO_RPC_ToAgent_VideoMemoryConfig 108
extern  VIDEO_RPC_VIDEO_FREE_MEMORY * VIDEO_RPC_ToAgent_VideoMemoryConfig_0();
extern  VIDEO_RPC_VIDEO_FREE_MEMORY * VIDEO_RPC_ToAgent_VideoMemoryConfig_0_svc();
#define VIDEO_RPC_ToAgent_VideoChunkConfig 109
extern  HRESULT * VIDEO_RPC_ToAgent_VideoChunkConfig_0();
extern  HRESULT * VIDEO_RPC_ToAgent_VideoChunkConfig_0_svc();
#define VIDEO_RPC_ToAgent_VideoDestroy 110
extern  HRESULT * VIDEO_RPC_ToAgent_VideoDestroy_0();
extern  HRESULT * VIDEO_RPC_ToAgent_VideoDestroy_0_svc();
#define VIDEO_RPC_ToAgent_RequestBuffer 120
extern  RPCRES_LONG * VIDEO_RPC_ToAgent_RequestBuffer_0();
extern  RPCRES_LONG * VIDEO_RPC_ToAgent_RequestBuffer_0_svc();
#define VIDEO_RPC_ToAgent_ReleaseBuffer 130
extern  HRESULT * VIDEO_RPC_ToAgent_ReleaseBuffer_0();
extern  HRESULT * VIDEO_RPC_ToAgent_ReleaseBuffer_0_svc();
#define VIDEO_RPC_ToAgent_SetFullHDBuffer 131
extern  HRESULT * VIDEO_RPC_ToAgent_SetFullHDBuffer_0();
extern  HRESULT * VIDEO_RPC_ToAgent_SetFullHDBuffer_0_svc();
#define VIDEO_RPC_ToAgent_FillBuffer 132
extern  HRESULT * VIDEO_RPC_ToAgent_FillBuffer_0();
extern  HRESULT * VIDEO_RPC_ToAgent_FillBuffer_0_svc();
#define VIDEO_RPC_ToAgent_ConfigLowDelay 133
extern  HRESULT * VIDEO_RPC_ToAgent_ConfigLowDelay_0();
extern  HRESULT * VIDEO_RPC_ToAgent_ConfigLowDelay_0_svc();
#define VIDEO_RPC_ToAgent_SetDebugMemory 140
extern  HRESULT * VIDEO_RPC_ToAgent_SetDebugMemory_0();
extern  HRESULT * VIDEO_RPC_ToAgent_SetDebugMemory_0_svc();
#define VIDEO_RPC_ToAgent_VideoHalt 150
extern  HRESULT * VIDEO_RPC_ToAgent_VideoHalt_0();
extern  HRESULT * VIDEO_RPC_ToAgent_VideoHalt_0_svc();
#define VIDEO_RPC_ToAgent_YUYV2RGB 160
extern  HRESULT * VIDEO_RPC_ToAgent_YUYV2RGB_0();
extern  HRESULT * VIDEO_RPC_ToAgent_YUYV2RGB_0_svc();
#define VIDEO_RPC_ToAgent_PrivateInfo 165
extern  VIDEO_RPC_PRIVATEINFO_RETURNVAL * VIDEO_RPC_ToAgent_PrivateInfo_0();
extern  VIDEO_RPC_PRIVATEINFO_RETURNVAL * VIDEO_RPC_ToAgent_PrivateInfo_0_svc();
#define VIDEO_RPC_DEC_ToAgent_SetSpeed 1010
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetSpeed_0();
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetSpeed_0_svc();
#define VIDEO_RPC_DEC_ToAgent_SetErrorConcealmentLevel 1015
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetErrorConcealmentLevel_0();
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetErrorConcealmentLevel_0_svc();
#define VIDEO_RPC_DEC_ToAgent_Init 1020
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_Init_0();
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_Init_0_svc();
#define VIDEO_RPC_DEC_ToAgent_SetDeblock 1030
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetDeblock_0();
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetDeblock_0_svc();
#define VIDEO_RPC_DEC_ToAgent_GetVideoSequenceInfo 1035
extern  VIDEO_RPC_DEC_SEQ_INFO * VIDEO_RPC_DEC_ToAgent_GetVideoSequenceInfo_0();
extern  VIDEO_RPC_DEC_SEQ_INFO * VIDEO_RPC_DEC_ToAgent_GetVideoSequenceInfo_0_svc();
#define VIDEO_RPC_DEC_ToAgent_BitstreamValidation 1040
extern  VIDEO_RPC_DEC_BV_RESULT * VIDEO_RPC_DEC_ToAgent_BitstreamValidation_0();
extern  VIDEO_RPC_DEC_BV_RESULT * VIDEO_RPC_DEC_ToAgent_BitstreamValidation_0_svc();
#define VIDEO_RPC_DEC_ToAgent_Capability 1045
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_Capability_0();
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_Capability_0_svc();
#define VIDEO_RPC_DEC_ToAgent_SetDecoderCCBypass 1050
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetDecoderCCBypass_0();
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetDecoderCCBypass_0_svc();
#define VIDEO_RPC_DEC_ToAgent_SetDNR 1060
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetDNR_0();
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetDNR_0_svc();
#define VIDEO_RPC_DEC_ToAgent_SetRefSyncLimit 1065
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetRefSyncLimit_0();
extern  HRESULT * VIDEO_RPC_DEC_ToAgent_SetRefSyncLimit_0_svc();
#define VIDEO_RPC_THUMBNAIL_ToAgent_SetVscalerOutputFormat 1070
extern  HRESULT * VIDEO_RPC_THUMBNAIL_ToAgent_SetVscalerOutputFormat_0();
extern  HRESULT * VIDEO_RPC_THUMBNAIL_ToAgent_SetVscalerOutputFormat_0_svc();
#define VIDEO_RPC_THUMBNAIL_ToAgent_SetThreshold 1080
extern  HRESULT * VIDEO_RPC_THUMBNAIL_ToAgent_SetThreshold_0();
extern  HRESULT * VIDEO_RPC_THUMBNAIL_ToAgent_SetThreshold_0_svc();
#define VIDEO_RPC_FLASH_ToAgent_SetOutput 1085
extern  HRESULT * VIDEO_RPC_FLASH_ToAgent_SetOutput_0();
extern  HRESULT * VIDEO_RPC_FLASH_ToAgent_SetOutput_0_svc();
#define VIDEO_RPC_THUMBNAIL_ToAgent_SetStartPictureNumber 1090
extern  HRESULT * VIDEO_RPC_THUMBNAIL_ToAgent_SetStartPictureNumber_0();
extern  HRESULT * VIDEO_RPC_THUMBNAIL_ToAgent_SetStartPictureNumber_0_svc();
#define VIDEO_RPC_DEC_ToAgent_PrivateInfo 1095
extern  VIDEO_RPC_DEC_PRIVATEINFO_OUTPUT_PARAMETERS * VIDEO_RPC_DEC_ToAgent_PrivateInfo_0();
extern  VIDEO_RPC_DEC_PRIVATEINFO_OUTPUT_PARAMETERS * VIDEO_RPC_DEC_ToAgent_PrivateInfo_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetVideoStandard 3010
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoStandard_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoStandard_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetHDMI 3011
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetHDMI_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetHDMI_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ConfigHDMI 3012
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigHDMI_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigHDMI_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ConfigHdmiInfoFrame 3013
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigHdmiInfoFrame_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigHdmiInfoFrame_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ConfigVideoStandard 3014
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigVideoStandard_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigVideoStandard_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ConfigTVSystem 3015
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigTVSystem_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigTVSystem_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_AnaglyphConversion 3016
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_AnaglyphConversion_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_AnaglyphConversion_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ConfigMacroVision 3340
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigMacroVision_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigMacroVision_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetTVtype 3020
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetTVtype_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetTVtype_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetBackground 3030
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetBackground_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetBackground_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetMixerOrder 3031
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetMixerOrder_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetMixerOrder_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_GetMixerOrder 3032
extern  VIDEO_RPC_VOUT_SET_MIXER_ORDER * VIDEO_RPC_VOUT_ToAgent_GetMixerOrder_0();
extern  VIDEO_RPC_VOUT_SET_MIXER_ORDER * VIDEO_RPC_VOUT_ToAgent_GetMixerOrder_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetClosedCaption 3040
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetClosedCaption_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetClosedCaption_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetAPS 3050
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetAPS_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetAPS_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetCopyMode 3060
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetCopyMode_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetCopyMode_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetAspectRatio 3070
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetAspectRatio_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetAspectRatio_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ConfigureDisplayWindow 3080
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureDisplayWindow_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureDisplayWindow_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_PMixer_ConfigurePlaneMixer 3085
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_PMixer_ConfigurePlaneMixer_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_PMixer_ConfigurePlaneMixer_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_3D_ConfigureShiftOffset 3087
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_3D_ConfigureShiftOffset_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_3D_ConfigureShiftOffset_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetV2alpha 3090
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetV2alpha_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetV2alpha_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetRescaleMode 3100
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetRescaleMode_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetRescaleMode_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetDeintMode 3110
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetDeintMode_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetDeintMode_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_Zoom 3120
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_Zoom_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_Zoom_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_Pan_Zoom 3121
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_Pan_Zoom_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_Pan_Zoom_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetTransparency 3122
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetTransparency_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetTransparency_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_Actual_Zoom 3123
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_Actual_Zoom_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_Actual_Zoom_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ConfigureOSD 3130
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureOSD_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureOSD_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ConfigureOSDPalette 3131
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureOSDPalette_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureOSDPalette_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_CreateOSDwindow 3140
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_CreateOSDwindow_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_CreateOSDwindow_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetOSDwindowPalette 3141
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetOSDwindowPalette_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetOSDwindowPalette_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindow 3150
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindow_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindow_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindowOnGo 3151
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindowOnGo_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ModifyOSDwindowOnGo_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindow 3160
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindow_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindow_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindowOnGo 3161
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindowOnGo_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DeleteOSDwindowOnGo_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_DrawOSDwindow 3170
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawOSDwindow_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawOSDwindow_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_DrawOSDwindowOnGo 3171
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawOSDwindowOnGo_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawOSDwindowOnGo_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_HideOSDwindow 3180
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideOSDwindow_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideOSDwindow_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_HideOSDwindowOnGo 3181
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideOSDwindowOnGo_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideOSDwindowOnGo_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ConfigOSDCanvas 3182
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigOSDCanvas_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigOSDCanvas_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ConfigureGraphicCanvas 3183
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureGraphicCanvas_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureGraphicCanvas_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_CreateGraphicWindow 3184
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_CreateGraphicWindow_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_CreateGraphicWindow_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_HideGraphicWindow 3185
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideGraphicWindow_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideGraphicWindow_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ModifyGraphicWindow 3186
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ModifyGraphicWindow_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ModifyGraphicWindow_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_DeleteGraphicWindow 3187
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DeleteGraphicWindow_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DeleteGraphicWindow_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_DrawGraphicWindow 3188
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawGraphicWindow_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawGraphicWindow_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_DisplayGraphic 3189
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DisplayGraphic_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DisplayGraphic_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ConfigureCursor 3190
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureCursor_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureCursor_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ConfigureMarsCursor 3192
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureMarsCursor_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigureMarsCursor_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_DrawCursor 3200
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawCursor_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DrawCursor_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_HideCursor 3210
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideCursor_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_HideCursor_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetPeakingStrength 3220
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetPeakingStrength_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetPeakingStrength_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetBrightness 3230
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetBrightness_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetBrightness_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetVideoBrightness 3235
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoBrightness_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoBrightness_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetHue 3240
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetHue_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetHue_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetVideoHue 3245
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoHue_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoHue_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetSaturation 3250
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetSaturation_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetSaturation_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetVideoSaturation 3252
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoSaturation_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoSaturation_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetVideoContrast 3254
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoContrast_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetVideoContrast_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetContrast 3255
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetContrast_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetContrast_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_ConfigColorMatrix 3256
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigColorMatrix_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_ConfigColorMatrix_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_VideoCapture 3257
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_VideoCapture_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_VideoCapture_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SetSubtitleYoffset 3258
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetSubtitleYoffset_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SetSubtitleYoffset_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_SwitchSPDomination 3259
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SwitchSPDomination_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_SwitchSPDomination_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_DisplayWinAnimation 3350
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DisplayWinAnimation_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_DisplayWinAnimation_0_svc();
#define VIDEO_RPC_VO_FILTER_ToAgent_Display 3260
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_Display_0();
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_Display_0_svc();
#define VIDEO_RPC_VO_FILTER_ToAgent_Capture 3270
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_Capture_0();
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_Capture_0_svc();
#define VIDEO_RPC_VO_FILTER_ToAgent_SetSpeed 3290
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_SetSpeed_0();
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_SetSpeed_0_svc();
#define VIDEO_RPC_VO_FILTER_ToAgent_Step 3300
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_Step_0();
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_Step_0_svc();
#define VIDEO_RPC_VO_FILTER_ToAgent_ShowStillPicture 3310
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_ShowStillPicture_0();
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_ShowStillPicture_0_svc();
#define VIDEO_RPC_VO_FILTER_ToAgent_FillVideoBorder 3320
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_FillVideoBorder_0();
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_FillVideoBorder_0_svc();
#define VIDEO_RPC_VO_FILTER_ToAgent_SetFastDisplay 3330
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_SetFastDisplay_0();
extern  HRESULT * VIDEO_RPC_VO_FILTER_ToAgent_SetFastDisplay_0_svc();
#define VIDEO_RPC_VO_FILTER_ToAgent_PrivateInfo 3335
extern  VIDEO_RPC_VO_PRIVATEINFO_OUTPUT_PARAMETERS * VIDEO_RPC_VO_FILTER_ToAgent_PrivateInfo_0();
extern  VIDEO_RPC_VO_PRIVATEINFO_OUTPUT_PARAMETERS * VIDEO_RPC_VO_FILTER_ToAgent_PrivateInfo_0_svc();
#define VIDEO_RPC_VOUT_ToAgent_VideoRotate 3345
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_VideoRotate_0();
extern  HRESULT * VIDEO_RPC_VOUT_ToAgent_VideoRotate_0_svc();
#define VIDEO_RPC_SUBPIC_DEC_ToAgent_EnableSubPicture 5010
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_EnableSubPicture_0();
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_EnableSubPicture_0_svc();
#define VIDEO_RPC_SUBPIC_DEC_ToAgent_ShowSubPicture 5020
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_ShowSubPicture_0();
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_ShowSubPicture_0_svc();
#define VIDEO_RPC_SUBPIC_DEC_ToAgent_HideSubPicture 5030
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_HideSubPicture_0();
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_HideSubPicture_0_svc();
#define VIDEO_RPC_SUBPIC_DEC_ToAgent_Configure 5040
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_Configure_0();
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_Configure_0_svc();
#define VIDEO_RPC_SUBPIC_DEC_ToAgent_Page 5050
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_Page_0();
extern  HRESULT * VIDEO_RPC_SUBPIC_DEC_ToAgent_Page_0_svc();
#define VIDEO_RPC_JPEG_ToAgent_DEC 6010
extern  HRESULT * VIDEO_RPC_JPEG_ToAgent_DEC_0();
extern  HRESULT * VIDEO_RPC_JPEG_ToAgent_DEC_0_svc();
#define VIDEO_RPC_JPEG_ToAgent_DEC_BATCH 6011
extern  HRESULT * VIDEO_RPC_JPEG_ToAgent_DEC_BATCH_0();
extern  HRESULT * VIDEO_RPC_JPEG_ToAgent_DEC_BATCH_0_svc();
#define VIDEO_RPC_TRANSITION_ToAgent_Start 6020
extern  HRESULT * VIDEO_RPC_TRANSITION_ToAgent_Start_0();
extern  HRESULT * VIDEO_RPC_TRANSITION_ToAgent_Start_0_svc();
#define VIDEO_RPC_MIXER_FILTER_ToAgent_Configure 8010
extern  HRESULT * VIDEO_RPC_MIXER_FILTER_ToAgent_Configure_0();
extern  HRESULT * VIDEO_RPC_MIXER_FILTER_ToAgent_Configure_0_svc();
#define VIDEO_RPC_MIXER_FILTER_ToAgent_ConfigureWindow 8020
extern  HRESULT * VIDEO_RPC_MIXER_FILTER_ToAgent_ConfigureWindow_0();
extern  HRESULT * VIDEO_RPC_MIXER_FILTER_ToAgent_ConfigureWindow_0_svc();
#define VIDEO_RPC_MIXER_FILTER_ToAgent_SetMasterWindow 8030
extern  HRESULT * VIDEO_RPC_MIXER_FILTER_ToAgent_SetMasterWindow_0();
extern  HRESULT * VIDEO_RPC_MIXER_FILTER_ToAgent_SetMasterWindow_0_svc();
#define VIDEO_RPC_MIXER_ToAgent_PlayOneMotionJpegFrame 8040
extern  HRESULT * VIDEO_RPC_MIXER_ToAgent_PlayOneMotionJpegFrame_0();
extern  HRESULT * VIDEO_RPC_MIXER_ToAgent_PlayOneMotionJpegFrame_0_svc();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_VIDEO_INIT_DATA (XDR *, VIDEO_INIT_DATA*);
extern  bool_t xdr_VIDEO_CONFIG_DATA (XDR *, VIDEO_CONFIG_DATA*);
extern  bool_t xdr_VIDEO_RPC_INSTANCE (XDR *, VIDEO_RPC_INSTANCE*);
extern  bool_t xdr_VIDEO_RPC_SET_REFCLOCK (XDR *, VIDEO_RPC_SET_REFCLOCK*);
extern  bool_t xdr_VIDEO_RPC_REQUEST_BUFFER (XDR *, VIDEO_RPC_REQUEST_BUFFER*);
extern  bool_t xdr_VIDEO_RPC_FILL_BUFFER (XDR *, VIDEO_RPC_FILL_BUFFER*);
extern  bool_t xdr_VIDEO_RPC_LOW_DELAY (XDR *, VIDEO_RPC_LOW_DELAY*);
extern  bool_t xdr_VIDEO_RPC_DEC_SET_SPEED (XDR *, VIDEO_RPC_DEC_SET_SPEED*);
extern  bool_t xdr_VIDEO_RPC_DEC_SET_ERR_CONCEALMENT_LEVEL (XDR *, VIDEO_RPC_DEC_SET_ERR_CONCEALMENT_LEVEL*);
extern  bool_t xdr_VIDEO_RPC_DEC_INIT (XDR *, VIDEO_RPC_DEC_INIT*);
extern  bool_t xdr_VIDEO_RPC_DEC_SET_DEBLOCK (XDR *, VIDEO_RPC_DEC_SET_DEBLOCK*);
extern  bool_t xdr_VIDEO_RPC_DEC_BITSTREAM_BUFFER (XDR *, VIDEO_RPC_DEC_BITSTREAM_BUFFER*);
extern  bool_t xdr_VIDEO_RPC_DEC_BV_RESULT (XDR *, VIDEO_RPC_DEC_BV_RESULT*);
extern  bool_t xdr_VIDEO_RPC_DEC_SEQ_INFO (XDR *, VIDEO_RPC_DEC_SEQ_INFO*);
extern  bool_t xdr_VIDEO_MEM_CHUNK (XDR *, VIDEO_MEM_CHUNK*);
extern  bool_t xdr_VIDEO_RPC_VIDEO_FREE_MEMORY (XDR *, VIDEO_RPC_VIDEO_FREE_MEMORY*);
extern  bool_t xdr_VIDEO_RPC_CONFIG_CHUNK (XDR *, VIDEO_RPC_CONFIG_CHUNK*);
extern  bool_t xdr_VIDEO_RPC_DEC_CC_BYPASS_MODE (XDR *, VIDEO_RPC_DEC_CC_BYPASS_MODE*);
extern  bool_t xdr_VIDEO_RPC_DEC_SET_DNR (XDR *, VIDEO_RPC_DEC_SET_DNR*);
extern  bool_t xdr_VIDEO_RPC_DEC_SET_REF_SYNC_LIMIT (XDR *, VIDEO_RPC_DEC_SET_REF_SYNC_LIMIT*);
extern  bool_t xdr_VIDEO_RPC_DEC_CAPABILITY (XDR *, VIDEO_RPC_DEC_CAPABILITY*);
extern  bool_t xdr_VIDEO_RPC_THUMBNAIL_SET_VSCALER_OUTFORMAT (XDR *, VIDEO_RPC_THUMBNAIL_SET_VSCALER_OUTFORMAT*);
extern  bool_t xdr_VIDEO_RPC_THUMBNAIL_SET_THRESHOLD (XDR *, VIDEO_RPC_THUMBNAIL_SET_THRESHOLD*);
extern  bool_t xdr_VIDEO_RPC_FLASH_SET_OUTPUT (XDR *, VIDEO_RPC_FLASH_SET_OUTPUT*);
extern  bool_t xdr_VIDEO_RPC_THUMBNAIL_SET_STARTPIC (XDR *, VIDEO_RPC_THUMBNAIL_SET_STARTPIC*);
extern  bool_t xdr_VIDEO_RPC_VOUT_SET_VIDEO_STANDARD (XDR *, VIDEO_RPC_VOUT_SET_VIDEO_STANDARD*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIG_VIDEO_STANDARD (XDR *, VIDEO_RPC_VOUT_CONFIG_VIDEO_STANDARD*);
extern  bool_t xdr_VIDEO_RPC_VOUT_SET_HDMI (XDR *, VIDEO_RPC_VOUT_SET_HDMI*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIG_HDMI (XDR *, VIDEO_RPC_VOUT_CONFIG_HDMI*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIG_HDMI_INFO_FRAME (XDR *, VIDEO_RPC_VOUT_CONFIG_HDMI_INFO_FRAME*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIG_TV_SYSTEM (XDR *, VIDEO_RPC_VOUT_CONFIG_TV_SYSTEM*);
extern  bool_t xdr_VIDEO_RPC_VOUT_ANAGLYPH_CONVERSION (XDR *, VIDEO_RPC_VOUT_ANAGLYPH_CONVERSION*);
extern  bool_t xdr_VIDEO_RPC_VOUT_VIDEO_ROTATE (XDR *, VIDEO_RPC_VOUT_VIDEO_ROTATE*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIG_MACROVISION (XDR *, VIDEO_RPC_VOUT_CONFIG_MACROVISION*);
extern  bool_t xdr_VIDEO_RPC_VOUT_SET_BKGRND (XDR *, VIDEO_RPC_VOUT_SET_BKGRND*);
extern  bool_t xdr_VIDEO_RPC_VOUT_SET_MIXER_ORDER (XDR *, VIDEO_RPC_VOUT_SET_MIXER_ORDER*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIGURE_PLANE_MIXER (XDR *, VIDEO_RPC_VOUT_CONFIGURE_PLANE_MIXER*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIGURE_3D_OFFSET (XDR *, VIDEO_RPC_VOUT_CONFIGURE_3D_OFFSET*);
extern  bool_t xdr_VIDEO_RPC_VOUT_SET_CC (XDR *, VIDEO_RPC_VOUT_SET_CC*);
extern  bool_t xdr_VIDEO_RPC_VOUT_SET_APS (XDR *, VIDEO_RPC_VOUT_SET_APS*);
extern  bool_t xdr_VIDEO_RPC_VOUT_SET_COPY_MODE (XDR *, VIDEO_RPC_VOUT_SET_COPY_MODE*);
extern  bool_t xdr_VIDEO_RPC_VOUT_SET_AR (XDR *, VIDEO_RPC_VOUT_SET_AR*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIG_DISP_WIN (XDR *, VIDEO_RPC_VOUT_CONFIG_DISP_WIN*);
extern  bool_t xdr_VIDEO_RPC_VOUT_DISP_WIN_ANIMATION (XDR *, VIDEO_RPC_VOUT_DISP_WIN_ANIMATION*);
extern  bool_t xdr_VIDEO_RPC_VOUT_SET_RESCALE_MODE (XDR *, VIDEO_RPC_VOUT_SET_RESCALE_MODE*);
extern  bool_t xdr_VIDEO_RPC_VOUT_SET_DEINT_MODE (XDR *, VIDEO_RPC_VOUT_SET_DEINT_MODE*);
extern  bool_t xdr_VIDEO_RPC_VOUT_ZOOM (XDR *, VIDEO_RPC_VOUT_ZOOM*);
extern  bool_t xdr_VIDEO_RPC_VOUT_PAN_ZOOM (XDR *, VIDEO_RPC_VOUT_PAN_ZOOM*);
extern  bool_t xdr_VIDEO_RPC_VOUT_TRANSPARENCY (XDR *, VIDEO_RPC_VOUT_TRANSPARENCY*);
extern  bool_t xdr_VIDEO_RPC_VOUT_ACTUAL_ZOOM (XDR *, VIDEO_RPC_VOUT_ACTUAL_ZOOM*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIG_OSD (XDR *, VIDEO_RPC_VOUT_CONFIG_OSD*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIG_OSD_PALETTE (XDR *, VIDEO_RPC_VOUT_CONFIG_OSD_PALETTE*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CREATE_OSD_WIN (XDR *, VIDEO_RPC_VOUT_CREATE_OSD_WIN*);
extern  bool_t xdr_VIDEO_RPC_VOUT_SET_OSD_WIN_PALETTE (XDR *, VIDEO_RPC_VOUT_SET_OSD_WIN_PALETTE*);
extern  bool_t xdr_VIDEO_RPC_VOUT_MODIFY_OSD_WIN (XDR *, VIDEO_RPC_VOUT_MODIFY_OSD_WIN*);
extern  bool_t xdr_VIDEO_RPC_VOUT_DRAW_OSD_WIN (XDR *, VIDEO_RPC_VOUT_DRAW_OSD_WIN*);
extern  bool_t xdr_VIDEO_RPC_VOUT_HIDE_OSD_WIN (XDR *, VIDEO_RPC_VOUT_HIDE_OSD_WIN*);
extern  bool_t xdr_VIDEO_RPC_VOUT_DELETE_OSD_WIN (XDR *, VIDEO_RPC_VOUT_DELETE_OSD_WIN*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIG_OSD_CANVAS (XDR *, VIDEO_RPC_VOUT_CONFIG_OSD_CANVAS*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIG_CURSOR (XDR *, VIDEO_RPC_VOUT_CONFIG_CURSOR*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIG_MARS_CURSOR (XDR *, VIDEO_RPC_VOUT_CONFIG_MARS_CURSOR*);
extern  bool_t xdr_VIDEO_RPC_VOUT_DRAW_CURSOR (XDR *, VIDEO_RPC_VOUT_DRAW_CURSOR*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIG_COLOR_MATRIX (XDR *, VIDEO_RPC_VOUT_CONFIG_COLOR_MATRIX*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CONFIG_GRAPHIC_CANVAS (XDR *, VIDEO_RPC_VOUT_CONFIG_GRAPHIC_CANVAS*);
extern  bool_t xdr_VIDEO_RPC_VOUT_CREATE_GRAPHIC_WIN (XDR *, VIDEO_RPC_VOUT_CREATE_GRAPHIC_WIN*);
extern  bool_t xdr_VIDEO_RPC_VOUT_MODIFY_GRAPHIC_WIN (XDR *, VIDEO_RPC_VOUT_MODIFY_GRAPHIC_WIN*);
extern  bool_t xdr_VIDEO_RPC_VOUT_DRAW_GRAPHIC_WIN (XDR *, VIDEO_RPC_VOUT_DRAW_GRAPHIC_WIN*);
extern  bool_t xdr_VIDEO_RPC_VOUT_HIDE_GRAPHIC_WIN (XDR *, VIDEO_RPC_VOUT_HIDE_GRAPHIC_WIN*);
extern  bool_t xdr_VIDEO_RPC_VOUT_DELETE_GRAPHIC_WIN (XDR *, VIDEO_RPC_VOUT_DELETE_GRAPHIC_WIN*);
extern  bool_t xdr_VIDEO_RPC_VOUT_DISPLAY_GRAPHIC_WIN (XDR *, VIDEO_RPC_VOUT_DISPLAY_GRAPHIC_WIN*);
extern  bool_t xdr_VIDEO_RPC_VOUT_DISPLAY_GRAPHIC (XDR *, VIDEO_RPC_VOUT_DISPLAY_GRAPHIC*);
extern  bool_t xdr_VIDEO_RPC_VOUT_VIDEO_CAPTURE (XDR *, VIDEO_RPC_VOUT_VIDEO_CAPTURE*);
extern  bool_t xdr_VIDEO_RPC_VO_FILTER_DISPLAY (XDR *, VIDEO_RPC_VO_FILTER_DISPLAY*);
extern  bool_t xdr_VIDEO_RPC_VO_FILTER_HIDE (XDR *, VIDEO_RPC_VO_FILTER_HIDE*);
extern  bool_t xdr_VIDEO_RPC_VO_FILTER_DISP_BD_COLOR (XDR *, VIDEO_RPC_VO_FILTER_DISP_BD_COLOR*);
extern  bool_t xdr_VIDEO_RPC_VO_FILTER_SET_SPEED (XDR *, VIDEO_RPC_VO_FILTER_SET_SPEED*);
extern  bool_t xdr_VIDEO_RPC_VO_FILTER_SHOW_STILL_PIC (XDR *, VIDEO_RPC_VO_FILTER_SHOW_STILL_PIC*);
extern  bool_t xdr_VIDEO_RPC_VO_FILTER_FILL_VIDEO_BORDER (XDR *, VIDEO_RPC_VO_FILTER_FILL_VIDEO_BORDER*);
extern  bool_t xdr_VIDEO_RPC_VO_FILTER_SET_FAST_DISPLAY (XDR *, VIDEO_RPC_VO_FILTER_SET_FAST_DISPLAY*);
extern  bool_t xdr_VIDEO_RPC_VO_FILTER_CAPTURE (XDR *, VIDEO_RPC_VO_FILTER_CAPTURE*);
extern  bool_t xdr_VIDEO_RPC_SUBPIC_DEC_ENABLE_SUBPIC (XDR *, VIDEO_RPC_SUBPIC_DEC_ENABLE_SUBPIC*);
extern  bool_t xdr_VIDEO_RPC_SUBPIC_DEC_CONFIGURE (XDR *, VIDEO_RPC_SUBPIC_DEC_CONFIGURE*);
extern  bool_t xdr_VIDEO_RPC_SUBPIC_DEC_PAGE (XDR *, VIDEO_RPC_SUBPIC_DEC_PAGE*);
extern  bool_t xdr_VIDEO_RPC_JPEG_DEC (XDR *, VIDEO_RPC_JPEG_DEC*);
extern  bool_t xdr_VIDEO_RPC_JPEG_DEC_BATCH (XDR *, VIDEO_RPC_JPEG_DEC_BATCH*);
extern  bool_t xdr_VIDEO_RPC_TRANSITION_EFFECT (XDR *, VIDEO_RPC_TRANSITION_EFFECT*);
extern  bool_t xdr_VIDEO_RPC_MIXER_FILTER_CONFIGURE (XDR *, VIDEO_RPC_MIXER_FILTER_CONFIGURE*);
extern  bool_t xdr_VIDEO_RPC_MIXER_FILTER_CONFIGURE_WIN (XDR *, VIDEO_RPC_MIXER_FILTER_CONFIGURE_WIN*);
extern  bool_t xdr_VIDEO_RPC_MIXER_FILTER_SET_MASTER_WIN (XDR *, VIDEO_RPC_MIXER_FILTER_SET_MASTER_WIN*);
extern  bool_t xdr_VIDEO_RPC_MIXER_PLAY_ONE_MOTION_JPEG_FRAME (XDR *, VIDEO_RPC_MIXER_PLAY_ONE_MOTION_JPEG_FRAME*);
extern  bool_t xdr_VIDEO_RPC_DEBUG_MEMORY (XDR *, VIDEO_RPC_DEBUG_MEMORY*);
extern  bool_t xdr_VIDEO_RPC_YUYV_TO_RGB (XDR *, VIDEO_RPC_YUYV_TO_RGB*);

#else /* K&R C */
extern bool_t xdr_VIDEO_INIT_DATA ();
extern bool_t xdr_VIDEO_CONFIG_DATA ();
extern bool_t xdr_VIDEO_RPC_INSTANCE ();
extern bool_t xdr_VIDEO_RPC_SET_REFCLOCK ();
extern bool_t xdr_VIDEO_RPC_REQUEST_BUFFER ();
extern bool_t xdr_VIDEO_RPC_FILL_BUFFER ();
extern bool_t xdr_VIDEO_RPC_LOW_DELAY ();
extern bool_t xdr_VIDEO_RPC_DEC_SET_SPEED ();
extern bool_t xdr_VIDEO_RPC_DEC_SET_ERR_CONCEALMENT_LEVEL ();
extern bool_t xdr_VIDEO_RPC_DEC_INIT ();
extern bool_t xdr_VIDEO_RPC_DEC_SET_DEBLOCK ();
extern bool_t xdr_VIDEO_RPC_DEC_BITSTREAM_BUFFER ();
extern bool_t xdr_VIDEO_RPC_DEC_BV_RESULT ();
extern bool_t xdr_VIDEO_RPC_DEC_SEQ_INFO ();
extern bool_t xdr_VIDEO_MEM_CHUNK ();
extern bool_t xdr_VIDEO_RPC_VIDEO_FREE_MEMORY ();
extern bool_t xdr_VIDEO_RPC_CONFIG_CHUNK ();
extern bool_t xdr_VIDEO_RPC_DEC_CC_BYPASS_MODE ();
extern bool_t xdr_VIDEO_RPC_DEC_SET_DNR ();
extern bool_t xdr_VIDEO_RPC_DEC_SET_REF_SYNC_LIMIT ();
extern bool_t xdr_VIDEO_RPC_DEC_CAPABILITY ();
extern bool_t xdr_VIDEO_RPC_THUMBNAIL_SET_VSCALER_OUTFORMAT ();
extern bool_t xdr_VIDEO_RPC_THUMBNAIL_SET_THRESHOLD ();
extern bool_t xdr_VIDEO_RPC_FLASH_SET_OUTPUT ();
extern bool_t xdr_VIDEO_RPC_THUMBNAIL_SET_STARTPIC ();
extern bool_t xdr_VIDEO_RPC_VOUT_SET_VIDEO_STANDARD ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIG_VIDEO_STANDARD ();
extern bool_t xdr_VIDEO_RPC_VOUT_SET_HDMI ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIG_HDMI ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIG_HDMI_INFO_FRAME ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIG_TV_SYSTEM ();
extern bool_t xdr_VIDEO_RPC_VOUT_ANAGLYPH_CONVERSION ();
extern bool_t xdr_VIDEO_RPC_VOUT_VIDEO_ROTATE ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIG_MACROVISION ();
extern bool_t xdr_VIDEO_RPC_VOUT_SET_BKGRND ();
extern bool_t xdr_VIDEO_RPC_VOUT_SET_MIXER_ORDER ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIGURE_PLANE_MIXER ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIGURE_3D_OFFSET ();
extern bool_t xdr_VIDEO_RPC_VOUT_SET_CC ();
extern bool_t xdr_VIDEO_RPC_VOUT_SET_APS ();
extern bool_t xdr_VIDEO_RPC_VOUT_SET_COPY_MODE ();
extern bool_t xdr_VIDEO_RPC_VOUT_SET_AR ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIG_DISP_WIN ();
extern bool_t xdr_VIDEO_RPC_VOUT_DISP_WIN_ANIMATION ();
extern bool_t xdr_VIDEO_RPC_VOUT_SET_RESCALE_MODE ();
extern bool_t xdr_VIDEO_RPC_VOUT_SET_DEINT_MODE ();
extern bool_t xdr_VIDEO_RPC_VOUT_ZOOM ();
extern bool_t xdr_VIDEO_RPC_VOUT_PAN_ZOOM ();
extern bool_t xdr_VIDEO_RPC_VOUT_TRANSPARENCY ();
extern bool_t xdr_VIDEO_RPC_VOUT_ACTUAL_ZOOM ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIG_OSD ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIG_OSD_PALETTE ();
extern bool_t xdr_VIDEO_RPC_VOUT_CREATE_OSD_WIN ();
extern bool_t xdr_VIDEO_RPC_VOUT_SET_OSD_WIN_PALETTE ();
extern bool_t xdr_VIDEO_RPC_VOUT_MODIFY_OSD_WIN ();
extern bool_t xdr_VIDEO_RPC_VOUT_DRAW_OSD_WIN ();
extern bool_t xdr_VIDEO_RPC_VOUT_HIDE_OSD_WIN ();
extern bool_t xdr_VIDEO_RPC_VOUT_DELETE_OSD_WIN ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIG_OSD_CANVAS ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIG_CURSOR ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIG_MARS_CURSOR ();
extern bool_t xdr_VIDEO_RPC_VOUT_DRAW_CURSOR ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIG_COLOR_MATRIX ();
extern bool_t xdr_VIDEO_RPC_VOUT_CONFIG_GRAPHIC_CANVAS ();
extern bool_t xdr_VIDEO_RPC_VOUT_CREATE_GRAPHIC_WIN ();
extern bool_t xdr_VIDEO_RPC_VOUT_MODIFY_GRAPHIC_WIN ();
extern bool_t xdr_VIDEO_RPC_VOUT_DRAW_GRAPHIC_WIN ();
extern bool_t xdr_VIDEO_RPC_VOUT_HIDE_GRAPHIC_WIN ();
extern bool_t xdr_VIDEO_RPC_VOUT_DELETE_GRAPHIC_WIN ();
extern bool_t xdr_VIDEO_RPC_VOUT_DISPLAY_GRAPHIC_WIN ();
extern bool_t xdr_VIDEO_RPC_VOUT_DISPLAY_GRAPHIC ();
extern bool_t xdr_VIDEO_RPC_VOUT_VIDEO_CAPTURE ();
extern bool_t xdr_VIDEO_RPC_VO_FILTER_DISPLAY ();
extern bool_t xdr_VIDEO_RPC_VO_FILTER_HIDE ();
extern bool_t xdr_VIDEO_RPC_VO_FILTER_DISP_BD_COLOR ();
extern bool_t xdr_VIDEO_RPC_VO_FILTER_SET_SPEED ();
extern bool_t xdr_VIDEO_RPC_VO_FILTER_SHOW_STILL_PIC ();
extern bool_t xdr_VIDEO_RPC_VO_FILTER_FILL_VIDEO_BORDER ();
extern bool_t xdr_VIDEO_RPC_VO_FILTER_SET_FAST_DISPLAY ();
extern bool_t xdr_VIDEO_RPC_VO_FILTER_CAPTURE ();
extern bool_t xdr_VIDEO_RPC_SUBPIC_DEC_ENABLE_SUBPIC ();
extern bool_t xdr_VIDEO_RPC_SUBPIC_DEC_CONFIGURE ();
extern bool_t xdr_VIDEO_RPC_SUBPIC_DEC_PAGE ();
extern bool_t xdr_VIDEO_RPC_JPEG_DEC ();
extern bool_t xdr_VIDEO_RPC_JPEG_DEC_BATCH ();
extern bool_t xdr_VIDEO_RPC_TRANSITION_EFFECT ();
extern bool_t xdr_VIDEO_RPC_MIXER_FILTER_CONFIGURE ();
extern bool_t xdr_VIDEO_RPC_MIXER_FILTER_CONFIGURE_WIN ();
extern bool_t xdr_VIDEO_RPC_MIXER_FILTER_SET_MASTER_WIN ();
extern bool_t xdr_VIDEO_RPC_MIXER_PLAY_ONE_MOTION_JPEG_FRAME ();
extern bool_t xdr_VIDEO_RPC_DEBUG_MEMORY ();
extern bool_t xdr_VIDEO_RPC_YUYV_TO_RGB ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VIDEORPC_SYSTEM_H_RPCGEN */
