obj-$(CONFIG_COMMON_CLK_REALTEK) += clk-rtk.o
obj-$(CONFIG_COMMON_CLK_RTD129X) += clk-rtd129x.o
obj-$(CONFIG_COMMON_CLK_RTD139X) += clk-rtd139x.o

clk-rtk-y += clk-mmio-mux.o
clk-rtk-y += clk-mmio-gate.o
clk-rtk-y += clk-pll.o
clk-rtk-y += cgc.o
clk-rtk-y += reset.o

clk-rtd129x-y += cc-rtd129x.o

