/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AUDIORPC_SYSTEM_H_RPCGEN
#define _AUDIORPC_SYSTEM_H_RPCGEN

#include <rt/misc/RPCstruct.h>

#include "AudioRPC_System_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#define printf(str)

#include <RPCBaseDS.h>
#include <AudioRPCBaseDS.h>

#define AUDIO_SYSTEM 201
#define VERSION 0

struct REG_STRUCT * AUDIO_SYSTEM_0_register(struct REG_STRUCT *rnode);

#if defined(__STDC__) || defined(__cplusplus)
#define AUDIO_RPC_ToAgent_Create 1
extern  RPCRES_LONG * AUDIO_RPC_ToAgent_Create_0(AUDIO_RPC_INSTANCE *, CLNT_STRUCT *);
extern  RPCRES_LONG * AUDIO_RPC_ToAgent_Create_0_svc(AUDIO_RPC_INSTANCE *, RPC_STRUCT *, RPCRES_LONG *);
#define AUDIO_RPC_ToAgent_Connect 2
extern  HRESULT * AUDIO_RPC_ToAgent_Connect_0(AUDIO_RPC_CONNECTION *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_Connect_0_svc(AUDIO_RPC_CONNECTION *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_InitRingBufferHeader 3
extern  HRESULT * AUDIO_RPC_ToAgent_InitRingBufferHeader_0(AUDIO_RPC_RINGBUFFER_HEADER *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_InitRingBufferHeader_0_svc(AUDIO_RPC_RINGBUFFER_HEADER *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_Run 4
extern  HRESULT * AUDIO_RPC_ToAgent_Run_0(long *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_Run_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_Pause 5
extern  HRESULT * AUDIO_RPC_ToAgent_Pause_0(long *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_Pause_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_Stop 6
extern  HRESULT * AUDIO_RPC_ToAgent_Stop_0(long *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_Stop_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_Destroy 7
extern  HRESULT * AUDIO_RPC_ToAgent_Destroy_0(long *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_Destroy_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_Flush 8
extern  HRESULT * AUDIO_RPC_ToAgent_Flush_0(AUDIO_RPC_SENDIO *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_Flush_0_svc(AUDIO_RPC_SENDIO *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_SetRefClock 9
extern  HRESULT * AUDIO_RPC_ToAgent_SetRefClock_0(AUDIO_RPC_REFCLOCK *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_SetRefClock_0_svc(AUDIO_RPC_REFCLOCK *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_GetStatus 10
extern  RPCRES_LONG * AUDIO_RPC_ToAgent_GetStatus_0(AUDIO_RPC_SEND_LONG *, CLNT_STRUCT *);
extern  RPCRES_LONG * AUDIO_RPC_ToAgent_GetStatus_0_svc(AUDIO_RPC_SEND_LONG *, RPC_STRUCT *, RPCRES_LONG *);
#define AUDIO_RPC_ToAgent_SetSeeking 11
extern  HRESULT * AUDIO_RPC_ToAgent_SetSeeking_0(AUDIO_RPC_SEEK *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_SetSeeking_0_svc(AUDIO_RPC_SEEK *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_BitstreamValidation 15
extern  AUDIO_RPC_FORMAT_INFO * AUDIO_RPC_ToAgent_BitstreamValidation_0(AUDIO_RPC_DEC_BITSTREAM_BUFFER *, CLNT_STRUCT *);
extern  AUDIO_RPC_FORMAT_INFO * AUDIO_RPC_ToAgent_BitstreamValidation_0_svc(AUDIO_RPC_DEC_BITSTREAM_BUFFER *, RPC_STRUCT *, AUDIO_RPC_FORMAT_INFO *);
#define AUDIO_RPC_ToAgent_AudioConfig 16
extern  HRESULT * AUDIO_RPC_ToAgent_AudioConfig_0(AUDIO_CONFIG_COMMAND *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AudioConfig_0_svc(AUDIO_CONFIG_COMMAND *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_DEC_ToAgent_Init 31
extern  HRESULT * AUDIO_RPC_DEC_ToAgent_Init_0(AUDIO_RPC_DEC_INIT *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_DEC_ToAgent_Init_0_svc(AUDIO_RPC_DEC_INIT *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_DEC_ToAgent_SkipMode 32
extern  HRESULT * AUDIO_RPC_DEC_ToAgent_SkipMode_0(AUDIO_RPC_SEND_LONG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_DEC_ToAgent_SkipMode_0_svc(AUDIO_RPC_SEND_LONG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ENC_ToAgent_Init 51
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_Init_0(AUDIO_RPC_ENC_INIT *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_Init_0_svc(AUDIO_RPC_ENC_INIT *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ENC_ToAgent_SetBitRate 52
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetBitRate_0(AUDIO_RPC_ENC_SET_BITRATE *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetBitRate_0_svc(AUDIO_RPC_ENC_SET_BITRATE *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ENC_ToAgent_StartEncoder 53
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_StartEncoder_0(AUDIO_RPC_SEND_LONG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_StartEncoder_0_svc(AUDIO_RPC_SEND_LONG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ENC_ToAgent_PauseEncoder 54
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_PauseEncoder_0(AUDIO_RPC_SEND_LONG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_PauseEncoder_0_svc(AUDIO_RPC_SEND_LONG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ENC_ToAgent_StopEncoder 55
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_StopEncoder_0(AUDIO_RPC_SEND_LONG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_StopEncoder_0_svc(AUDIO_RPC_SEND_LONG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ENC_ToAgent_SetSourceFile 56
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetSourceFile_0(AUDIO_RPC_ENC_SOURCEFILE *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetSourceFile_0_svc(AUDIO_RPC_ENC_SOURCEFILE *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ENC_ToAgent_Command 57
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_Command_0(AUDIO_RPC_ENC_COMMAND *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_Command_0_svc(AUDIO_RPC_ENC_COMMAND *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ENC_ToAgent_MuteEncoder 58
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_MuteEncoder_0(AUDIO_RPC_SEND_LONG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_MuteEncoder_0_svc(AUDIO_RPC_SEND_LONG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ENC_SetEncoder 59
extern  HRESULT * AUDIO_RPC_ENC_SetEncoder_0(AUDIO_RPC_ENC_INFO *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ENC_SetEncoder_0_svc(AUDIO_RPC_ENC_INFO *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ENC_ToAgent_SetDVMixer 60
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetDVMixer_0(AUDIO_RPC_ENC_DV_MIXER *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetDVMixer_0_svc(AUDIO_RPC_ENC_DV_MIXER *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ENC_ToAgent_SetNonRealTime 61
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetNonRealTime_0(AUDIO_RPC_SEND_LONG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetNonRealTime_0_svc(AUDIO_RPC_SEND_LONG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_AO_ToAgent_Init 81
extern  HRESULT * AUDIO_RPC_AO_ToAgent_Init_0(AUDIO_RPC_AO_INIT *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_AO_ToAgent_Init_0_svc(AUDIO_RPC_AO_INIT *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_AO_ToAgent_SetEaqualizer 82
extern  HRESULT * AUDIO_RPC_AO_ToAgent_SetEaqualizer_0(AUDIO_RPC_AO_SET_EQUALIZER *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_AO_ToAgent_SetEaqualizer_0_svc(AUDIO_RPC_AO_SET_EQUALIZER *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_AO_ToAgent_ConfigDelayControl 83
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigDelayControl_0(AUDIO_AO_RPC_CONFIG_DELAY_CONTROL *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigDelayControl_0_svc(AUDIO_AO_RPC_CONFIG_DELAY_CONTROL *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_AO_ToAgent_ConfigKaraoke 84
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigKaraoke_0(AUDIO_RPC_AO_CONFIG_KARAOKE *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigKaraoke_0_svc(AUDIO_RPC_AO_CONFIG_KARAOKE *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_AO_ToAgent_ConfigMixer 85
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigMixer_0(AUDIO_RPC_AO_MIXER *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigMixer_0_svc(AUDIO_RPC_AO_MIXER *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_AO_ToAgent_ConfigPP 86
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigPP_0(AUDIO_RPC_PP_CFG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigPP_0_svc(AUDIO_RPC_PP_CFG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_AO_ToAgent_Mute 87
extern  HRESULT * AUDIO_RPC_AO_ToAgent_Mute_0(AUDIO_OUT_MUTE_INFO *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_AO_ToAgent_Mute_0_svc(AUDIO_OUT_MUTE_INFO *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_AO_ToAgent_ConfigDAC 88
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigDAC_0(AUDIO_RPC_AO_DAC *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigDAC_0_svc(AUDIO_RPC_AO_DAC *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_AO_ToAgent_ConfigPrologic 89
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigPrologic_0(AUDIO_RPC_PP_PROLOGIC *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigPrologic_0_svc(AUDIO_RPC_PP_PROLOGIC *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_ADC0_Config 110
extern  HRESULT * AUDIO_RPC_ToAgent_ADC0_Config_0(AUDIO_CONFIG_ADC *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_ADC0_Config_0_svc(AUDIO_CONFIG_ADC *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_ADC1_Config 111
extern  HRESULT * AUDIO_RPC_ToAgent_ADC1_Config_0(AUDIO_CONFIG_ADC *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_ADC1_Config_0_svc(AUDIO_CONFIG_ADC *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_SPDIF_Config 112
extern  HRESULT * AUDIO_RPC_ToAgent_SPDIF_Config_0(AUDIO_CONFIG_SPDIF *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_SPDIF_Config_0_svc(AUDIO_CONFIG_SPDIF *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AI_BackDoor_Init 113
extern  HRESULT * AUDIO_RPC_ToAgent_AI_BackDoor_Init_0(AUDIO_BACKDOOR_AI_INIT *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AI_BackDoor_Init_0_svc(AUDIO_BACKDOOR_AI_INIT *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_SPDIF_Err_Threshold_Config 114
extern  HRESULT * AUDIO_RPC_ToAgent_SPDIF_Err_Threshold_Config_0(AUDIO_CONFIG_SPDIF_ERR *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_SPDIF_Err_Threshold_Config_0_svc(AUDIO_CONFIG_SPDIF_ERR *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AIN_Switch_Focus 115
extern  HRESULT * AUDIO_RPC_ToAgent_AIN_Switch_Focus_0(AUDIO_IN_SOURCE *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AIN_Switch_Focus_0_svc(AUDIO_IN_SOURCE *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AOUT_Copy_Source 116
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Copy_Source_0(AUDIO_OUT_COPY_SOURCE *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Copy_Source_0_svc(AUDIO_OUT_COPY_SOURCE *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AOUT_Volume_Control 117
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Volume_Control_0(AUDIO_VOLUME_CONTROL *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Volume_Control_0_svc(AUDIO_VOLUME_CONTROL *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AOUT_SPDIF_Source 118
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_SPDIF_Source_0(AUDIO_OUT_SPDIF_SOURCE *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_SPDIF_Source_0_svc(AUDIO_OUT_SPDIF_SOURCE *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_Karaoke_Control 119
extern  HRESULT * AUDIO_RPC_ToAgent_Karaoke_Control_0(AUDIO_KARAOKE_CONTROL_INFO *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_Karaoke_Control_0_svc(AUDIO_KARAOKE_CONTROL_INFO *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AIN_Mute 120
extern  HRESULT * AUDIO_RPC_ToAgent_AIN_Mute_0(AUDIO_IN_MUTE_INFO *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AIN_Mute_0_svc(AUDIO_IN_MUTE_INFO *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AOUT_Drop_Sample 121
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Drop_Sample_0(AUDIO_DROP_SAMPLE *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Drop_Sample_0_svc(AUDIO_DROP_SAMPLE *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AOUT_Pink_White_Noise 122
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Pink_White_Noise_0(AUDIO_P_W_NOISE_CFG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Pink_White_Noise_0_svc(AUDIO_P_W_NOISE_CFG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AOUT_Send_Spectrum_Data 123
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Send_Spectrum_Data_0(AUDIO_SPECTRUM_CFG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Send_Spectrum_Data_0_svc(AUDIO_SPECTRUM_CFG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_PlaySoundEvent 125
extern  HRESULT * AUDIO_RPC_ToAgent_PlaySoundEvent_0(AUDIO_SOUND_EVENT *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_PlaySoundEvent_0_svc(AUDIO_SOUND_EVENT *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AOUT_ResetPin 126
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_ResetPin_0(long *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_ResetPin_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AFC_Config 127
extern  HRESULT * AUDIO_RPC_ToAgent_AFC_Config_0(AUDIO_CONFIG_AFC *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AFC_Config_0_svc(AUDIO_CONFIG_AFC *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_Audistry_Config 128
extern  HRESULT * AUDIO_RPC_ToAgent_Audistry_Config_0(AUDISTRY_CONFIG_COMMAND *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_Audistry_Config_0_svc(AUDISTRY_CONFIG_COMMAND *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_HDMI_Mute 129
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_Mute_0(AUDIO_HDMI_MUTE_INFO *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_Mute_0_svc(AUDIO_HDMI_MUTE_INFO *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_ADC2_Config 130
extern  HRESULT * AUDIO_RPC_ToAgent_ADC2_Config_0(AUDIO_CONFIG_ADC *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_ADC2_Config_0_svc(AUDIO_CONFIG_ADC *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AOUT_HDMI_Set 131
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_HDMI_Set_0(AUDIO_HDMI_SET *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_HDMI_Set_0_svc(AUDIO_HDMI_SET *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AO_Only_Switchfocus 132
extern  HRESULT * AUDIO_RPC_ToAgent_AO_Only_Switchfocus_0(AUDIO_RPC_AO_FOCUS *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AO_Only_Switchfocus_0_svc(AUDIO_RPC_AO_FOCUS *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AIN_Data_Measurement 133
extern  HRESULT * AUDIO_RPC_ToAgent_AIN_Data_Measurement_0(AUDIO_IN_DATA_MEASURE *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AIN_Data_Measurement_0_svc(AUDIO_IN_DATA_MEASURE *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_SET_CHANNEL_OUT_SWAP 134
extern  HRESULT * AUDIO_RPC_ToAgent_SET_CHANNEL_OUT_SWAP_0(AUDIO_RPC_AO_CHANNEL_OPT_SWAP *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_SET_CHANNEL_OUT_SWAP_0_svc(AUDIO_RPC_AO_CHANNEL_OPT_SWAP *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_HDMI_OUT_EDID 200
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_OUT_EDID_0(AUDIO_HDMI_OUT_EDID_DATA *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_OUT_EDID_0_svc(AUDIO_HDMI_OUT_EDID_DATA *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_HDMI_INFO 201
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_INFO_0(HDMI_INFO *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_INFO_0_svc(HDMI_INFO *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_UpdatePTS 203
extern  HRESULT * AUDIO_RPC_ToAgent_UpdatePTS_0(AUDIO_RPC_PTS_INFO *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_UpdatePTS_0_svc(AUDIO_RPC_PTS_INFO *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_EndOfStream 204
extern  HRESULT * AUDIO_RPC_ToAgent_EndOfStream_0(AUDIO_RPC_SENDPIN_LONG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_EndOfStream_0_svc(AUDIO_RPC_SENDPIN_LONG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_SwitchFocus 205
extern  HRESULT * AUDIO_RPC_ToAgent_SwitchFocus_0(AUDIO_RPC_FOCUS *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_SwitchFocus_0_svc(AUDIO_RPC_FOCUS *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_DAC_I2S_Config 206
extern  HRESULT * AUDIO_RPC_ToAgent_DAC_I2S_Config_0(AUDIO_CONFIG_DAC_I2S *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_DAC_I2S_Config_0_svc(AUDIO_CONFIG_DAC_I2S *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_DAC_SPDIF_Config 207
extern  HRESULT * AUDIO_RPC_ToAgent_DAC_SPDIF_Config_0(AUDIO_CONFIG_DAC_SPDIF *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_DAC_SPDIF_Config_0_svc(AUDIO_CONFIG_DAC_SPDIF *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_HDMI_OUT_VSDB 208
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_OUT_VSDB_0(AUDIO_HDMI_OUT_VSDB_DATA *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_OUT_VSDB_0_svc(AUDIO_HDMI_OUT_VSDB_DATA *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_HDMI_OUT_EDID2 209
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_OUT_EDID2_0(AUDIO_HDMI_OUT_EDID_DATA2 *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_OUT_EDID2_0_svc(AUDIO_HDMI_OUT_EDID_DATA2 *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_DecoderConfig 212
extern  HRESULT * AUDIO_RPC_ToAgent_DecoderConfig_0(AUDIO_RPC_DECCFG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_DecoderConfig_0_svc(AUDIO_RPC_DECCFG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_NightMode 213
extern  HRESULT * AUDIO_RPC_ToAgent_NightMode_0(AUDIO_RPC_NIGHTMODE *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_NightMode_0_svc(AUDIO_RPC_NIGHTMODE *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_PP_InitPin 214
extern  HRESULT * AUDIO_RPC_ToAgent_PP_InitPin_0(long *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_PP_InitPin_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_TrueHD_LosslessMode 228
extern  HRESULT * AUDIO_RPC_ToAgent_TrueHD_LosslessMode_0(AUDIO_RPC_TRUEHD_LOSSLESSMODE *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_TrueHD_LosslessMode_0_svc(AUDIO_RPC_TRUEHD_LOSSLESSMODE *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AskDebugMemoryAddress 215
extern  HRESULT * AUDIO_RPC_ToAgent_AskDebugMemoryAddress_0(u_long *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AskDebugMemoryAddress_0_svc(u_long *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_PP_Config 216
extern  HRESULT * AUDIO_RPC_ToAgent_PP_Config_0(AUDIO_PP_CONFIG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_PP_Config_0_svc(AUDIO_PP_CONFIG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_PP_SRC_Config 217
extern  HRESULT * AUDIO_RPC_ToAgent_PP_SRC_Config_0(AUDIO_SRC_CONFIG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_PP_SRC_Config_0_svc(AUDIO_SRC_CONFIG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_PP_PL2_Config 218
extern  HRESULT * AUDIO_RPC_ToAgent_PP_PL2_Config_0(AUDIO_PROLOGIC2_CONFIG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_PP_PL2_Config_0_svc(AUDIO_PROLOGIC2_CONFIG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_PP_MIXER_Config 219
extern  HRESULT * AUDIO_RPC_ToAgent_PP_MIXER_Config_0(AUDIO_MIXER_CONFIG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_PP_MIXER_Config_0_svc(AUDIO_MIXER_CONFIG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_PP_BASS_MANAGEMENT_Config 220
extern  HRESULT * AUDIO_RPC_ToAgent_PP_BASS_MANAGEMENT_Config_0(AUDIO_BASS_MANAGEMENT_CONFIG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_PP_BASS_MANAGEMENT_Config_0_svc(AUDIO_BASS_MANAGEMENT_CONFIG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_PP_KEY_SHIFT_Config 221
extern  HRESULT * AUDIO_RPC_ToAgent_PP_KEY_SHIFT_Config_0(AUDIO_KEY_SHIFT_CONFIG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_PP_KEY_SHIFT_Config_0_svc(AUDIO_KEY_SHIFT_CONFIG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_PP_REVERB_Config 222
extern  HRESULT * AUDIO_RPC_ToAgent_PP_REVERB_Config_0(AUDIO_REVERB_CONFIG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_PP_REVERB_Config_0_svc(AUDIO_REVERB_CONFIG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_PP_COMFORT_LISTEN 223
extern  HRESULT * AUDIO_RPC_ToAgent_PP_COMFORT_LISTEN_0(AUDIO_AGC_MODE *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_PP_COMFORT_LISTEN_0_svc(AUDIO_AGC_MODE *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_PP_EQ_Config 224
extern  HRESULT * AUDIO_RPC_ToAgent_PP_EQ_Config_0(AUDIO_EQUALIZER_CONFIG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_PP_EQ_Config_0_svc(AUDIO_EQUALIZER_CONFIG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_PP_VOCAL_REMOVER_Config 225
extern  HRESULT * AUDIO_RPC_ToAgent_PP_VOCAL_REMOVER_Config_0(AUDIO_VOCAL_REMOVER_CONFIG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_PP_VOCAL_REMOVER_Config_0_svc(AUDIO_VOCAL_REMOVER_CONFIG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_DEC_ToAgent_GetAudioFormatInfo 226
extern  AUDIO_RPC_DEC_FORMAT_INFO * AUDIO_RPC_DEC_ToAgent_GetAudioFormatInfo_0(long *, CLNT_STRUCT *);
extern  AUDIO_RPC_DEC_FORMAT_INFO * AUDIO_RPC_DEC_ToAgent_GetAudioFormatInfo_0_svc(long *, RPC_STRUCT *, AUDIO_RPC_DEC_FORMAT_INFO *);
#define AUDIO_RPC_ToAgent_PP_DVS_Config 227
extern  HRESULT * AUDIO_RPC_ToAgent_PP_DVS_Config_0(AUDIO_DVS_CONFIG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_PP_DVS_Config_0_svc(AUDIO_DVS_CONFIG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_Karaoke_Scoring 229
extern  HRESULT * AUDIO_RPC_ToAgent_Karaoke_Scoring_0(AUDIO_KARAOKE_SCORING_CONFIG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_Karaoke_Scoring_0_svc(AUDIO_KARAOKE_SCORING_CONFIG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_DEC_SetCodecKey 230
extern  HRESULT * AUDIO_RPC_ToAgent_DEC_SetCodecKey_0(AUDIO_CODEC_KEY_INFO *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_DEC_SetCodecKey_0_svc(AUDIO_CODEC_KEY_INFO *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_Capability_SetMask 250
extern  HRESULT * AUDIO_RPC_ToAgent_Capability_SetMask_0(long *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_Capability_SetMask_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AudioHalt 251
extern  HRESULT * AUDIO_RPC_ToAgent_AudioHalt_0(long *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_AudioHalt_0_svc(long *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_Full_Capability_SetMask 252
extern  HRESULT * AUDIO_RPC_ToAgent_Full_Capability_SetMask_0(AUDIO_LICENSE_STATUS_CONFIG *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_Full_Capability_SetMask_0_svc(AUDIO_LICENSE_STATUS_CONFIG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_PrivateInfo 253
extern  AUDIO_RPC_PRIVATEINFO_RETURNVAL * AUDIO_RPC_ToAgent_PrivateInfo_0(AUDIO_RPC_PRIVATEINFO_PARAMETERS *, CLNT_STRUCT *);
extern  AUDIO_RPC_PRIVATEINFO_RETURNVAL * AUDIO_RPC_ToAgent_PrivateInfo_0_svc(AUDIO_RPC_PRIVATEINFO_PARAMETERS *, RPC_STRUCT *, AUDIO_RPC_PRIVATEINFO_RETURNVAL *);
#define AUDIO_RPC_ToAgent_Capability_SetPassThroughMode 254
extern  HRESULT * AUDIO_RPC_ToAgent_Capability_SetPassThroughMode_0(AUDIO_PASSTHROUGH_INFO *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_Capability_SetPassThroughMode_0_svc(AUDIO_PASSTHROUGH_INFO *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AI_Device_USBinfo 255
extern  USB_DEVICE_CONFIG_INFO * AUDIO_RPC_ToAgent_AI_Device_USBinfo_0(AUDIO_AI_DEVICE_USB_INFO *, CLNT_STRUCT *);
extern  USB_DEVICE_CONFIG_INFO * AUDIO_RPC_ToAgent_AI_Device_USBinfo_0_svc(AUDIO_AI_DEVICE_USB_INFO *, RPC_STRUCT *, USB_DEVICE_CONFIG_INFO *);
#define AUDIO_RPC_ToAgent_Set_Dummy_Value 300
extern  HRESULT * AUDIO_RPC_ToAgent_Set_Dummy_Value_0(AUDIO_DUMMY_DATA *, CLNT_STRUCT *);
extern  HRESULT * AUDIO_RPC_ToAgent_Set_Dummy_Value_0_svc(AUDIO_DUMMY_DATA *, RPC_STRUCT *, HRESULT *);

#else /* K&R C */
#define AUDIO_RPC_ToAgent_Create 1
extern  RPCRES_LONG * AUDIO_RPC_ToAgent_Create_0();
extern  RPCRES_LONG * AUDIO_RPC_ToAgent_Create_0_svc();
#define AUDIO_RPC_ToAgent_Connect 2
extern  HRESULT * AUDIO_RPC_ToAgent_Connect_0();
extern  HRESULT * AUDIO_RPC_ToAgent_Connect_0_svc();
#define AUDIO_RPC_ToAgent_InitRingBufferHeader 3
extern  HRESULT * AUDIO_RPC_ToAgent_InitRingBufferHeader_0();
extern  HRESULT * AUDIO_RPC_ToAgent_InitRingBufferHeader_0_svc();
#define AUDIO_RPC_ToAgent_Run 4
extern  HRESULT * AUDIO_RPC_ToAgent_Run_0();
extern  HRESULT * AUDIO_RPC_ToAgent_Run_0_svc();
#define AUDIO_RPC_ToAgent_Pause 5
extern  HRESULT * AUDIO_RPC_ToAgent_Pause_0();
extern  HRESULT * AUDIO_RPC_ToAgent_Pause_0_svc();
#define AUDIO_RPC_ToAgent_Stop 6
extern  HRESULT * AUDIO_RPC_ToAgent_Stop_0();
extern  HRESULT * AUDIO_RPC_ToAgent_Stop_0_svc();
#define AUDIO_RPC_ToAgent_Destroy 7
extern  HRESULT * AUDIO_RPC_ToAgent_Destroy_0();
extern  HRESULT * AUDIO_RPC_ToAgent_Destroy_0_svc();
#define AUDIO_RPC_ToAgent_Flush 8
extern  HRESULT * AUDIO_RPC_ToAgent_Flush_0();
extern  HRESULT * AUDIO_RPC_ToAgent_Flush_0_svc();
#define AUDIO_RPC_ToAgent_SetRefClock 9
extern  HRESULT * AUDIO_RPC_ToAgent_SetRefClock_0();
extern  HRESULT * AUDIO_RPC_ToAgent_SetRefClock_0_svc();
#define AUDIO_RPC_ToAgent_GetStatus 10
extern  RPCRES_LONG * AUDIO_RPC_ToAgent_GetStatus_0();
extern  RPCRES_LONG * AUDIO_RPC_ToAgent_GetStatus_0_svc();
#define AUDIO_RPC_ToAgent_SetSeeking 11
extern  HRESULT * AUDIO_RPC_ToAgent_SetSeeking_0();
extern  HRESULT * AUDIO_RPC_ToAgent_SetSeeking_0_svc();
#define AUDIO_RPC_ToAgent_BitstreamValidation 15
extern  AUDIO_RPC_FORMAT_INFO * AUDIO_RPC_ToAgent_BitstreamValidation_0();
extern  AUDIO_RPC_FORMAT_INFO * AUDIO_RPC_ToAgent_BitstreamValidation_0_svc();
#define AUDIO_RPC_ToAgent_AudioConfig 16
extern  HRESULT * AUDIO_RPC_ToAgent_AudioConfig_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AudioConfig_0_svc();
#define AUDIO_RPC_DEC_ToAgent_Init 31
extern  HRESULT * AUDIO_RPC_DEC_ToAgent_Init_0();
extern  HRESULT * AUDIO_RPC_DEC_ToAgent_Init_0_svc();
#define AUDIO_RPC_DEC_ToAgent_SkipMode 32
extern  HRESULT * AUDIO_RPC_DEC_ToAgent_SkipMode_0();
extern  HRESULT * AUDIO_RPC_DEC_ToAgent_SkipMode_0_svc();
#define AUDIO_RPC_ENC_ToAgent_Init 51
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_Init_0();
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_Init_0_svc();
#define AUDIO_RPC_ENC_ToAgent_SetBitRate 52
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetBitRate_0();
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetBitRate_0_svc();
#define AUDIO_RPC_ENC_ToAgent_StartEncoder 53
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_StartEncoder_0();
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_StartEncoder_0_svc();
#define AUDIO_RPC_ENC_ToAgent_PauseEncoder 54
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_PauseEncoder_0();
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_PauseEncoder_0_svc();
#define AUDIO_RPC_ENC_ToAgent_StopEncoder 55
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_StopEncoder_0();
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_StopEncoder_0_svc();
#define AUDIO_RPC_ENC_ToAgent_SetSourceFile 56
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetSourceFile_0();
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetSourceFile_0_svc();
#define AUDIO_RPC_ENC_ToAgent_Command 57
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_Command_0();
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_Command_0_svc();
#define AUDIO_RPC_ENC_ToAgent_MuteEncoder 58
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_MuteEncoder_0();
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_MuteEncoder_0_svc();
#define AUDIO_RPC_ENC_SetEncoder 59
extern  HRESULT * AUDIO_RPC_ENC_SetEncoder_0();
extern  HRESULT * AUDIO_RPC_ENC_SetEncoder_0_svc();
#define AUDIO_RPC_ENC_ToAgent_SetDVMixer 60
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetDVMixer_0();
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetDVMixer_0_svc();
#define AUDIO_RPC_ENC_ToAgent_SetNonRealTime 61
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetNonRealTime_0();
extern  HRESULT * AUDIO_RPC_ENC_ToAgent_SetNonRealTime_0_svc();
#define AUDIO_RPC_AO_ToAgent_Init 81
extern  HRESULT * AUDIO_RPC_AO_ToAgent_Init_0();
extern  HRESULT * AUDIO_RPC_AO_ToAgent_Init_0_svc();
#define AUDIO_RPC_AO_ToAgent_SetEaqualizer 82
extern  HRESULT * AUDIO_RPC_AO_ToAgent_SetEaqualizer_0();
extern  HRESULT * AUDIO_RPC_AO_ToAgent_SetEaqualizer_0_svc();
#define AUDIO_RPC_AO_ToAgent_ConfigDelayControl 83
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigDelayControl_0();
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigDelayControl_0_svc();
#define AUDIO_RPC_AO_ToAgent_ConfigKaraoke 84
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigKaraoke_0();
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigKaraoke_0_svc();
#define AUDIO_RPC_AO_ToAgent_ConfigMixer 85
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigMixer_0();
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigMixer_0_svc();
#define AUDIO_RPC_AO_ToAgent_ConfigPP 86
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigPP_0();
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigPP_0_svc();
#define AUDIO_RPC_AO_ToAgent_Mute 87
extern  HRESULT * AUDIO_RPC_AO_ToAgent_Mute_0();
extern  HRESULT * AUDIO_RPC_AO_ToAgent_Mute_0_svc();
#define AUDIO_RPC_AO_ToAgent_ConfigDAC 88
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigDAC_0();
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigDAC_0_svc();
#define AUDIO_RPC_AO_ToAgent_ConfigPrologic 89
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigPrologic_0();
extern  HRESULT * AUDIO_RPC_AO_ToAgent_ConfigPrologic_0_svc();
#define AUDIO_RPC_ToAgent_ADC0_Config 110
extern  HRESULT * AUDIO_RPC_ToAgent_ADC0_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_ADC0_Config_0_svc();
#define AUDIO_RPC_ToAgent_ADC1_Config 111
extern  HRESULT * AUDIO_RPC_ToAgent_ADC1_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_ADC1_Config_0_svc();
#define AUDIO_RPC_ToAgent_SPDIF_Config 112
extern  HRESULT * AUDIO_RPC_ToAgent_SPDIF_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_SPDIF_Config_0_svc();
#define AUDIO_RPC_ToAgent_AI_BackDoor_Init 113
extern  HRESULT * AUDIO_RPC_ToAgent_AI_BackDoor_Init_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AI_BackDoor_Init_0_svc();
#define AUDIO_RPC_ToAgent_SPDIF_Err_Threshold_Config 114
extern  HRESULT * AUDIO_RPC_ToAgent_SPDIF_Err_Threshold_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_SPDIF_Err_Threshold_Config_0_svc();
#define AUDIO_RPC_ToAgent_AIN_Switch_Focus 115
extern  HRESULT * AUDIO_RPC_ToAgent_AIN_Switch_Focus_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AIN_Switch_Focus_0_svc();
#define AUDIO_RPC_ToAgent_AOUT_Copy_Source 116
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Copy_Source_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Copy_Source_0_svc();
#define AUDIO_RPC_ToAgent_AOUT_Volume_Control 117
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Volume_Control_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Volume_Control_0_svc();
#define AUDIO_RPC_ToAgent_AOUT_SPDIF_Source 118
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_SPDIF_Source_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_SPDIF_Source_0_svc();
#define AUDIO_RPC_ToAgent_Karaoke_Control 119
extern  HRESULT * AUDIO_RPC_ToAgent_Karaoke_Control_0();
extern  HRESULT * AUDIO_RPC_ToAgent_Karaoke_Control_0_svc();
#define AUDIO_RPC_ToAgent_AIN_Mute 120
extern  HRESULT * AUDIO_RPC_ToAgent_AIN_Mute_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AIN_Mute_0_svc();
#define AUDIO_RPC_ToAgent_AOUT_Drop_Sample 121
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Drop_Sample_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Drop_Sample_0_svc();
#define AUDIO_RPC_ToAgent_AOUT_Pink_White_Noise 122
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Pink_White_Noise_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Pink_White_Noise_0_svc();
#define AUDIO_RPC_ToAgent_AOUT_Send_Spectrum_Data 123
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Send_Spectrum_Data_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_Send_Spectrum_Data_0_svc();
#define AUDIO_RPC_ToAgent_PlaySoundEvent 125
extern  HRESULT * AUDIO_RPC_ToAgent_PlaySoundEvent_0();
extern  HRESULT * AUDIO_RPC_ToAgent_PlaySoundEvent_0_svc();
#define AUDIO_RPC_ToAgent_AOUT_ResetPin 126
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_ResetPin_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_ResetPin_0_svc();
#define AUDIO_RPC_ToAgent_AFC_Config 127
extern  HRESULT * AUDIO_RPC_ToAgent_AFC_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AFC_Config_0_svc();
#define AUDIO_RPC_ToAgent_Audistry_Config 128
extern  HRESULT * AUDIO_RPC_ToAgent_Audistry_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_Audistry_Config_0_svc();
#define AUDIO_RPC_ToAgent_HDMI_Mute 129
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_Mute_0();
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_Mute_0_svc();
#define AUDIO_RPC_ToAgent_ADC2_Config 130
extern  HRESULT * AUDIO_RPC_ToAgent_ADC2_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_ADC2_Config_0_svc();
#define AUDIO_RPC_ToAgent_AOUT_HDMI_Set 131
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_HDMI_Set_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AOUT_HDMI_Set_0_svc();
#define AUDIO_RPC_ToAgent_AO_Only_Switchfocus 132
extern  HRESULT * AUDIO_RPC_ToAgent_AO_Only_Switchfocus_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AO_Only_Switchfocus_0_svc();
#define AUDIO_RPC_ToAgent_AIN_Data_Measurement 133
extern  HRESULT * AUDIO_RPC_ToAgent_AIN_Data_Measurement_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AIN_Data_Measurement_0_svc();
#define AUDIO_RPC_ToAgent_SET_CHANNEL_OUT_SWAP 134
extern  HRESULT * AUDIO_RPC_ToAgent_SET_CHANNEL_OUT_SWAP_0();
extern  HRESULT * AUDIO_RPC_ToAgent_SET_CHANNEL_OUT_SWAP_0_svc();
#define AUDIO_RPC_ToAgent_HDMI_OUT_EDID 200
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_OUT_EDID_0();
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_OUT_EDID_0_svc();
#define AUDIO_RPC_ToAgent_HDMI_INFO 201
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_INFO_0();
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_INFO_0_svc();
#define AUDIO_RPC_ToAgent_UpdatePTS 203
extern  HRESULT * AUDIO_RPC_ToAgent_UpdatePTS_0();
extern  HRESULT * AUDIO_RPC_ToAgent_UpdatePTS_0_svc();
#define AUDIO_RPC_ToAgent_EndOfStream 204
extern  HRESULT * AUDIO_RPC_ToAgent_EndOfStream_0();
extern  HRESULT * AUDIO_RPC_ToAgent_EndOfStream_0_svc();
#define AUDIO_RPC_ToAgent_SwitchFocus 205
extern  HRESULT * AUDIO_RPC_ToAgent_SwitchFocus_0();
extern  HRESULT * AUDIO_RPC_ToAgent_SwitchFocus_0_svc();
#define AUDIO_RPC_ToAgent_DAC_I2S_Config 206
extern  HRESULT * AUDIO_RPC_ToAgent_DAC_I2S_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_DAC_I2S_Config_0_svc();
#define AUDIO_RPC_ToAgent_DAC_SPDIF_Config 207
extern  HRESULT * AUDIO_RPC_ToAgent_DAC_SPDIF_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_DAC_SPDIF_Config_0_svc();
#define AUDIO_RPC_ToAgent_HDMI_OUT_VSDB 208
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_OUT_VSDB_0();
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_OUT_VSDB_0_svc();
#define AUDIO_RPC_ToAgent_HDMI_OUT_EDID2 209
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_OUT_EDID2_0();
extern  HRESULT * AUDIO_RPC_ToAgent_HDMI_OUT_EDID2_0_svc();
#define AUDIO_RPC_ToAgent_DecoderConfig 212
extern  HRESULT * AUDIO_RPC_ToAgent_DecoderConfig_0();
extern  HRESULT * AUDIO_RPC_ToAgent_DecoderConfig_0_svc();
#define AUDIO_RPC_ToAgent_NightMode 213
extern  HRESULT * AUDIO_RPC_ToAgent_NightMode_0();
extern  HRESULT * AUDIO_RPC_ToAgent_NightMode_0_svc();
#define AUDIO_RPC_ToAgent_PP_InitPin 214
extern  HRESULT * AUDIO_RPC_ToAgent_PP_InitPin_0();
extern  HRESULT * AUDIO_RPC_ToAgent_PP_InitPin_0_svc();
#define AUDIO_RPC_ToAgent_TrueHD_LosslessMode 228
extern  HRESULT * AUDIO_RPC_ToAgent_TrueHD_LosslessMode_0();
extern  HRESULT * AUDIO_RPC_ToAgent_TrueHD_LosslessMode_0_svc();
#define AUDIO_RPC_ToAgent_AskDebugMemoryAddress 215
extern  HRESULT * AUDIO_RPC_ToAgent_AskDebugMemoryAddress_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AskDebugMemoryAddress_0_svc();
#define AUDIO_RPC_ToAgent_PP_Config 216
extern  HRESULT * AUDIO_RPC_ToAgent_PP_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_PP_Config_0_svc();
#define AUDIO_RPC_ToAgent_PP_SRC_Config 217
extern  HRESULT * AUDIO_RPC_ToAgent_PP_SRC_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_PP_SRC_Config_0_svc();
#define AUDIO_RPC_ToAgent_PP_PL2_Config 218
extern  HRESULT * AUDIO_RPC_ToAgent_PP_PL2_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_PP_PL2_Config_0_svc();
#define AUDIO_RPC_ToAgent_PP_MIXER_Config 219
extern  HRESULT * AUDIO_RPC_ToAgent_PP_MIXER_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_PP_MIXER_Config_0_svc();
#define AUDIO_RPC_ToAgent_PP_BASS_MANAGEMENT_Config 220
extern  HRESULT * AUDIO_RPC_ToAgent_PP_BASS_MANAGEMENT_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_PP_BASS_MANAGEMENT_Config_0_svc();
#define AUDIO_RPC_ToAgent_PP_KEY_SHIFT_Config 221
extern  HRESULT * AUDIO_RPC_ToAgent_PP_KEY_SHIFT_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_PP_KEY_SHIFT_Config_0_svc();
#define AUDIO_RPC_ToAgent_PP_REVERB_Config 222
extern  HRESULT * AUDIO_RPC_ToAgent_PP_REVERB_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_PP_REVERB_Config_0_svc();
#define AUDIO_RPC_ToAgent_PP_COMFORT_LISTEN 223
extern  HRESULT * AUDIO_RPC_ToAgent_PP_COMFORT_LISTEN_0();
extern  HRESULT * AUDIO_RPC_ToAgent_PP_COMFORT_LISTEN_0_svc();
#define AUDIO_RPC_ToAgent_PP_EQ_Config 224
extern  HRESULT * AUDIO_RPC_ToAgent_PP_EQ_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_PP_EQ_Config_0_svc();
#define AUDIO_RPC_ToAgent_PP_VOCAL_REMOVER_Config 225
extern  HRESULT * AUDIO_RPC_ToAgent_PP_VOCAL_REMOVER_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_PP_VOCAL_REMOVER_Config_0_svc();
#define AUDIO_RPC_DEC_ToAgent_GetAudioFormatInfo 226
extern  AUDIO_RPC_DEC_FORMAT_INFO * AUDIO_RPC_DEC_ToAgent_GetAudioFormatInfo_0();
extern  AUDIO_RPC_DEC_FORMAT_INFO * AUDIO_RPC_DEC_ToAgent_GetAudioFormatInfo_0_svc();
#define AUDIO_RPC_ToAgent_PP_DVS_Config 227
extern  HRESULT * AUDIO_RPC_ToAgent_PP_DVS_Config_0();
extern  HRESULT * AUDIO_RPC_ToAgent_PP_DVS_Config_0_svc();
#define AUDIO_RPC_ToAgent_Karaoke_Scoring 229
extern  HRESULT * AUDIO_RPC_ToAgent_Karaoke_Scoring_0();
extern  HRESULT * AUDIO_RPC_ToAgent_Karaoke_Scoring_0_svc();
#define AUDIO_RPC_ToAgent_DEC_SetCodecKey 230
extern  HRESULT * AUDIO_RPC_ToAgent_DEC_SetCodecKey_0();
extern  HRESULT * AUDIO_RPC_ToAgent_DEC_SetCodecKey_0_svc();
#define AUDIO_RPC_ToAgent_Capability_SetMask 250
extern  HRESULT * AUDIO_RPC_ToAgent_Capability_SetMask_0();
extern  HRESULT * AUDIO_RPC_ToAgent_Capability_SetMask_0_svc();
#define AUDIO_RPC_ToAgent_AudioHalt 251
extern  HRESULT * AUDIO_RPC_ToAgent_AudioHalt_0();
extern  HRESULT * AUDIO_RPC_ToAgent_AudioHalt_0_svc();
#define AUDIO_RPC_ToAgent_Full_Capability_SetMask 252
extern  HRESULT * AUDIO_RPC_ToAgent_Full_Capability_SetMask_0();
extern  HRESULT * AUDIO_RPC_ToAgent_Full_Capability_SetMask_0_svc();
#define AUDIO_RPC_ToAgent_PrivateInfo 253
extern  AUDIO_RPC_PRIVATEINFO_RETURNVAL * AUDIO_RPC_ToAgent_PrivateInfo_0();
extern  AUDIO_RPC_PRIVATEINFO_RETURNVAL * AUDIO_RPC_ToAgent_PrivateInfo_0_svc();
#define AUDIO_RPC_ToAgent_Capability_SetPassThroughMode 254
extern  HRESULT * AUDIO_RPC_ToAgent_Capability_SetPassThroughMode_0();
extern  HRESULT * AUDIO_RPC_ToAgent_Capability_SetPassThroughMode_0_svc();
#define AUDIO_RPC_ToAgent_AI_Device_USBinfo 255
extern  USB_DEVICE_CONFIG_INFO * AUDIO_RPC_ToAgent_AI_Device_USBinfo_0();
extern  USB_DEVICE_CONFIG_INFO * AUDIO_RPC_ToAgent_AI_Device_USBinfo_0_svc();
#define AUDIO_RPC_ToAgent_Set_Dummy_Value 300
extern  HRESULT * AUDIO_RPC_ToAgent_Set_Dummy_Value_0();
extern  HRESULT * AUDIO_RPC_ToAgent_Set_Dummy_Value_0_svc();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AUDIORPC_SYSTEM_H_RPCGEN */
