
ccflags-y += -I$(srctree)/drivers/media/platform/rtk_hdmirx/reg_include
ccflags-y += -I$(srctree)/drivers/media/platform/rtk_hdmirx/
ccflags-y += -I$(srctree)/drivers/staging/android/
ccflags-y += -I$(srctree)/drivers/tee

obj-$(CONFIG_RTK_HDMIRX)    += hdmiHdmi.o hdmiEDID.o hdmiPhy.o hdmiMS.o
obj-$(CONFIG_RTK_HDCPRX_1P4_TEE) += TEE2p1_HDCP1p4_ENTRY.o
