LOCAL_32_BIT_ONLY := true

CHIP_MODEL = 0x1186
CHIP_MODEL_DEFS =  "-DIS_CHIP(MODEL)=((CHIP_MODEL & 0x100F) == MODEL)"
CHIP_MODEL_DEFS += "-DCHIP_MODEL=$(CHIP_MODEL)"
CHIP_MODEL_DEFS +=   "-DVENUS=0x1001"
CHIP_MODEL_DEFS += "-DNEPTUNE=0x1002"
CHIP_MODEL_DEFS +=    "-DMARS=0x1003"
CHIP_MODEL_DEFS += "-DJUPITER=0x1005"
CHIP_MODEL_DEFS +=  "-DSATURN=0x1006"

#CHIP_MODEL_DEFS = "-DIS_CHIP(SATURN)"
#CHIP_MODEL_DEFS += "-DCHIP_MODEL=0x1186"
CHIP_MODEL_DEFS += "-DERROR_CONCEALMENT_LEVEL=0"
CHIP_MODEL_DEFS += "-DERROR_NOTIFICATION_LEVEL=0"
CHIP_MODEL_DEFS += "-DRECOVERY_JUMP_LEVEL=128"

DEFINES+= -DERROR_CONCEALMENT_LEVEL=$(ERROR_CONCEALMENT_LEVEL)
DEFINES+= -DERROR_NOTIFICATION_LEVEL=$(ERROR_NOTIFICATION_LEVEL)


CHIP_MODEL_DEFS += -DINPUT_USE_IO_PLUGIN

CHIP_MODEL_DEFS += -DENABLE_MP4_INPUT_PLUGIN -DENABLE_ASF_INPUT_PLUGIN -DENABLE_SOCKET_INPUT_PLUGIN -DENABLE_RM_INPUT_PLUGIN
CHIP_MODEL_DEFS += -DTEST_TS -DDVB_T "-DDTV_TUNER_ID = 0" 
CHIP_MODEL_DEFS += -DFIXBUG_26492 
#define DVB_T include FIXBUG_13912, FEATURE_001, FIXBUG_1637, FIXBUG_17293, FIXBUG_2551, FIXBUG_17588, FIXBUG_17756, FIXBUG_16914, FIXBUG_17802, FIXBUG_18179, FIXBUG_1720, FIXBUG_2500, FIXBUG_1117, FEATURE_002, FEATURE_010, ADD_MULTISEC, SUPPORT_UNDEFINED_SERVICE_TYPE, SUPPORT_AVS_CODEC, ENABLE_PARSE_EXTENDED_EVENT_DESCRIPTOR in RTKExtractor/Include/Filters/NavigationFilter/SiEngine.h

CHIP_MODEL_DEFS += -D_RTK_ANDROID_ARM_ -D_RTK_1195_SIMULATOR_ -D__ANDROID__
CHIP_MODEL_DEFS += -DUSE_ION -DUSE_ION_V2

# For reduce RTKExtractor code size and reorganize code flow
CHIP_MODEL_DEFS += -DREDUCE_CODE_FLOW

# When we porting DTV ready, need open the above option for check not ready item, TODO
#CHIP_MODEL_DEFS += -DSUPPORT_NOT_CHECK_FEATURE
#CHIP_MODEL_DEFS += -DDTV_DIRECT_IO_WRITE_18382
#CHIP_MODEL_DEFS += -DENABLE_DTV_3D

#CHIP_MODEL_DEFS += "-DAP_CONFIG_WITH(APCFG_SMOOTH_TRICK_PLAY)"


APCFG_DEFS = "-DAP_CONFIG_WITH(MODULE)=((APCFG_FLAGS)&(MODULE))"
APCFG_DEFS+=                     "-DAPCFG_LIMIT=0x0000000000000000LL"
#APCFG_DEFS+=                    "-DAPCFG_HW_DVD=0x0000000000000004LL"
APCFG_DEFS+=         "-DAPCFG_SMOOTH_TRICK_PLAY=0x0000004000000000LL"

APCFG_PLAYER      =APCFG_LIMIT
APCFG_PLAYER += |APCFG_SMOOTH_TRICK_PLAY

APCFG_FLAGS = "$(APCFG_PLAYER)"

CHIP_MODEL_DEFS += $(APCFG_DEFS) -DAPCFG_FLAGS=$(APCFG_FLAGS)
